(() => {
  let ctx=null, musicOn=true, sfxOn=true, volume=.35, combat=false, ambience='camp', timer=null, unlocked=false;
  const active=new Set();
  function init(){if(ctx)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;ctx=new AudioContext();}
  function unlock(){init();if(!ctx)return;if(ctx.state==='suspended')ctx.resume();if(!unlocked){unlocked=true;syncMusic();}}
  function tone(freq,duration=.12,type='sine',gain=.06,delay=0){if(!ctx||!sfxOn)return;const osc=ctx.createOscillator(),amp=ctx.createGain(),now=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,now);amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime(Math.max(.001,gain*volume),now+.012);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(amp);amp.connect(ctx.destination);osc.start(now);osc.stop(now+duration+.02);}
  function play(kind='ui'){if(!sfxOn)return;const sounds={ui:[[520,.055,'square',.025]],shot:[[92,.11,'sawtooth',.09],[620,.045,'square',.045,.015]],hit:[[145,.16,'triangle',.07],[80,.12,'sine',.035]],miss:[[340,.07,'triangle',.025]],reload:[[240,.06,'square',.035],[420,.1,'triangle',.045,.1]],damage:[[75,.18,'sawtooth',.065]],rare:[[440,.22,'sine',.055],[660,.35,'sine',.05,.1],[880,.45,'triangle',.045,.23]],victory:[[330,.14,'triangle',.04],[494,.22,'sine',.05,.14]],loot:[[660,.08,'sine',.04],[880,.11,'triangle',.045,.08]],alert:[[210,.16,'sawtooth',.04],[170,.18,'sawtooth',.04,.2]]};for(const args of sounds[kind]||sounds.ui)tone(...args);}
  function musicStep(){if(!ctx||!musicOn||document.hidden)return;const notes=combat?[55,82.41,110]:ambience==='deep'?[61.74,92.5,123.47]:ambience==='expedition'?[65.41,98,130.81]:ambience==='faction'?[82.41,110,164.81]:[73.42,110,146.83],now=ctx.currentTime;notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===1?'triangle':'sine';o.frequency.value=f*(Math.random()<.22?1.5:1);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime((combat?.015:.009)*volume,now+.8);g.gain.exponentialRampToValueAtTime(.0001,now+3.4);o.connect(g);g.connect(ctx.destination);o.start(now);o.stop(now+3.5);const node={osc:o,gain:g};active.add(node);o.onended=()=>active.delete(node);});}
  function syncMusic(){if(!ctx||!unlocked)return;if(timer){clearInterval(timer);timer=null;}const now=ctx.currentTime;for(const node of active){node.gain.gain.cancelScheduledValues(now);node.gain.gain.setTargetAtTime(.0001,now,.045);try{node.osc.stop(now+.22);}catch{}}active.clear();if(musicOn){musicStep();timer=setInterval(musicStep,3200);}}
  function sync(mode,settings,context={}){const nextAmbience=context.expedition?(context.depth>=10?'deep':'expedition'):context.factionBase?'faction':'camp';const ambientChanged=nextAmbience!==ambience;ambience=nextAmbience;let changed=ambientChanged;if(settings){const nextMusic=settings.music!==false,nextSfx=settings.sfx!==false,nextVolume=Math.max(0,Math.min(1,Number(settings.volume??.35)));changed=changed||nextMusic!==musicOn;musicOn=nextMusic;sfxOn=nextSfx;changed=changed||nextVolume!==volume;volume=nextVolume;}const nextCombat=context.combat||['combat','combatItems','combatWeapons'].includes(mode);changed=changed||nextCombat!==combat;combat=nextCombat;if(unlocked&&changed)syncMusic();}
  window.ZoneRPGAudio={unlock,play,setMusic(value){musicOn=!!value;syncMusic();},setSfx(value){sfxOn=!!value;},sync};
  window.addEventListener('pagehide',()=>{if(timer)clearInterval(timer);for(const node of active){try{node.osc.stop();}catch{}}active.clear();});
})();
