(() => {
  const W=window.ZoneRPGWorld,I=window.ZoneRPGItems,S=window.ZoneRPGState;
  let state=S.fresh(),listeners=new Set();
  const clone=x=>JSON.parse(JSON.stringify(x)),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),rand=a=>a[Math.floor(Math.random()*a.length)];
  const emit=()=>listeners.forEach(fn=>fn());
  function log(text){state.log.push(text);state.log=state.log.slice(-10);}
  function notify(text){log(text);emit();}
  function count(id){return state.inventory.find(x=>x.id===id)?.qty||0;}
  function environment(){return W.locations[state.travelTo||state.player.location]||W.locations[state.player.location];}
  function weight(){return state.inventory.reduce((a,x)=>a+(I.items[x.id]?.weight||0)*x.qty,0);}
  function passive(){const out={protection:0,radResist:0,maxWeight:0,maxHealth:0,maxStamina:0,radPerTrip:0};const armor=I.items[state.equipment.armor]?.effect;if(armor)Object.keys(out).forEach(k=>out[k]+=(armor[k]||0));for(const id of state.equipment.artifacts){const e=I.items[id]?.effect||{};Object.keys(out).forEach(k=>out[k]+=(e[k]||0));}return out;}
  function capacity(){return Math.max(20,35+passive().maxWeight);}
  function add(id,qty=1){if(!I.items[id]||qty<=0)return 0;const item=I.items[id],current=count(id),room=capacity()-weight(),fit=item.weight===0?qty:Math.min(qty,Math.floor((room+1e-7)/item.weight));if(fit<=0)return 0;if(item.stackable&&current){state.inventory.find(x=>x.id===id).qty+=fit;}else for(let n=0;n<fit;n++)state.inventory.push({id,qty:1});return fit;}
  function remove(id,qty=1){const row=state.inventory.find(x=>x.id===id);if(!row||row.qty<qty)return false;row.qty-=qty;if(!row.qty)state.inventory=state.inventory.filter(x=>x!==row);return true;}
  function shiftRep(faction,amount){if(!faction)return;state.reputation[faction]=clamp((state.reputation[faction]||0)+amount,-100,100);}
  function unlocked(id){if(!W.locations[id])return false;if(id==='chNpp')return state.worldFlags.stationOpen&&state.player.location==='pripyat';return W.locations[state.player.location].neighbors.includes(id)||state.known.includes(id);}
  function getRoutes(){return W.locations[state.player.location].neighbors.map(id=>({id,...W.locations[id],open:unlocked(id),reason:id==='chNpp'&&!state.worldFlags.stationOpen?'Сначала найди данные о станции':null}));}
  function discover(id){if(W.locations[id]&&!state.known.includes(id)){state.known.push(id);notify(`На карте появилась новая отметка: ${W.locations[id].name}.`);}}
  function maybeReveal(){const choices=W.locations[state.player.location].neighbors.filter(id=>!state.known.includes(id));if(choices.length)discover(rand(choices));if(state.player.location==='pripyat'&&state.worldFlags.documentsFound&&!state.worldFlags.stationOpen){state.worldFlags.stationOpen=true;notify('Схема открыла путь к саркофагу ЧАЭС.');}}
  function objectiveProgress(type,target,amount=1){for(const q of state.quests.active){const d=W.quests.find(x=>x.id===q.id);if(!d)continue;if(d.type===type&&(target==null||d.target===target))q.progress+=amount;}}
  function completeQuest(q){const d=W.quests.find(x=>x.id===q.id);if(!d)return;state.player.money+=d.reward;state.statistics.earnings+=d.reward;shiftRep(d.rep,d.repGain);state.player.xp+=30;state.statistics.quests++;state.quests.completed.push(q.id);state.quests.active=state.quests.active.filter(x=>x!==q);if(q.id==='first_road'&&state.player.location==='garbage')q.step=1;notify(`Задание «${d.title}» выполнено · +${d.reward} ₽ · отношение «${W.factions[d.rep]?.name||d.rep}» улучшилось.`);}
  function questOnArrival(id){state.player.location=id;if(!state.visited.includes(id))state.visited.push(id);for(const q of [...state.quests.active]){const d=W.quests.find(x=>x.id===q.id);if(d.type==='visit'&&d.target===id)completeQuest(q);if(d.type==='route'&&id===d.target){q.step=1;notify('Свалка достигнута. Пора вернуться на Кордон.');}else if(d.type==='route'&&id===d.returnTo&&q.step===1)completeQuest(q);}if(id==='pripyat'&&state.worldFlags.documentsFound&&!state.worldFlags.stationOpen){state.worldFlags.stationOpen=true;notify('Документы раскрыли доступ к ЧАЭС.');}for(const n of W.locations[id].neighbors)discover(n);objectiveProgress('visit',id);}
  function arrive(id){state.travelTo=null;state.event=null;state.mode='play';state.panelReturn=null;state.player.trips++;questOnArrival(id);log(`Прибытие: ${W.locations[id].name}.`);emit();}
  function candidates(kind,locationId=state.player.location){const loc=W.locations[locationId]||W.locations[state.player.location],all=W.events.filter(e=>(e.kind===kind||e.kind==='both')&&loc.danger>=e.minDanger);const unseen=all.filter(e=>!state.seenEvents.includes(e.id));return unseen.length?unseen:all;}
  function eventChance(dest){const to=W.locations[dest],p=state.player,gear=passive().protection,rep=state.reputation.loners||0,carry=Math.max(0,weight()-capacity()*.7),night=p.time>=21||p.time<5;return clamp(28+to.danger*5.4-gear*20-rep*.07+carry*.8+(p.stamina<25?9:0)+(night?9:0)+(p.hunger>80||p.thirst>80?7:0),15,88);}
  function triggerEvent(kind,locationId){const options=candidates(kind,locationId);if(!options.length)return null;const e=clone(rand(options));state.seenEvents.push(e.id);state.event=e;return e;}
  function travel(id){if(state.event||state.combat)return notify('Сначала закончи текущую встречу.');const loc=W.locations[state.player.location];if(!loc.neighbors.includes(id)||!unlocked(id))return notify('Этот путь пока закрыт.');if(state.player.stamina<4)return notify('Сил не хватает. Отдохни или выпей энергетик.');const dest=W.locations[id],p=state.player;state.travelTo=id;const cost=5+dest.danger*2+(weight()>capacity()?8:0);p.stamina=clamp(p.stamina-cost);p.hunger=clamp(p.hunger+5+dest.danger);p.thirst=clamp(p.thirst+7+dest.danger);p.time=(p.time+1)%24;const res=passive();p.radiation=clamp(p.radiation+dest.rad*(1-res.radResist/100)+res.radPerTrip);if(p.radiation>=80){const dose=Math.ceil((p.radiation-75)/10);p.health=clamp(p.health-dose,0,p.maxHealth+res.maxHealth);notify(`Критический фон повреждает здоровье: −${dose}.`);}p.health=clamp(p.health-(p.hunger>80?3:0)-(p.thirst>80?4:0),0,p.maxHealth+res.maxHealth);if(p.radiation>=20)p.stamina=clamp(p.stamina-(p.radiation>=50?8:3));log(`Переход к ${dest.name}: −${cost} выносливости, +${5+dest.danger}% голода, +${7+dest.danger}% жажды.`);if(p.health<=0)return die();const chance=eventChance(id);if(Math.random()*100<chance){const e=triggerEvent('travel',id);if(e){emit();return;}}arrive(id);}
  function setAmbientEvent(){state.event={id:`arrival_${state.player.trips}`,category:'Локация',text:`${W.locations[state.player.location].layout}. ${W.locations[state.player.location].description}`,choices:[{label:'Осмотреться',action:'dismiss'},{label:'Открыть карту',action:'map'}]};}
  function explore(){if(state.event||state.combat)return notify('Сначала разберись с текущей ситуацией.');const id=state.player.location,n=state.explores[id]||0;if(n>=3)return notify('Ты уже тщательно обыскал этот сектор. Пора идти дальше.');if(state.player.stamina<12)return notify('Не хватает сил на поиск.');state.player.stamina=clamp(state.player.stamina-12);state.player.time=(state.player.time+1)%24;state.player.radiation=clamp(state.player.radiation+W.locations[id].rad*.18*(1-passive().radResist/100));state.explores[id]=n+1;objectiveProgress('explore',id);triggerEvent('explore');if(!state.event)setAmbientEvent();emit();}
  function pickLoot(type){const lists={common:['wires','bread','water','ammo918','valuables','parts','canned'],military:['ammo545','ammo762','bandage','electronics','parts'],artifact:['jellyfish','stoneflower','meatchunk','flash','gravi'],medical:['medkit','bandage','antirad','canned']};let pool=lists[type]||lists.common;if(type==='common'&&environment().danger>4)pool=pool.concat(lists.military);for(const id of pool){if(add(id,1))return id;}return null;}
  function applyEffects(effects){const p=state.player;if(!effects)return;if(effects.itemCost&&Object.entries(effects.itemCost).some(([id,n])=>count(id)<n)){const id=Object.keys(effects.itemCost).find(x=>count(x)<effects.itemCost[x]);notify(`Не хватает: ${I.items[id].name}. Остальные последствия этого выбора отменены.`);return;}if(effects.money<0&&p.money<-effects.money){notify('У тебя не хватает денег на этот выбор. Остальные последствия отменены.');return;}for(const k of ['health','stamina','hunger','thirst','radiation'])if(effects[k])p[k]=clamp(p[k]+effects[k],0,k==='health'?p.maxHealth+passive().maxHealth:100);if(effects.money){const amount=effects.money;p.money=Math.max(0,p.money+amount);if(amount>0)state.statistics.earnings+=amount;}
    if(effects.rep)Object.entries(effects.rep).forEach(([f,n])=>shiftRep(f,n));if(effects.itemCost)Object.entries(effects.itemCost).forEach(([id,n])=>{if(remove(id,n))notify(`Потрачено: ${I.items[id].name}.`);else notify(`Не хватает: ${I.items[id].name}.`);});if(effects.add)Object.entries(effects.add).forEach(([id,n])=>{const got=add(id,n);if(got)notify(`Получено: ${I.items[id].name} ×${got}.`);else notify('В рюкзаке нет места для находки.');});if(effects.lootRoll||effects.riskRoll){const id=pickLoot();if(id)notify(`Находка: ${I.items[id].name}.`);else notify('Рюкзак полон, находку пришлось оставить.');}
    if(effects.artifactRoll){const id=pickLoot('artifact');if(id){state.statistics.artifacts++;p.artifacts++;notify(`Найден артефакт «${I.items[id].name}».`);}else notify('В рюкзаке нет места для артефакта.');}if(effects.questRoll){const d=W.quests.find(q=>q.id==='field_notes');if(p.location==='yantar'&&d&&!state.worldFlags.documentsFound&&add('documents')){state.worldFlags.documentsFound=true;notify('Получены документы лаборатории. Координаты указывают на северный сектор.');}else{const id=pickLoot('medical');if(id)notify(`В благодарность передано: ${I.items[id].name}.`);}}if(effects.talkRoll){const chance=clamp(58+(state.reputation.loners||0)*.2+p.stamina*.12,25,88);if(Math.random()*100<chance){p.money+=60;shiftRep('bandits',2);notify(`Переговоры удались (шанс ${Math.round(chance)}%). Бандиты уступили за 60 ₽.`);}else {p.health=clamp(p.health-12,0,p.maxHealth);notify(`Договориться не вышло (шанс ${Math.round(chance)}%). В драке ты потерял 12 здоровья.`);}}
    if(effects.fleeRoll){const chance=clamp(68+p.stamina*.18-environment().danger*4,20,93);if(Math.random()*100>chance){p.health=clamp(p.health-9,0,p.maxHealth);notify(`Отступление сорвалось (шанс ${Math.round(chance)}%). Получено 9 урона.`);}else notify(`Ты ушёл от опасности (шанс ${Math.round(chance)}%).`);}
    if(effects.detectRoll){const chance=clamp(48+p.stamina*.22+(state.equipment.weapon==='knife'?8:0),25,91);notify(`Проверка: ${Math.round(chance)}% шанс заметить опасность.`);if(Math.random()*100<chance)notify('Ты заметил безопасный подход.');else {p.radiation=clamp(p.radiation+4);notify('Проверка не выявила угрозу; фон немного вырос.');}}
    if(effects.riskRoll&&Math.random()<.32){const hit=Math.round(5+environment().danger*1.4);p.health=clamp(p.health-hit,0,p.maxHealth+passive().maxHealth);notify(`Ловушка сработала: −${hit} здоровья.`);}if(effects.flags)Object.entries(effects.flags).forEach(([k,v])=>state.worldFlags[k]=v);if(effects.discoverRoll)maybeReveal();if(effects.tradeRoll){const id=remove('parts',1)?'parts':remove('wires',2)?'wires':null;if(id){p.money+=id==='parts'?150:90;notify(`Обмен завершён: +${id==='parts'?150:90} ₽.`);}else notify('Для обмена нужны детали или два мотка провода.');}if(effects.time){p.time=(p.time+effects.time)%24;}if(p.radiation>=25)notify('Дозиметр предупреждает: фон повышен. Антирад поможет снизить нагрузку.');if(p.health<=0)die();}
  function chooseEvent(index){if(!state.event||!state.event.choices?.[index])return;const choice=state.event.choices[index];if(choice.action==='dismiss'){state.event=null;emit();return;}if(choice.action==='map'){state.mode='map';emit();return;}if(choice.combat){startCombat(choice.combat==='autoMutant'?rand(['dog','boar','bloodsucker']):choice.combat);return;}const next=choice.effects?.nextEvent;applyEffects(choice.effects);if(state.player.health<=0)return;if(next){const chained=W.events.find(e=>e.id===next);if(chained){state.event=clone(chained);state.seenEvents.push(chained.id);emit();return;}}state.event=null;if(state.travelTo)arrive(state.travelTo);else emit();}
  function startCombat(type){const enemy=clone(W.enemyTypes[type]||W.enemyTypes.bandit);state.combat={type,enemy:{...enemy,maxHp:enemy.hp},aimed:false,log:[`${enemy.name} вступает в бой.`],turn:1};state.event=null;state.mode='combat';state.panelReturn=null;notify(`Бой: ${enemy.name} · ${enemy.hp} здоровья. Выбери действие.`);emit('combat');}
  function combatLog(text){state.combat.log.push(text);state.combat.log=state.combat.log.slice(-6);log(text);}
  function enemyHit(){if(!state.combat)return;const c=state.combat,p=state.player,e=c.enemy,armor=passive(),hit=Math.random()<e.accuracy;if(hit){const raw=Math.round(e.damage*(.84+Math.random()*.32)),loss=Math.max(1,Math.round(raw*(1-armor.protection)));p.health=clamp(p.health-loss,0,p.maxHealth+armor.maxHealth);combatLog(`${e.name} попадает: −${loss} здоровья (урон ${raw}, защита ${Math.round(armor.protection*100)}%).`);}else combatLog(`${e.name} промахивается.`);c.turn++;if(p.health<=0)die();}
  function defeatEnemy(){const c=state.combat,e=c.enemy,p=state.player;p.xp+=e.xp;p.kills++;state.statistics.kills++;p.money+=Math.round(20+Math.random()*55);const drops=e.loot.filter(()=>Math.random()<.6);for(const id of drops)add(id);shiftRep(e.faction,-5);if(e.faction==='mutants')objectiveProgress('kill','mutants');else if(['bandits','mercs'].includes(e.faction))objectiveProgress('kill','hostiles');log(`${e.name} повержен. +${e.xp} опыта; найдено: ${drops.map(x=>I.items[x].name).join(', ')||'ничего'}.`);state.combat=null;state.event=null;state.mode='play';state.panelReturn=null;if(state.player.xp>=state.player.rank*120){p.xp-=p.rank*120;p.rank++;p.maxHealth+=5;p.health=clamp(p.health+15,0,p.maxHealth);notify(`Новый опыт Зоны: ранг ${p.rank}, максимальное здоровье +5.`);}if(state.travelTo)arrive(state.travelTo);else emit();}
  function attack(){const c=state.combat;if(!c)return;const p=state.player,weapon=I.weapons[I.items[state.equipment.weapon].weaponId],ammo=weapon.ammoType,mag=state.magazines[state.equipment.weapon]||0;if(ammo&&mag<=0){combatLog('Магазин пуст. Перезаряди оружие.');return enemyHit();}if(ammo)state.magazines[state.equipment.weapon]--;let chance=weapon.accuracy+(c.aimed?.18:0)+(p.stamina-50)*.002-(p.hunger>75?.12:0)-(p.thirst>75?.1:0);chance=clamp(chance,.18,.96);c.aimed=false;if(Math.random()<chance){let damage=Math.round(weapon.damage*(.82+Math.random()*.36));if(Math.random()<weapon.critChance)damage=Math.round(damage*1.65);damage=Math.max(1,Math.round(damage*(1-c.enemy.armor)));c.enemy.hp-=damage;combatLog(`Попадание: ${weapon.name} наносит ${damage} урона (точность ${Math.round(chance*100)}%).`);if(c.enemy.hp<=0)return defeatEnemy();}else combatLog(`Промах (точность ${Math.round(chance*100)}%).`);enemyHit();}
  function aim(){if(!state.combat)return;state.combat.aimed=true;combatLog('Ты прицеливаешься. Следующий выстрел точнее на 18%.');enemyHit();}
  function reload(){if(!state.combat)return;const id=state.equipment.weapon,weapon=I.weapons[I.items[id].weaponId];if(!weapon.ammoType){combatLog('Нож не требует перезарядки.');return;}const need=weapon.magazine-(state.magazines[id]||0),have=count(weapon.ammoType);if(need<=0){combatLog('Магазин уже полон.');return;}if(!have){combatLog(`Нет боеприпасов ${I.items[weapon.ammoType].name}.`);return;}const n=Math.min(need,have);remove(weapon.ammoType,n);state.magazines[id]=(state.magazines[id]||0)+n;combatLog(`Перезаряжено за ${weapon.reloadTime.toFixed(1)} с: ${n} патронов.`);enemyHit();}
  function combatUse(id){if(!state.combat)return;const index=state.inventory.findIndex(x=>x.id===id);if(index<0)return notify('Предмета нет в рюкзаке.');useItem(index);if(state.combat)enemyHit();}
  function flee(){if(!state.combat)return;const chance=clamp(62+state.player.stamina*.2-W.locations[state.player.location].danger*4,18,92);if(Math.random()*100<chance){combatLog(`Уход удался (шанс ${Math.round(chance)}%).`);state.combat=null;state.event=null;state.mode='play';state.panelReturn=null;state.player.stamina=clamp(state.player.stamina-8);if(state.travelTo)arrive(state.travelTo);else emit();}else{combatLog(`Не удалось оторваться (шанс ${Math.round(chance)}%).`);state.player.stamina=clamp(state.player.stamina-10);enemyHit();}}
  function useItem(index){const row=state.inventory[index];if(!row)return;const d=I.items[row.id],fx=d.effect;if(!fx||['ammo','loot','quest','weapon'].includes(d.type)){notify('Этот предмет нельзя использовать напрямую.');return;}if(d.type==='armor'){state.equipment.armor=row.id;notify(`Надет ${d.name}.`);return;}if(d.type==='artifact'){const at=state.equipment.artifacts.indexOf(row.id);if(at>=0)state.equipment.artifacts.splice(at,1);else if(state.equipment.artifacts.length<2)state.equipment.artifacts.push(row.id);else return notify('Свободно только два слота артефактов. Сними один в панели персонажа.');notify(at>=0?`${d.name} снят.`:`${d.name} помещён в слот артефакта.`);return;}if(fx.ammo)return notify('Боеприпасы можно зарядить в бою.');if(fx.repair)return notify('Снаряжение исправно.');for(const k of ['health','stamina'])if(fx[k])state.player[k]=clamp(state.player[k]+fx[k],0,k==='health'?state.player.maxHealth+passive().maxHealth:100);for(const k of ['hunger','thirst','radiation'])if(fx[k])state.player[k]=clamp(state.player[k]+fx[k]);remove(row.id);notify(`${d.name} использован${d.type==='food'?'а':d.type==='drink'?'':'а'}.`);if(fx.quest==='documents'){state.worldFlags.documentsFound=true;}
  }
  function equipWeapon(id){if(!state.inventory.some(x=>x.id===id&&I.items[id].type==='weapon'))return notify('Этого оружия нет в рюкзаке.');state.equipment.weapon=id;state.magazines[id]??=0;notify(`В руках: ${I.items[id].name}.`);emit();}
  function equipArmor(id){if(!state.inventory.some(x=>x.id===id&&I.items[id].type==='armor'))return notify('Брони нет в рюкзаке.');state.equipment.armor=id;notify(`Надето: ${I.items[id].name}.`);emit();}
  function toggleArtifact(id){if(!state.inventory.some(x=>x.id===id&&I.items[id].type==='artifact'))return notify('Артефакта нет в рюкзаке.');const list=state.equipment.artifacts,i=list.indexOf(id);if(i>=0)list.splice(i,1);else if(list.length<2)list.push(id);else return notify('Доступно два слота артефактов.');emit();}
  function sell(id,qty=1){const row=state.inventory.find(x=>x.id===id);if(!row||row.qty<qty)return notify('Предмета нет в рюкзаке.');if(id===state.equipment.weapon||id===state.equipment.armor||state.equipment.artifacts.includes(id))return notify('Сначала сними экипированный предмет.');const npc=trader();if(!npc)return notify('Здесь нет торговца.');const factor=clamp(1-(state.reputation[npc.faction]||0)*.001,.8,1.25),price=Math.max(1,Math.round(I.items[id].price*.52*factor));remove(id,qty);state.player.money+=price*qty;state.statistics.earnings+=price*qty;notify(`Продано ${I.items[id].name} ×${qty} за ${price*qty} ₽.`);emit();}
  function drop(id){const row=state.inventory.find(x=>x.id===id);if(!row)return notify('Предмета нет в рюкзаке.');if(id===state.equipment.weapon||id===state.equipment.armor||state.equipment.artifacts.includes(id))return notify('Сначала сними экипированный предмет.');remove(id);notify(`Оставлено в Зоне: ${I.items[id].name}.`);emit();}
  function trader(){const loc=W.locations[state.player.location];return loc.trader?W.people[loc.trader]:null;}
  function buy(id,qty=1){const npc=trader();if(!npc)return notify('Торговец сейчас недоступен.');const item=I.items[id];if(!item)return;const factor=clamp(1-(state.reputation[npc.faction]||0)*.001,.8,1.25),price=Math.ceil(item.price*factor)*qty;if(state.player.money<price)return notify('Не хватает денег.');if(add(id,qty)<qty)return notify('Рюкзак полон. Сними лишний вес.');state.player.money-=price;notify(`Куплено ${item.name} ×${qty} за ${price} ₽.`);emit();}
  function rest(){const npc=trader(),loc=W.locations[state.player.location];if(!npc&&!loc.camp)return notify('Нужен лагерь или безопасное место для отдыха.');if(state.player.money<35)return notify('Не хватает 35 ₽ на припасы.');state.player.money-=35;state.player.health=clamp(state.player.health+25,0,state.player.maxHealth+passive().maxHealth);state.player.stamina=100;state.player.hunger=clamp(state.player.hunger+7);state.player.thirst=clamp(state.player.thirst+8);state.player.radiation=clamp(state.player.radiation-4);notify('Передышка у костра: +25 здоровья, выносливость восстановлена, фон немного спал. Потрачено 35 ₽.');}
  function questOffers(){const local=W.locations[state.player.location].npcs;return W.quests.filter(q=>local.includes(q.giver)&&!state.quests.active.some(a=>a.id===q.id)&&!state.quests.completed.includes(q.id)&&(!q.target||q.id!=='scout_pripyat'||state.known.includes('pripyat'))).map(q=>({...q,accepted:false}));}
  function acceptQuest(id){const d=W.quests.find(q=>q.id===id);if(!d||state.quests.completed.includes(id)||state.quests.active.some(q=>q.id===id))return;state.quests.active.push({id,step:0,progress:0});notify(`Принято задание: ${d.title}.`);}
  function npcAction(value){const [id,act]=value.split(':');const npc=W.people[id];if(!npc||!W.locations[state.player.location].npcs.includes(id))return notify('Этого человека здесь нет.');if(act==='fight'){return startCombat(id==='merc'?'merc':id==='military'?'merc':'bandit');}if(act==='pay'){if(state.player.money<80)return notify('У тебя нет 80 ₽ на плату за проход.');state.player.money-=80;shiftRep('bandits',4);return notify('Бандиты забрали 80 ₽ и пропустили дальше.');}if(act==='talk'){const chance=clamp(55+(state.reputation[npc.faction]||0)*.35+state.player.stamina*.12,20,92);if(Math.random()*100<chance){shiftRep(npc.faction,4);state.player.money+=25;notify(`Разговор с ${npc.name} прошёл удачно (шанс ${Math.round(chance)}%). +25 ₽ и уважение.`);}else{notify(`Доверия пока мало (шанс ${Math.round(chance)}%). Попробуй позже или поговори с другой группировкой.`);}}}
  function turnIn(id){const q=state.quests.active.find(x=>x.id===id);if(!q)return;const d=W.quests.find(x=>x.id===id);if(!W.locations[state.player.location].npcs.includes(d.giver))return notify(`Найди заказчика: ${W.people[d.giver].name}.`);if(d.type==='deliver'&&!count(d.item))return notify(`Нужно принести: ${I.items[d.item].name}.`);if(d.type==='deliverType'&&!state.inventory.some(x=>I.items[x.id].type===d.itemType))return notify('В рюкзаке нет нужного артефакта.');if(d.type==='deliver')remove(d.item,d.count||1);if(d.type==='deliverType'){const art=state.inventory.find(x=>I.items[x.id].type===d.itemType);remove(art.id,1);}if(d.type==='kill'&&q.progress<(d.count||1))return notify(`Пока выполнено ${q.progress}/${d.count}.`);if(d.type==='route'&&q.step<1)return notify('Сначала сходи на Свалку.');if(d.type==='route'&&state.player.location!==d.returnTo)return notify('Задание нужно завершить возвращением на Кордон.');completeQuest(q);emit();}
  function showEventChoice(i){chooseEvent(i);}
  function getMap(){return Object.entries(W.locations).map(([id,l])=>({id,name:l.name,danger:l.danger,known:state.known.includes(id),visited:state.visited.includes(id),current:id===state.player.location,open:unlocked(id),neighbors:l.neighbors}));}
  function getQuests(){return {active:state.quests.active.map(q=>({...W.quests.find(d=>d.id===q.id),...q})),available:questOffers(),completed:state.quests.completed.map(id=>W.quests.find(q=>q.id===id))};}
  function getShop(){const who=trader();if(!who)return null;let stock=['bandage','antirad','canned','water','energy','ammo918','ammo919','ammo545','ammo762','ammo1270','ammo9x39'];if(state.player.location==='cordon')stock.push('pm','pistol19','jacket','leather','knife','sawedoff');if(state.player.location==='agro'||state.player.location==='yantar')stock.push('stalkerSuit','aksu','shotgun','electronics','tools');if(state.player.location==='warehouses')stock.push('ak','armySuit','exoskeleton','vintar','vest');const fac=clamp(1-(state.reputation[who.faction]||0)*.001,.8,1.25);return{name:who.name,faction:who.faction,stock:[...new Set(stock)].map(id=>({id,item:I.items[id],price:Math.ceil(I.items[id].price*fac)}))};}
  function die(){state.player.health=0;state.mode='dead';state.deathSummary={trips:state.player.trips,kills:state.statistics.kills,artifacts:state.statistics.artifacts,earnings:state.statistics.earnings,quests:state.statistics.quests};state.combat=null;state.event=null;log('Ты погиб в Зоне. Последнее сохранение осталось нетронутым.');emit('death');}
  function action(name,value,extra){switch(name){case'travel':travel(value);break;case'explore':explore();break;case'event':chooseEvent(Number(value));break;case'attack':attack();break;case'aim':aim();break;case'reload':reload();break;case'flee':flee();break;case'combatUse':combatUse(value);if(state.mode==='combatItems'&&state.combat)state.mode='combat';break;case'use':useItem(Number(value));break;case'equipWeapon':equipWeapon(value);break;case'equipArmor':equipArmor(value);break;case'artifact':toggleArtifact(value);break;case'drop':drop(value);break;case'buy':buy(value,Number(extra||1));break;case'sell':sell(value,Number(extra||1));break;case'rest':rest();break;case'npcAction':npcAction(value);break;case'acceptQuest':acceptQuest(value);break;case'turnIn':turnIn(value);break;case'mainMenu':state.mode='menu';emit();break;case'setSetting':state.settings[value.key]=value.value;emit();break;case'newGame':state=S.fresh();state.mode='play';notify('Ты входишь в Зону. Сидорович ждёт у старого КПП.');setAmbientEvent();emit();break;case'load':{const r=window.ZoneRPGSave.read();if(!r.ok)return notify(r.reason==='corrupt'?'Сохранение повреждено. Начни новую игру или удали его.':'Сохранение отсутствует или создано другой версией.');state=S.sanitize(r.data,I.items,W);notify('Сохранение загружено.');emit();break;}case'save':{if(state.combat||state.travelTo||state.event&&!state.event.id.startsWith('arrival_'))return notify('Сохранение доступно после завершения текущей встречи.');const r=window.ZoneRPGSave.write(state);notify(r.ok?'Сохранение записано.':r.reason==='quota'?'В браузере недостаточно места для сохранения.':'Не удалось записать сохранение в этом браузере.');break;}case'deletePrompt':state.mode='deleteConfirm';emit();break;case'deleteSave':if(window.ZoneRPGSave.remove()){state.mode='settings';notify('Локальное сохранение удалено.');}else notify('Не удалось удалить сохранение.');break;case'settings':state.mode='settings';emit();break;case'closePanel':state.mode=state.panelReturn==='menu'?'menu':state.panelReturn==='pause'?'pause':'play';state.panelReturn=null;emit();break;case'resume':state.mode='play';state.panelReturn=null;emit();break;case'continue':if(state.combat){state.mode='combat';emit();}else if(state.event){state.mode='event';emit();}else{state.mode='play';emit();}break;case'dismissEvent':if(state.event?.id.startsWith('arrival_')){state.event=null;state.mode='play';emit();}break;case'openPanel':if(!['settings','inventory','map','quests','character','trade','people','combatItems','combatWeapons'].includes(state.mode))state.panelReturn=state.mode;state.mode=value;emit();break;case'equipSlot':{const id=value;if(I.items[id]?.type==='weapon')equipWeapon(id);else if(I.items[id]?.type==='armor')equipArmor(id);else if(I.items[id]?.type==='artifact')toggleArtifact(id);break;}default:break;}emit();}
  function getState(){const copy=clone(state),paths=[];for(const [id,l] of Object.entries(W.locations))for(const n of l.neighbors)if(id<n)paths.push([id,n]);const h=state.player.time;return {...copy,items:I.items,weapons:I.weapons,locations:W.locations,people:W.people,factions:W.factions,map:getMap(),edgePaths:paths,hasSave:window.ZoneRPGSave.has(),weight:weight(),capacity:capacity(),passive:passive(),routes:getRoutes(),quests:getQuests(),shop:getShop(),radStage:state.player.radiation<20?'безопасно':state.player.radiation<50?'лёгкое облучение':state.player.radiation<80?'опасный уровень':'критическое состояние',timeLabel:h<5||h>=21?'Ночь':h<10?'Утро':h<17?'День':'Вечер'};}
  window.ZoneRPGEngine={getState,action,onChange(fn){listeners.add(fn);},hasSave:()=>window.ZoneRPGSave.has(),eventChance,getItemWeight:weight};
})();
