// Data only: all prices, effects and equipment are consumed by the game engine.
(() => {
  const weapons = {
    knife:{name:'Охотничий нож',damage:16,accuracy:.76,magazine:0,ammoType:null,reloadTime:0,fireRate:1,critChance:.08,weaponClass:'melee',price:150,weight:.4,range:'ближний бой'},
    pm:{name:'ПМ',damage:24,accuracy:.72,magazine:8,ammoType:'ammo918',reloadTime:1.2,fireRate:.7,critChance:.1,weaponClass:'pistol',price:900,weight:.9,range:'короткая'},
    pistol19:{name:'Форт-12',damage:28,accuracy:.78,magazine:12,ammoType:'ammo919',reloadTime:1.4,fireRate:.65,critChance:.12,weaponClass:'pistol',price:1400,weight:1.1,range:'короткая'},
    sawedoff:{name:'Обрез',damage:48,accuracy:.57,magazine:2,ammoType:'ammo1270',reloadTime:1.8,fireRate:.45,critChance:.18,weaponClass:'shotgun',price:1600,weight:2.4,range:'короткая'},
    shotgun:{name:'ТОЗ-34',damage:56,accuracy:.61,magazine:2,ammoType:'ammo1270',reloadTime:2,fireRate:.42,critChance:.2,weaponClass:'shotgun',price:2600,weight:3.2,range:'короткая'},
    aksu:{name:'АКС-74У',damage:28,accuracy:.69,magazine:30,ammoType:'ammo545',reloadTime:1.8,fireRate:.9,critChance:.1,weaponClass:'rifle',price:4200,weight:3.1,range:'средняя'},
    ak:{name:'АКМ',damage:37,accuracy:.67,magazine:30,ammoType:'ammo762',reloadTime:2,fireRate:.78,critChance:.12,weaponClass:'rifle',price:5600,weight:3.8,range:'средняя'},
    vintar:{name:'Винтарь-ВС',damage:64,accuracy:.9,magazine:10,ammoType:'ammo9x39',reloadTime:2.2,fireRate:.48,critChance:.22,weaponClass:'sniper',price:12500,weight:3.7,range:'дальняя'},
    aps:{name:'АПС',damage:31,accuracy:.7,magazine:20,ammoType:'ammo918',reloadTime:1.5,fireRate:.88,critChance:.11,weaponClass:'pistol',price:2300,weight:1.2,range:'короткая'},
    ppVityaz:{name:'ПП-19 «Витязь»',damage:25,accuracy:.74,magazine:30,ammoType:'ammo919',reloadTime:1.7,fireRate:.95,critChance:.09,weaponClass:'smg',price:5200,weight:3,range:'средняя'},
    huntingRifle:{name:'Охотничья винтовка',damage:46,accuracy:.8,magazine:5,ammoType:'ammo762',reloadTime:2,fireRate:.55,critChance:.16,weaponClass:'rifle',price:3900,weight:3.5,range:'средняя'}
  };
  const items = {
    knife:{name:'Охотничий нож',type:'weapon',slot:'melee',description:'Тихое оружие для ближнего боя.',price:150,weight:.4,stackable:false,effect:null,weaponId:'knife'},
    pm:{name:'ПМ',type:'weapon',slot:'sidearm',description:'Старый, но надёжный пистолет.',price:900,weight:.9,stackable:false,effect:null,weaponId:'pm'},
    pistol19:{name:'Форт-12',type:'weapon',slot:'sidearm',description:'Пистолет под патрон 9×19.',price:1400,weight:1.1,stackable:false,effect:null,weaponId:'pistol19'},
    sawedoff:{name:'Обрез',type:'weapon',slot:'primary',description:'Два громких выстрела почти в упор.',price:1600,weight:2.4,stackable:false,effect:null,weaponId:'sawedoff'},
    shotgun:{name:'ТОЗ-34',type:'weapon',slot:'primary',description:'Охотничье ружьё с тяжёлым ударом.',price:2600,weight:3.2,stackable:false,effect:null,weaponId:'shotgun'},
    aksu:{name:'АКС-74У',type:'weapon',slot:'primary',description:'Компактный автомат для опасных маршрутов.',price:4200,weight:3.1,stackable:false,effect:null,weaponId:'aksu'},
    ak:{name:'АКМ',type:'weapon',slot:'primary',description:'Мощная винтовка под 7.62×39.',price:5600,weight:3.8,stackable:false,effect:null,weaponId:'ak'},
    vintar:{name:'Винтарь-ВС',type:'weapon',slot:'primary',description:'Редкая бесшумная винтовка для дальнего боя.',price:12500,weight:3.7,stackable:false,effect:null,weaponId:'vintar'},
    aps:{name:'АПС',type:'weapon',slot:'sidearm',description:'Тяжёлый пистолет с вместительным магазином.',price:2300,weight:1.2,stackable:false,effect:null,weaponId:'aps'},
    ppVityaz:{name:'ПП-19 «Витязь»',type:'weapon',slot:'primary',description:'Компактный пистолет-пулемёт под распространённый патрон 9×19.',price:5200,weight:3,stackable:false,effect:null,weaponId:'ppVityaz'},
    huntingRifle:{name:'Охотничья винтовка',type:'weapon',slot:'primary',description:'Точная пятизарядная винтовка для осторожных выстрелов.',price:3900,weight:3.5,stackable:false,effect:null,weaponId:'huntingRifle'},
    ammo918:{name:'Патроны 9×18',type:'ammo',description:'Боеприпасы для ПМ.',price:8,weight:.018,stackable:true,effect:{ammo:'pm',amount:8}},ammo919:{name:'Патроны 9×19',type:'ammo',description:'Боеприпасы 9×19 для Форт-12 и ПП-19 «Витязь».',price:12,weight:.02,stackable:true,effect:{ammo:'pistol19',amount:8}},ammo545:{name:'Патроны 5.45×39',type:'ammo',description:'Боеприпасы для АКС-74У.',price:16,weight:.025,stackable:true,effect:{ammo:'aksu',amount:10}},ammo762:{name:'Патроны 7.62×39',type:'ammo',description:'Тяжёлые патроны для АКМ.',price:20,weight:.03,stackable:true,effect:{ammo:'ak',amount:10}},ammo1270:{name:'Патроны 12×70',type:'ammo',description:'Дробь для охотничьего оружия.',price:14,weight:.045,stackable:true,effect:{ammo:'shotgun',amount:6}},ammo9x39:{name:'Патроны 9×39',type:'ammo',description:'Дозвуковой боеприпас для Винтаря.',price:30,weight:.035,stackable:true,effect:{ammo:'vintar',amount:5}},
    jacket:{name:'Куртка новичка',type:'armor',slot:'armor',description:'Почти не защищает, зато не мешает идти.',price:250,weight:2,effect:{protection:.05,radResist:.02,maxWeight:0}},leather:{name:'Кожаная куртка',type:'armor',slot:'armor',description:'Самодельная защита от когтей и осколков.',price:950,weight:4,effect:{protection:.13,radResist:.04,maxWeight:1}},vest:{name:'Бронежилет',type:'armor',slot:'armor',description:'Тяжёлый жилет с керамическими вставками.',price:3200,weight:8,effect:{protection:.34,radResist:.02,maxWeight:-2}},stalkerSuit:{name:'Костюм сталкера',type:'armor',slot:'armor',description:'Защищает от пуль и слабого фона.',price:5800,weight:7,effect:{protection:.22,radResist:.18,maxWeight:0}},armySuit:{name:'Армейский костюм',type:'armor',slot:'armor',description:'Усиленный костюм для опасных маршрутов.',price:9200,weight:10,effect:{protection:.39,radResist:.21,maxWeight:1}},exoskeleton:{name:'Экзоскелет',type:'armor',slot:'armor',description:'Мощная рама повышает грузоподъёмность.',price:24000,weight:16,effect:{protection:.62,radResist:.12,maxWeight:20}},
    fieldPack:{name:'Полевой рюкзак',type:'backpack',slot:'backpack',description:'Старый, но целый рюкзак. Увеличивает переносимый вес.',price:1100,weight:1.8,stackable:false,effect:{maxWeight:10}},milPack:{name:'Военный рюкзак',type:'backpack',slot:'backpack',description:'Усиленная рама и широкие лямки для тяжёлых вылазок.',price:4200,weight:3.2,stackable:false,effect:{maxWeight:17}},
    gasmask:{name:'Противогаз ПМК',type:'headgear',slot:'head',description:'Фильтрующая маска немного снижает воздействие радиации.',price:1800,weight:1.4,stackable:false,effect:{radResist:.08}},sealedHelmet:{name:'Герметичный шлем',type:'headgear',slot:'head',description:'Тяжёлый шлем с защитным визором и хорошей фильтрацией.',price:6800,weight:3.1,stackable:false,effect:{radResist:.16,protection:.04,maxStamina:-4}},
    medkit:{name:'Аптечка',type:'medicine',description:'Восстанавливает 42 здоровья.',price:180,weight:.4,stackable:true,effect:{health:42}},bandage:{name:'Бинт',type:'medicine',description:'Останавливает кровотечение и лечит на 18.',price:75,weight:.1,stackable:true,effect:{health:18}},antirad:{name:'Антирад',type:'medicine',description:'Снижает радиацию на 35.',price:240,weight:.2,stackable:true,effect:{radiation:-35}},
    canned:{name:'Консервы',type:'food',description:'Сытная тушёнка. Уменьшает голод.',price:90,weight:.45,stackable:true,effect:{hunger:-38,stamina:8}},bread:{name:'Хлеб',type:'food',description:'Черствый, но ещё съедобный.',price:35,weight:.3,stackable:true,effect:{hunger:-22}},water:{name:'Вода',type:'drink',description:'Чистая вода в пластиковой фляге.',price:45,weight:.5,stackable:true,effect:{thirst:-42}},energy:{name:'Энергетик',type:'drink',description:'Быстро возвращает силы и немного снижает жажду.',price:80,weight:.25,stackable:true,effect:{stamina:35,thirst:-15}},
    wires:{name:'Старые провода',type:'loot',description:'Медные жилы ещё можно продать технику.',price:45,weight:.8,stackable:true,effect:null},electronics:{name:'Электроника',type:'loot',description:'Плата с довоенного прибора.',price:135,weight:1.1,stackable:true,effect:null},parts:{name:'Детали',type:'loot',description:'Механические запчасти для мастерской.',price:90,weight:1.4,stackable:true,effect:null},tools:{name:'Набор инструментов',type:'loot',description:'Редкий комплект для ремонта снаряжения.',price:420,weight:2.2,stackable:false,effect:{repair:1}},documents:{name:'Документы',type:'quest',description:'Исписанные схемы подземного комплекса.',price:0,weight:.2,stackable:false,effect:{quest:'documents'}},valuables:{name:'Довоенные ценности',type:'loot',description:'Небольшие вещи с большой ценой у торговца.',price:260,weight:.3,stackable:true,effect:null},
    jellyfish:{name:'Медуза',type:'artifact',rarity:'common',description:'Снижает радиацию, но немного ослабляет организм.',price:850,weight:.4,stackable:false,effect:{radResist:.15,maxHealth:-5}},stoneflower:{name:'Каменный цветок',type:'artifact',rarity:'uncommon',description:'Защищает от пуль, усиливая радиационный фон.',price:1500,weight:.8,stackable:false,effect:{protection:.12,radPerTrip:3}},meatchunk:{name:'Ломоть мяса',type:'artifact',rarity:'uncommon',description:'Добавляет выносливости, медленно отравляя кровь.',price:1250,weight:.7,stackable:false,effect:{maxStamina:15,radPerTrip:2}},flash:{name:'Вспышка',type:'artifact',rarity:'rare',description:'Защищает от радиации и отнимает часть сил.',price:2200,weight:.5,stackable:false,effect:{radResist:.24,maxStamina:-8}},gravi:{name:'Грави',type:'artifact',rarity:'rare',description:'Увеличивает грузоподъёмность, но облучает владельца.',price:2800,weight:1.3,stackable:false,effect:{maxWeight:20,radPerTrip:5}},spark:{name:'Искра',type:'artifact',rarity:'uncommon',description:'Небольшой заряд помогает держать силы, но ускоряет усталость.',price:1900,weight:.4,stackable:false,effect:{maxStamina:8,radPerTrip:1}},nightstar:{name:'Ночная звезда',type:'artifact',rarity:'very_rare',description:'Редкий тёмный кристалл, найденный после выброса.',price:6200,weight:.6,stackable:false,effect:{radResist:.3,maxHealth:-8}},shell:{name:'Ракушка',type:'artifact',rarity:'rare',description:'Плотная оболочка смягчает попадания и отнимает выносливость.',price:3600,weight:1.1,stackable:false,effect:{protection:.18,maxStamina:-5}},
    fireball:{name:'Огненный шар',type:'artifact',rarity:'rare',description:'Тёплое ядро понемногу затягивает раны, но ускоряет жажду.',price:4100,weight:.7,stackable:false,effect:{healthRegen:1,maxHealth:8}},moonlight:{name:'Лунный свет',type:'artifact',rarity:'uncommon',description:'Мягкое свечение помогает уклониться от удара.',price:2300,weight:.4,stackable:false,effect:{evasion:.08,radResist:.05}},battery:{name:'Батарейка',type:'artifact',rarity:'rare',description:'Стабилизирует руки и повышает точность.',price:3900,weight:.5,stackable:false,effect:{accuracy:.08,maxStamina:-4}},goldfish:{name:'Золотая рыбка',type:'artifact',rarity:'very_rare',description:'Тяжёлый артефакт расширяет грузоподъёмность и медленно облучает.',price:7500,weight:1.4,stackable:false,effect:{maxWeight:25,radPerTrip:4}},soul:{name:'Душа',type:'artifact',rarity:'very_rare',description:'Редкая аномалия укрепляет здоровье и сопротивление радиации.',price:9200,weight:.6,stackable:false,effect:{maxHealth:12,radResist:.12}},needle:{name:'Игла',type:'artifact',rarity:'rare',description:'Острый кристалл повышает шанс критического попадания.',price:4400,weight:.3,stackable:false,effect:{critChance:.08,protection:-.04}},bubble:{name:'Пузырь',type:'artifact',rarity:'uncommon',description:'Пористая оболочка нейтрализует часть фона.',price:2100,weight:.7,stackable:false,effect:{radResist:.2,radPerTrip:-1}},motherBeads:{name:'Бусы Бабки',type:'artifact',rarity:'anomalous',description:'Аномальная нить быстро восстанавливает силы, но отнимает здоровье.',price:18000,weight:.2,stackable:false,effect:{healthRegen:2,maxHealth:-18,radResist:.25}}
  };
  items.echoDetector={name:'Детектор «Отклик»',type:'detector',slot:'detector',rarity:'common',description:'Простой прибор помогает находить следы аномалий.',price:1800,weight:.8,stackable:false,effect:{artifactFindChance:.12}};
  items.svarog={name:'Детектор «Сварог»',type:'detector',slot:'detector',rarity:'rare',description:'Точный сканер повышает шанс найти артефакт и немного снижает радиационный фон.',price:7200,weight:1.2,stackable:false,effect:{artifactFindChance:.23,radResist:.04}};
  const iconById={
    knife:'knife',pm:'pistol',pistol19:'pistol',aps:'pistol-heavy',sawedoff:'shotgun',shotgun:'shotgun',aksu:'rifle',ak:'rifle',ppVityaz:'smg',vintar:'sniper',huntingRifle:'sniper',
    ammo918:'ammo-pistol',ammo919:'ammo-pistol',ammo545:'ammo-rifle',ammo762:'ammo-rifle',ammo9x39:'ammo-rifle',ammo1270:'ammo-shells',
    medkit:'medkit',bandage:'bandage',antirad:'antirad',canned:'canned',bread:'ration',water:'water',energy:'energy-drink',
    jacket:'armor-light',leather:'armor-light',vest:'armor-vest',stalkerSuit:'armor-suit',armySuit:'armor-suit',exoskeleton:'armor-exo',
    gasmask:'gas-mask',sealedHelmet:'helmet',fieldPack:'backpack',milPack:'backpack',echoDetector:'detector',svarog:'detector-pro',
    jellyfish:'artifact-medusa',stoneflower:'artifact-stoneflower',meatchunk:'artifact-meatchunk',flash:'artifact-flash',gravi:'artifact-gravi',spark:'artifact-spark',nightstar:'artifact-nightstar',shell:'artifact-shell',fireball:'artifact-fireball',moonlight:'artifact-moonlight',battery:'artifact-battery',goldfish:'artifact-goldfish',soul:'artifact-soul',needle:'artifact-needle',bubble:'artifact-bubble',motherBeads:'artifact-beads',documents:'quest-document',tools:'tools',electronics:'electronics',parts:'parts',wires:'wires',valuables:'valuables'
  };
  const iconFallback=item=>{
    if(item.slot==='melee')return 'knife';
    if(item.slot==='sidearm'||item.weaponId&&weapons[item.weaponId]?.weaponClass==='pistol')return 'pistol';
    if(item.weaponId){const cls=weapons[item.weaponId]?.weaponClass;return cls==='shotgun'?'shotgun':cls==='smg'?'smg':cls==='sniper'?'sniper':cls==='melee'?'knife':'rifle';}
    if(item.type==='ammo')return item.effect?.ammo&&weapons[item.effect.ammo]?.weaponClass==='shotgun'?'ammo-shells':'ammo-rifle';
    if(item.type==='medicine')return item.effect?.radiation?'antirad':item.effect?.health>=30?'medkit':'bandage';
    if(item.type==='food')return item.name?.toLowerCase().includes('консерв')?'canned':'ration';
    if(item.type==='drink')return item.name?.toLowerCase().includes('вод')?'water':'energy-drink';
    if(item.type==='artifact')return item.rarity==='common'?'artifact-medusa':'artifact-rare';
    if(item.slot==='armor'||item.type==='armor')return 'armor-suit';
    if(item.slot==='head'||item.type==='headgear')return 'gas-mask';
    if(item.slot==='backpack'||item.type==='backpack')return 'backpack';
    if(item.slot==='detector'||item.type==='detector')return 'detector';
    if(item.type==='quest')return 'quest-document';
    return 'salvage';
  };
  for(const [id,item] of Object.entries(items))item.icon=iconById[id]||iconFallback(item);
  const armors=['jacket','leather','vest','stalkerSuit','armySuit','exoskeleton'];
  window.ZoneRPGItems={items,weapons,armors,iconFallback};
})();
