// Data only: all prices, effects and equipment are consumed by the game engine.
(() => {
  const weapons = {
    knife:{name:'Охотничий нож',damage:16,accuracy:.76,magazine:0,ammoType:null,reloadTime:0,fireRate:1,critChance:.08,weaponClass:'melee',price:150,weight:.4,range:'ближний бой'},
    pm:{name:'ПМ',damage:24,accuracy:.72,magazine:8,ammoType:'ammo918',reloadTime:1.2,fireRate:.7,critChance:.1,weaponClass:'pistol',price:900,weight:.9,range:'короткая'},
    pistol19:{name:'Форт-12',damage:28,accuracy:.78,magazine:12,ammoType:'ammo919',reloadTime:1.4,fireRate:.65,critChance:.12,weaponClass:'pistol',price:1400,weight:1.1,range:'короткая'},
    sawedoff:{name:'Обрез',damage:48,accuracy:.57,magazine:2,ammoType:'ammo1270',reloadTime:1.8,fireRate:.45,critChance:.18,weaponClass:'shotgun',price:1600,weight:2.4,range:'короткая'},
    shotgun:{name:'ТОЗ-34',damage:56,accuracy:.61,magazine:2,ammoType:'ammo1270',reloadTime:2,fireRate:.42,critChance:.2,weaponClass:'shotgun',price:2600,weight:3.2,range:'короткая'},
    aksu:{name:'АКС-74У',damage:28,accuracy:.69,magazine:30,ammoType:'ammo545',reloadTime:1.8,fireRate:.9,critChance:.1,weaponClass:'rifle',price:4200,weight:3.1,range:'средняя'},
    ak:{name:'АКМ',damage:37,accuracy:.67,magazine:30,ammoType:'ammo762',reloadTime:2,fireRate:.78,critChance:.12,weaponClass:'rifle',price:5600,weight:3.8,range:'средняя'},
    vintar:{name:'Винтарь-ВС',damage:64,accuracy:.9,magazine:10,ammoType:'ammo9x39',reloadTime:2.2,fireRate:.48,critChance:.22,weaponClass:'sniper',price:12500,weight:3.7,range:'дальняя'}
  };
  const items = {
    knife:{name:'Охотничий нож',type:'weapon',description:'Тихое оружие для ближнего боя.',price:150,weight:.4,stackable:false,effect:null,weaponId:'knife'},
    pm:{name:'ПМ',type:'weapon',description:'Старый, но надёжный пистолет.',price:900,weight:.9,stackable:false,effect:null,weaponId:'pm'},
    pistol19:{name:'Форт-12',type:'weapon',description:'Пистолет под патрон 9×19.',price:1400,weight:1.1,stackable:false,effect:null,weaponId:'pistol19'},
    sawedoff:{name:'Обрез',type:'weapon',description:'Два громких выстрела почти в упор.',price:1600,weight:2.4,stackable:false,effect:null,weaponId:'sawedoff'},
    shotgun:{name:'ТОЗ-34',type:'weapon',description:'Охотничье ружьё с тяжёлым ударом.',price:2600,weight:3.2,stackable:false,effect:null,weaponId:'shotgun'},
    aksu:{name:'АКС-74У',type:'weapon',description:'Компактный автомат для опасных маршрутов.',price:4200,weight:3.1,stackable:false,effect:null,weaponId:'aksu'},
    ak:{name:'АКМ',type:'weapon',description:'Мощная винтовка под 7.62×39.',price:5600,weight:3.8,stackable:false,effect:null,weaponId:'ak'},
    vintar:{name:'Винтарь-ВС',type:'weapon',description:'Редкая бесшумная винтовка для дальнего боя.',price:12500,weight:3.7,stackable:false,effect:null,weaponId:'vintar'},
    ammo918:{name:'Патроны 9×18',type:'ammo',description:'Боеприпасы для ПМ.',price:8,weight:.018,stackable:true,effect:{ammo:'pm',amount:8}},ammo919:{name:'Патроны 9×19',type:'ammo',description:'Боеприпасы для Форт-12.',price:12,weight:.02,stackable:true,effect:{ammo:'pistol19',amount:8}},ammo545:{name:'Патроны 5.45×39',type:'ammo',description:'Боеприпасы для АКС-74У.',price:16,weight:.025,stackable:true,effect:{ammo:'aksu',amount:10}},ammo762:{name:'Патроны 7.62×39',type:'ammo',description:'Тяжёлые патроны для АКМ.',price:20,weight:.03,stackable:true,effect:{ammo:'ak',amount:10}},ammo1270:{name:'Патроны 12×70',type:'ammo',description:'Дробь для охотничьего оружия.',price:14,weight:.045,stackable:true,effect:{ammo:'shotgun',amount:6}},ammo9x39:{name:'Патроны 9×39',type:'ammo',description:'Дозвуковой боеприпас для Винтаря.',price:30,weight:.035,stackable:true,effect:{ammo:'vintar',amount:5}},
    jacket:{name:'Куртка новичка',type:'armor',description:'Почти не защищает, зато не мешает идти.',price:250,weight:2,effect:{protection:.05,radResist:.02,maxWeight:0}},leather:{name:'Кожаная куртка',type:'armor',description:'Самодельная защита от когтей и осколков.',price:950,weight:4,effect:{protection:.13,radResist:.04,maxWeight:1}},vest:{name:'Бронежилет',type:'armor',description:'Тяжёлый жилет с керамическими вставками.',price:3200,weight:8,effect:{protection:.34,radResist:.02,maxWeight:-2}},stalkerSuit:{name:'Костюм сталкера',type:'armor',description:'Защищает от пуль и слабого фона.',price:5800,weight:7,effect:{protection:.22,radResist:.18,maxWeight:0}},armySuit:{name:'Армейский костюм',type:'armor',description:'Усиленный костюм для опасных маршрутов.',price:9200,weight:10,effect:{protection:.39,radResist:.21,maxWeight:1}},exoskeleton:{name:'Экзоскелет',type:'armor',description:'Мощная рама повышает грузоподъёмность.',price:24000,weight:16,effect:{protection:.62,radResist:.12,maxWeight:20}},
    medkit:{name:'Аптечка',type:'medicine',description:'Восстанавливает 42 здоровья.',price:180,weight:.4,stackable:true,effect:{health:42}},bandage:{name:'Бинт',type:'medicine',description:'Останавливает кровотечение и лечит на 18.',price:75,weight:.1,stackable:true,effect:{health:18}},antirad:{name:'Антирад',type:'medicine',description:'Снижает радиацию на 35.',price:240,weight:.2,stackable:true,effect:{radiation:-35}},
    canned:{name:'Консервы',type:'food',description:'Сытная тушёнка. Уменьшает голод.',price:90,weight:.45,stackable:true,effect:{hunger:-38,stamina:8}},bread:{name:'Хлеб',type:'food',description:'Черствый, но ещё съедобный.',price:35,weight:.3,stackable:true,effect:{hunger:-22}},water:{name:'Вода',type:'drink',description:'Чистая вода в пластиковой фляге.',price:45,weight:.5,stackable:true,effect:{thirst:-42}},energy:{name:'Энергетик',type:'drink',description:'Быстро возвращает силы и немного снижает жажду.',price:80,weight:.25,stackable:true,effect:{stamina:35,thirst:-15}},
    wires:{name:'Старые провода',type:'loot',description:'Медные жилы ещё можно продать технику.',price:45,weight:.8,stackable:true,effect:null},electronics:{name:'Электроника',type:'loot',description:'Плата с довоенного прибора.',price:135,weight:1.1,stackable:true,effect:null},parts:{name:'Детали',type:'loot',description:'Механические запчасти для мастерской.',price:90,weight:1.4,stackable:true,effect:null},tools:{name:'Набор инструментов',type:'loot',description:'Редкий комплект для ремонта снаряжения.',price:420,weight:2.2,stackable:false,effect:{repair:1}},documents:{name:'Документы',type:'quest',description:'Исписанные схемы подземного комплекса.',price:0,weight:.2,stackable:false,effect:{quest:'documents'}},valuables:{name:'Довоенные ценности',type:'loot',description:'Небольшие вещи с большой ценой у торговца.',price:260,weight:.3,stackable:true,effect:null},
    jellyfish:{name:'Медуза',type:'artifact',description:'Снижает радиацию, но немного ослабляет организм.',price:850,weight:.4,stackable:false,effect:{radResist:.15,maxHealth:-5}},stoneflower:{name:'Каменный цветок',type:'artifact',description:'Защищает от пуль, усиливая радиационный фон.',price:1500,weight:.8,stackable:false,effect:{protection:.12,radPerTrip:3}},meatchunk:{name:'Ломоть мяса',type:'artifact',description:'Добавляет выносливости, медленно отравляя кровь.',price:1250,weight:.7,stackable:false,effect:{staminaMax:15,radPerTrip:2}},flash:{name:'Вспышка',type:'artifact',description:'Защищает от радиации и отнимает часть сил.',price:2200,weight:.5,stackable:false,effect:{radResist:.24,maxStamina:-8}},gravi:{name:'Грави',type:'artifact',description:'Увеличивает грузоподъёмность, но облучает владельца.',price:2800,weight:1.3,stackable:false,effect:{maxWeight:20,radPerTrip:5}}
  };
  const armors=['jacket','leather','vest','stalkerSuit','armySuit','exoskeleton'];
  window.ZoneRPGItems={items,weapons,armors};
})();
