/* Personal stories extend the shared world; combat, quests and expeditions remain canonical. */
(() => {
  const W=window.ZoneRPGWorld,I=window.ZoneRPGItems;
  const arcs={
    rookie:{title:'Своё место',theme:'Первые долги, доверие и собственный путь.',faction:'loners',perk:{maxWeight:1},
      cast:[['Тихон','наставник','rookie','loners'],['Лена «Карта»','проводник','cordon','loners'],['Павлик','новичок','garbage','loners']],
      chapters:[
        ['Не чужой','rookie','Поговорить с наставником','Тихон сушит у костра чужие перчатки. «В первый день легче всего потерять себя. Пройдём тропу вместе?»','Осмотреть метки безопасной тропы','Проверить тропу самому','perception',2,'Метки сверены. Ты понимаешь, где лучше возвращаться к костру.'],
        ['Первый долг','cordon','Найти проводника','Лена заплатила за пропавшую аптечку Павлика. Он отмалчивается: у него нет денег.','Взять на себя возвращение долга','Попросить время и поручиться за Павлика','intelligence',3,'Лена согласилась ждать отчёта. Теперь это твоё слово, а не чужой долг.'],
        ['У ржавого кузова','garbage','Искать вещи Павлика','На кузове зацепилась лямка Павлика. Под машиной лежат его записи и целый полевой пакет.','Спасти записи, оставив тяжёлый лом','Забрать лом для выплаты долга','strength',3,'Ты нашёл след Павлика и вернул пакет из-под кузова.'],
        ['Цена доверия','rookie','Рассказать Тихону о находке','Тихон спрашивает, кто отправил Павлика одного. Лена просит не впутывать её: она продала ему неверную схему.','Рассказать правду и защитить новичка','Сохранить имя Лены в тайне','intelligence',3,'Тихон выслушал твой отчёт. После этих слов отношения уже не прежние.'],
        ['Обратная тропа','railway','Проверить путь к деревне','У насыпи псы прижали Павлика к вагону. Можно расчистить путь или отвлечь стаю и вывести его через дренаж.','Отогнать стаю','Вывести Павлика обходом','agility',3,'Павлик добрался до укрытия. Твои решения впервые спасли чужую жизнь.','dog'],
        ['Кем остаться','rookie','Вернуться к наставнику','Тихон кладёт рядом две карты: свободные дороги и маршруты совместных дозоров. «Теперь выбираешь ты».','Остаться независимым проводником','Работать с общими дозорами','perception',3,'Первый долг закрыт. Зона всё ещё опасна, но ты уже знаешь, за кого отвечаешь.']
      ],endings:['Своя дорога','Общее плечо'],finals:['Ты остаёшься независимым проводником. Тихон доверяет тебе людей, а не приказы.','Ты помогаешь общим дозорам. Текущую фракцию выбираешь сам; прошлое не определяет принадлежность.'],
      extra:[['rookie','Перчатки у костра','Тихон оставил сухие перчатки для того, кто вернётся последним.','Развесить остальные вещи','Павлик запомнил, что ты не прошёл мимо.'],['cordon','Цена карты','Лена показывает карту с исправленной тропой. Она больше не обещает безопасную Зону.','Попросить отметить ошибку','Карту исправили, а ошибку назвали вслух.'],['garbage','Чужой первый день','Другой новичок боится вернуться без находки.','Показать путь к укрытию','Ты дал совет, который сам недавно услышал у костра.']]},
    soldier:{title:'Старый позывной',theme:'Сослуживцы, закрытый приказ и цена верности.',faction:'military',perk:{accuracy:.015},
      cast:[['Капитан Вязов','бывший командир','checkpoint','military'],['Саша «Линия»','сослуживец','militaryDepot','military'],['Рита «Эфир»','радист','warehouses','loners']],
      chapters:[
        ['Узнанный голос','checkpoint','Назвать старый позывной','Вязов узнаёт голос, но не фамилию в новых документах. Старый патруль не вернулся со склада.','Назвать подразделение','Представиться свободным сталкером','intelligence',2,'Вязов передал маршрут пропавшего патруля. За периметром звание не защитит.'],
        ['Сломанная пломба','militaryDepot','Проверить маркировку склада','Пломба вскрыта изнутри. Под маркировкой грузов спрятан приказ о вывозе гражданских.','Узнать старую маркировку','Сверить номера с журналом караула','perception',3,'Ты сохранил копию приказа и установил последнюю смену.'],
        ['Сослуживец без оружия','southTunnel','Найти Сашу в тоннеле','Саша сидит за решёткой без автомата. Он вывел гражданских вместо выполнения приказа.','Вывести Сашу и оставить отметку для патруля','Спрятать его след от патруля','strength',3,'Саша выбрался через служебный проход. Его судьба теперь зависит от твоего отчёта.'],
        ['Копия приказа','warehouses','Связаться с радисткой','Рита может передать приказ военным или по открытой частоте. Обратного хода у передачи не будет.','Передать приказ по служебной частоте','Раскрыть приказ сталкерам','intelligence',3,'Передача ушла. Одни считают тебя свидетелем, другие — нарушителем приказа.'],
        ['Контрольная группа','militaryDepot','Проверить место сбора','На месте сбора ждёт вооружённый посредник. Он требует копию и обещает забыть о Саше.','Отказаться и удержать проход','Подменить маршрут в бумагах','intelligence',4,'Копия уцелела, проход к Саше больше не контролируется.','merc'],
        ['Последний рапорт','checkpoint','Передать последний рапорт','Вязов предлагает вернуть позывной. Рита готова стереть твой след в списках части.','Восстановить связь со старой частью','Закончить службу и защитить Сашу','endurance',3,'Последний рапорт подписан твоим именем. Дальше приказы больше не заменяют решения.']
      ],endings:['Связь восстановлена','Свободный позывной'],finals:['Ты поддерживаешь связь с частью, сохраняя право отказаться от приказа. Автоматического вступления нет.','Ты уходишь из списков части и защищаешь сослуживца. Связь с военными стала холоднее, зато Саша доверяет тебе.'],
      extra:[['checkpoint','Три копыта у будки','Бандит-свинья укладывается на старой шинели Вязова. Капитан снимает её с поста только для стирки.','Помочь вернуть шинель в будку','У караула тоже есть те, за кого отвечают без приказа.'],['militaryDepot','Неправильный номер','На ящике стоит номер подразделения, которого больше нет.','Сверить старый список','Номер оказался прикрытием для гражданского груза.'],['warehouses','Тишина в эфире','Рита оставляет минуту тишины для пропавших связистов.','Подождать у радиостанции','Она запомнила, что ты не торопил передачу.']]},
    technician:{title:'Работающий свет',theme:'Схемы, инструменты и спор о праве на технологию.',faction:'ecologists',perk:{artifactFindChance:.015},
      cast:[['Гена «Контакт»','мастер','railway','loners'],['Ира «Контур»','конкурент-техник','machineYard','loners'],['Доктор Левин','приборист','yantar','ecologists']],
      chapters:[
        ['Схема без подписи','railway','Разобрать старую схему','Гена нашёл схему резервного питания. Половину подписей смыло, но почерк знаком тебе по прежней работе.','Разобрать схему по цепям','Проверить схему на простом стенде','intelligence',3,'Ты восстановил маршрут силовой линии к машинному двору.'],
        ['Генератор Иры','machineYard','Починить генератор','Ира держит снятый регулятор. Она не отдаст работу случайному человеку, но готова разделить риск.','[Набор инструментов] Починить регулятор','Собрать временный ручной привод','strength',3,'Генератор работает на малой мощности. Твой напарник теперь знает, чего стоит твоё обещание.'],
        ['Мёртвый терминал','agro','Включить терминал','Терминал показывает не секреты мира, а список сломанных насосов. Один ещё может питать лабораторию.','Перенастроить устройство','Снять безопасную копию схемы','intelligence',4,'Ты сохранил рабочую схему узла и не перегрузил старую сеть.'],
        ['Кому принадлежит свет','yantar','Обсудить схему с Левиным','Левин просит эксклюзивный доступ. Ира считает, что свет сначала нужен полевым мастерским.','Передать копию учёным','Открыть схему для мастерских','intelligence',3,'Решение о доступе принято. Пользователи схемы будут помнить, кто получил её первым.'],
        ['Под напряжением','underground','Проверить силовой узел','Вода под узлом потрескивает. Перемычка не выдержит прямого включения. Нужен обход или рискованный замер.','[Набор инструментов] Установить перемычку','Обесточить секцию и пройти по сухому настилу','agility',3,'Узел выведен из аварийного режима. Можно закончить прибор без новой жертвы.'],
        ['Первое включение','railway','Собрать полевой прибор','Ира предлагает продать сборку. Левин ждёт открытый комплект. Гена оставил место на твоём стенде.','Оставить прибор и открыть схему','Продать сборку, сохранив чертежи','intelligence',4,'Первое включение прошло без вспышки. Работа закончена, но техника требует заботы каждый день.']
      ],endings:['Открытая мастерская','Своя сборка'],finals:['Схема доступна полевым мастерским. Ты оставляешь небольшой диагностический прибор себе.','Ты продаёшь опытную сборку и сохраняешь чертежи. Ира уважает расчёт, учёные — меньше.'],
      extra:[['railway','Лишний винт','Гена оставил винт после сборки. Это не поломка: им он помечает свою работу.','Вернуть винт на стенд','Мастер рассказал, зачем сохраняет старые детали.'],['machineYard','Чужая пайка','Ира показывает красивую, но хрупкую пайку.','Проверить контакт под нагрузкой','Под нагрузкой контакт дрогнул. Ира согласилась переделать соединение.'],['yantar','Шум прибора','Левин отличает помеху прибора от аномального сигнала.','Сверить контрольный замер','Записан шумовой профиль: полезнее громкого обещания нового артефакта.']]},
    hunter:{title:'Чужая территория',theme:'Следы, пропавший охотник и цена трофея.',faction:'loners',perk:{evasion:.015},
      cast:[['Егор «Сухарь»','охотник','rookie','loners'],['Ника «Соль»','следопыт','quarry','loners'],['Мирон','мутантолог','greenhouse','ecologists']],
      chapters:[
        ['След не стаи','rookie','Определить следы у леса','Егор пропустил встречу. На его тропе один глубокий след поверх собачьих, а на ветке висит красная нить.','[Охотник] Определить следы','Сверить след с заметками Егора','perception',3,'Тропа ведёт к Каменоломне. Зверь тяжёлый, но бережёт одну лапу.'],
        ['Пустой привал','quarry','Найти привал Егора','Ника нашла пустой привал. Она хочет трофей; ты ищешь человека. На золе сохранились следы носилок.','Идти по следам носилок','Проверить территорию хищника','perception',3,'Найдена тропа к теплицам и след живого охотника.'],
        ['Что ранит зверя','greenhouse','Показать образец Мирону','Мирон изучает шерсть: зверь не легенда, а раненый кабан с аномальными пластинами.','Передать наблюдения исследователю','Оставить координаты только охотникам','intelligence',3,'Повадки зверя записаны. Теперь ты понимаешь, почему засады у воды не работают.'],
        ['Кто выйдет первым','redforest','Подготовить выход из леса','Егор жив, но нога не держит. Ника просит оставить его в укрытии на время охоты.','Вывести Егора, отложив трофей','Подготовить засаду и оставить Егора под охраной','endurance',3,'Укрытие и обратный путь отмечены. Ты выбрал, кто и чем рискует.'],
        ['Панцирь у воды','redforest','Найти раненого секача','На воде идут кольца. Секач узнаёт запах приманки и закрывает голову костяными пластинами.','Вступить в подготовленный бой','Увести людей из его территории','agility',4,'Опасный контакт завершён. Можно решить, что важнее славы.','storyScarBoar'],
        ['Имя на трофее','greenhouse','Передать итог охоты','Мирон ждёт наблюдения, Ника — имя победителя. Егор спрашивает, вернутся ли сюда новые охотники.','Передать трофей и координаты учёным','Скрыть логово и остаться проводником','perception',4,'Охота закончена. То, как её запомнят, зависит от твоего рассказа.']
      ],endings:['Наблюдатель','Проводник живых'],finals:['Учёные получили наблюдения и образец. Слава охотника теперь связана с точностью, а не числом убитых зверей.','Ты скрываешь логово и выводишь людей обходом. Егор жив, а следующая охота не станет обязательной.'],
      extra:[['quarry','Лапа в глине','Ника ошиблась размером следа: вода размыла края.','Сравнить свежий и старый отпечаток','Она приняла поправку, хотя спорить ей привычнее.'],['greenhouse','Заметка о миграции','Мирон просит отметить свежую сводку движения мутантов.','Сверить следы со сводкой','Отмечено, как смена территории меняет повадки зверей.'],['rookie','Старый ошейник','Егор держит ошейник собаки, которой давно нет.','Выслушать охотника','Не каждый охотник измеряет прошлое трофеями.']]},
    scavenger:{title:'Долг под ржавчиной',theme:'Шайка, тайник и незакрытый долг.',faction:'bandits',perk:{maxWeight:1.5},
      cast:[['Федька «Шов»','старый напарник','garbage','bandits'],['Вера «Касса»','счётчик долгов','darkvalley','bandits'],['Данила «Рейс»','перевозчик','railway','loners']],
      chapters:[
        ['Знакомая метка','garbage','Узнать метку шайки','Федька оставил двойную черту на кузове. Вера считает старый груз твоим долгом, хотя ты его не получал.','[Мародёр] Узнать метку','Поговорить с Федькой без угроз','perception',2,'Ты узнал, где исчез груз и кто до сих пор ведёт счёт.'],
        ['Под чужим настилом','machineYard','Найти старый тайник','В настиле лежит твой прежний тайник. Пломба вскрыта, но двойное дно никто не заметил.','[Мародёр] Найти двойное дно','Осмотреть следы последнего посетителя','agility',3,'Найдена бирка груза, которую не смогли подделать.'],
        ['Кому должен груз','railway','Проверить накладную у перевозчика','Данила узнаёт бирку: груз принадлежал полевому госпиталю. Вера переписала его как собственный.','Вернуть накладную перевозчику','Оставить накладную для торга с Верой','intelligence',3,'Настоящий владелец груза установлен. Отговорка о бесхозном тайнике больше не работает.'],
        ['Старая касса','darkvalley','Обсудить долг с Верой','Вера предлагает убрать накладную. Федька согласен свидетельствовать, но тогда ему придётся уйти из шайки.','Защитить Федьку и назвать владельца груза','Признать долг по правилам шайки','strength',3,'Старая касса приняла твоё решение. Одни связи стали крепче, другие оборвались.'],
        ['Уход без свидетеля','garbage','Проверить дорогу Федьки','У выхода из Свалки стоит сборщик. Он ждёт Федьку и чужую накладную.','Защитить проход','Провести Федьку по старому водостоку','agility',3,'Федька вышел со Свалки. Накладная осталась у того, кого ты выбрал.','bandit'],
        ['Закрыть счёт','darkvalley','Закончить разговор о долге','Вера ждёт последнего слова. Данила готов вернуть имя владельца груза в записи.','Вернуться к старым связям на своих условиях','Закрыть долг и уйти из шайки','intelligence',3,'Счёт закрыт. Прошлое не исчезло, но больше не выбирает твою дорогу.']
      ],endings:['Свои условия','Чистая накладная'],finals:['Ты сохраняешь старые связи, добившись новых правил. Бандиты признают расчёт, перевозчик относится осторожнее.','Ты восстанавливаешь накладную и уходишь из шайки. Федька считает тебя союзником, старая касса — неудобным должником.'],
      extra:[['garbage','Зарубка Федьки','Федька пометил безопасную ступеньку. Такая же зарубка была на вашем первом тайнике.','Исправить сгнившую ступеньку','Напарник заметил, что ты ещё помнишь общие привычки.'],['darkvalley','Пустая графа','Вера оставила пустое место напротив имени погибшего должника.','Спросить, кто закрыл его долг','Она впервые ответила без цены.'],['railway','Мокрый груз','Данила перекладывает коробки на сухую доску.','Помочь сохранить коробки','На этот раз груз не станет бесхозным из-за чужой лени.']]},
    medic:{title:'Цена помощи',theme:'Пациенты, дефицит лекарств и ответственность.',faction:'ecologists',perk:{healingBonus:.04},
      cast:[['Ася','полевой фельдшер','cordon','loners'],['Володя «Тёплый»','раненый знакомый','rookie','loners'],['Доктор Романова','исследователь','yantar','ecologists']],
      chapters:[
        ['Не затягивать узел','cordon','Осмотреть знакомую рану','Ася показывает повязку Володи. Пальцы холодные, хотя дозиметр почти молчит.','[Медик] Осмотреть рану','Ослабить повязку и проверить пульс','intelligence',3,'Кровообращение восстановлено. Но причина слабости не похожа на обычную рану.'],
        ['Ночной пункт','rookie','Проверить запас лекарств','Ночью приходят двое раненых. Одного можно стабилизировать бинтом; второму нужна аптечка.','[Аптечка] Помочь тяжёлому пациенту','Сделать шину и распределить дежурство','intelligence',3,'Ночной пункт пережил смену. Ася запомнила, как ты распределил ограниченный запас.'],
        ['Необычный синдром','yantar','Определить симптомы у учёных','Романова видит дрожь в пробе, но запрещает давать неизвестный препарат человеку. Володя просит рискнуть.','Передать образец для контрольного анализа','Изучить пробу с полевым прибором','perception',3,'Установлена реакция на аномальную пыль. Обычные обезболивающие скрывают симптомы, а не лечат.'],
        ['Чья очередь','greenhouse','Найти чистые перевязочные материалы','В теплице сухие материалы рядом с заражённым стоком. Один пакет можно вынести, второй уже мокрый.','Сохранить запас для всего пункта','Отложить чистый пакет для Володи','agility',3,'Ты вынес чистый материал. Это решение определило, кому достанется первый курс.'],
        ['Опытный курс','yantar','Провести контроль лечения','Романова предлагает короткий контролируемый курс. Володя согласен только если ты останешься рядом.','[Медик] Использовать препарат под наблюдением','Отказаться от риска и вести поддерживающее лечение','intelligence',4,'Пациент пережил контрольный период. Ты записал и пользу, и ограничения метода.'],
        ['Кому оставить метод','cordon','Вернуться в полевой пункт','Ася ждёт карточки наблюдений. Романова предлагает закрытый протокол, чтобы исключить опасные копии.','Передать протокол учёным с открытыми наблюдениями','Оставить осторожный метод полевым медикам','intelligence',3,'Карточка Володи закрыта, работа пункта продолжается. Помощь не стала обещанием бессмертия.']
      ],endings:['Проверенный протокол','Полевое доверие'],finals:['Учёные получили проверенный протокол. Ася пользуется открытыми наблюдениями и знает ограничения лечения.','Полевые медики получили осторожную методику. Володя доверяет тебе, а учёные требуют дальнейшего контроля.'],
      extra:[['cordon','Список на двери','Ася пишет имена вместо номеров пациентов.','Помочь заполнить карточки','В карточке осталось место для человека, а не только диагноза.'],['rookie','Чашка тёплой воды','Володя просит посидеть рядом, пока остывает вода.','Остаться на короткий разговор','Он запомнил, что помощь не всегда требует лекарства.'],['yantar','Чистая проба','Романова выбросила загрязнённую пробу, потеряв день работы.','Поддержать повторный анализ','Спешка не заменила проверку — это тоже часть лечения.']]}
  };
  const qid=(bg,n)=>`personal_${bg}_${n+1}`,eid=(bg,n)=>`personal_event_${bg}_${n+1}`;
  const rewardDefs={
    rookie:['Карта Тихона','Пояс проводника','backpack','backpack',{maxWeight:9,evasion:.008},1.1],
    soldier:['Старый жетон','Памятный ПМ','weapon','sidearm',{accuracy:.008},.73],
    technician:['Схема силового узла','Диагностический датчик','detector','detector',{artifactFindChance:.025,radResist:.015},.45],
    hunter:['Карточка следов','Нож следопыта','weapon','melee',{evasion:.008},.45],
    scavenger:['Чистая накладная','Рюкзак с двойным дном','backpack','backpack',{maxWeight:12,maxStamina:-2},1.5],
    medic:['Карточка пациента','Контрольный препарат','medicine',null,{health:32,radiation:-10},.25]
  };
  for(const [bg,a]of Object.entries(arcs)){
    a.id=bg;a.npcs=a.cast.map((_,i)=>`personal_npc_${bg}_${i+1}`);a.quests=a.chapters.map((_,n)=>qid(bg,n));
    const [memo,name,type,slot,effect,weight]=rewardDefs[bg];
    I.items[`personal_${bg}_memo`]={name:memo,type:'quest',rarity:'uncommon',price:0,weight:0,stackable:true,icon:'quest-document',description:'Памятная запись личной истории. Решения также сохранены в КПК.'};
    I.items[`personal_${bg}_reward`]={name,type,slot,effect,rarity:'rare',price:bg==='medic'?450:1500,weight,stackable:type==='medicine',icon:bg==='soldier'?'pistol':bg==='hunter'?'knife':I.iconFallback({type,slot,effect,name}),description:'Награда личной истории. Умеренный полевой бонус.'};
    if(bg==='soldier'||bg==='hunter'){I.items[`personal_${bg}_reward`].weaponId=`personal_${bg}_reward`;I.weapons[`personal_${bg}_reward`]={...I.weapons[bg==='soldier'?'pm':'knife'],name,...(bg==='soldier'?{reloadTime:1.05}:{damage:17,accuracy:.78})};}
    a.cast.forEach(([name,role,home,faction],i)=>{
      const id=a.npcs[i];W.people[id]={name,role,faction,home,storyRole:role,requiresBackground:bg,personalStory:true,nonCombatant:true,sprite:id,questLinks:[...a.quests],greeting:'Он помнит вашу общую историю. Текущая запись в КПК подскажет, к чему вернуться.'};W.locations[home].npcs.push(id);W.events.push({id:'npc_story_'+id,category:'Личная история · '+name,kind:'quest',locations:[home],requiresBackground:bg,personalStory:true,storyContact:true,rarity:'common',text:role+' возвращается к вашему общему делу.',stages:[{id:'contact',text:name+' помнит общее дело. Можно сверить запись с текущим поручением или просто поговорить.',choices:[{label:'Обсудить личные поручения',action:'questPanel'},{label:'Спросить о старых знакомых',finish:true,effects:{knowledge:name+': '+a.theme},resultText:'Собеседник делится знакомыми именами, не обещая лёгкого решения.'},{label:'Поблагодарить и уйти',finish:true,resultText:'Разговор закончен. Записи и отношения остаются в КПК.'}]}]});
    });
    a.chapters.forEach((c,n)=>{
      const [title,target,action,text,label,alternate,stat,min,result,enemy]=c,giver=a.npcs[n===0||n===5?0:n===1||n===4?1:2],home=W.people[giver].home,id=qid(bg,n),eventId=eid(bg,n);
      const finish=(label,choice,fx={},when={})=>({label,finish:true,when:{...when},effects:{...fx,story:{background:bg,chapter:n,choice,npc:giver}},resultText:result});
      const choices=[finish(label,'a',{rep:{[a.faction]:2}},bg==='technician'&&[1,4].includes(n)?{items:{tools:1}}:bg==='medic'&&n===1?{items:{medkit:1}}:{}),finish(alternate,'b',{rep:{[bg==='soldier'?'loners':bg==='scavenger'?'loners':a.faction]:2}}),finish(`[${stat==='intelligence'?'Интеллект':stat==='perception'?'Восприятие':stat==='strength'?'Сила':stat==='endurance'?'Выносливость':'Ловкость'} ${min}] Проверить решение перед действием`,'careful',{stamina:-2},{attributes:{[stat]:min}}),{label:'Отложить и вернуться позже',finish:true,resultText:'Ты сохраняешь отметку. Поручение и гарантированный путь остаются доступными.'}];
      if(bg==='medic'&&n===1)choices[0].effects.itemCost={medkit:1};
      if(enemy){choices[0]={label,combat:enemy,enemyId:enemy,nextStage:'evidence',resultText:'Ты выбираешь позицию.',winText:'Контакт завершён. Нужно проверить, что осталось у прохода.',fleeText:'Ты отступил. Обход остаётся доступным.'};}
      if(n>=2)choices.splice(choices.length-1,0,finish('[Доверие] Попросить знакомого проверить план','careful',{stamina:4},{storyTrust:{npc:giver,min:1}}));if(n===3){choices[0].effects.rep={[a.faction]:6};choices[1].effects.rep={[a.faction]:-6,loners:4};}const context='';
      W.events.push({id:eventId,category:'Личная история · '+title,kind:'explore',requiresBackground:bg,personalStory:true,storyChapter:n,unique:true,tags:null,storyTags:['personal','background-specific','story-chapter','once'],locations:[target],rarity:'uncommon',text:text+context,stages:[
        {id:'brief',text:text,choices:[{label:'Принять личное поручение',when:{questMissing:id},effects:{startQuest:id},nextStage:'field',resultText:'Поручение записано. Награда выдаётся только после отчёта заказчику.'},{label:action,when:{questActive:id},nextStage:'field',resultText:'Ты возвращаешься к отмеченному делу.'},{label:'Сейчас не время',finish:true,resultText:'Отметка осталась в КПК. Вернуться можно через местное действие или встречу.'}]},
        {id:'field',text,choices},
        ...(enemy?[{id:'evidence',text:'После стычки проверь следы и вернись к заказчику. Если противник не побеждён, можно закончить дело обходом.',choices:[finish('Осмотреть следы после боя','a',{}, {combatWon:true}),finish(alternate,'b')]}]:[])
      ]});
      W.quests.push({id,title:'Личная история · '+title,text:'Выполни личное дело: '+action+'. Отчёт: '+W.people[giver].name+' — '+W.locations[home].name+'.',type:'personal',personalStory:true,backgroundId:bg,storyChapter:n,target,count:1,giver,rep:a.faction,repGain:2,reward:90+n*35,giverLocations:[home],turnInLocations:[home],requiresDialogue:true,autoTurnInEligible:false,rewardTrigger:'turnIn',requiredCompletedQuest:n? a.quests[n-1]:null});
    });
    a.extra.forEach(([loc,title,text,label,result],n)=>W.events.push({id:`personal_side_${bg}_${n+1}`,category:'Личная история · '+title,kind:'explore',personalStory:true,requiresBackground:bg,storySide:true,storyChapter:n,unique:true,storyTags:['personal','background-specific','once'],locations:[loc],rarity:'uncommon',text,stages:[{id:'contact',text,choices:[{label,finish:true,effects:{storySide:{background:bg,index:n,npc:a.npcs[n],trust:1},knowledge:title+': '+result},resultText:result},{label:'Выслушать и продолжить путь',finish:true,effects:{storySide:{background:bg,index:n,npc:a.npcs[n],trust:0}},resultText:'Ты запомнил встречу. Она не меняет маршрут личного поручения.'}]}]}));
  }
  W.enemyTypes.storyScarBoar={...W.enemyTypes.ironBoar,name:'Секач с красным шрамом',visual:'ironBoar',hp:108,damage:16,accuracy:.5,xp:48,loot:['meatchunk'],description:'Раненый секач из личной охоты. Бережёт лапу и закрывает голову пластинами.',intro:'Вода дрожит у берега. Зверь хромает, но тяжёлый бросок всё ещё опасен.'};
  const bounded=(x,lo,hi,f=0)=>Number.isFinite(x)?Math.min(hi,Math.max(lo,Math.floor(x))):f;
  function fresh(bg,adapted=false){return{backgroundId:bg,currentChapter:0,currentQuest:qid(bg,0),completedSteps:[],importantChoices:{},relatedNPCs:[...arcs[bg].npcs],unlockedEvents:[eid(bg,0)],endings:[],rewards:[],pendingRewards:[],relationships:{},sideEvents:[],log:[],cooldownUntil:0,missedEncounters:0,adapted};}
  function normalize(raw,bg,worldClock,completed,legacy=false){
    const s=fresh(bg,legacy),a=arcs[bg];if(!raw||raw.backgroundId!==bg)return s;
    s.currentChapter=bounded(raw.currentChapter,0,6);s.completedSteps=a.quests.filter(id=>completed.includes(id));
    // Canonical manual quest claims determine progression, not a stale UI chapter index.
    s.currentChapter=0;while(s.currentChapter<6&&s.completedSteps.includes(a.quests[s.currentChapter]))s.currentChapter++;
    s.currentQuest=s.currentChapter<6?qid(bg,s.currentChapter):null;
    s.importantChoices={};for(const [id,value]of Object.entries(raw.importantChoices||{}))if(a.quests.includes(id)&&['a','b','careful'].includes(value))s.importantChoices[id]=value;
    s.sideEvents=(Array.isArray(raw.sideEvents)?raw.sideEvents:[]).filter(id=>W.events.some(e=>e.id===id&&e.requiresBackground===bg&&e.storySide));
    s.endings=s.currentChapter===6?[a.endings[s.importantChoices[qid(bg,5)]==='b'?1:0]]:[];
    s.rewards=[...new Set((Array.isArray(raw.rewards)?raw.rewards:[]).filter(id=>id===`personal_${bg}_memo`||id===`personal_${bg}_reward`))];
    s.pendingRewards=[...new Set((Array.isArray(raw.pendingRewards)?raw.pendingRewards:[]).filter(id=>(id===`personal_${bg}_memo`||id===`personal_${bg}_reward`)&&!s.rewards.includes(id)))];
    s.relationships={};for(const id of a.npcs){const r=raw.relationships?.[id];if(r)s.relationships[id]={trust:bounded(r.trust,-5,5),hostility:bounded(r.hostility,0,5),ally:r.ally===true,dead:r.dead===true,choices:(Array.isArray(r.choices)?r.choices:[]).filter(x=>a.quests.includes(x)).slice(-6)};}
    s.unlockedEvents=s.currentChapter<6?[eid(bg,s.currentChapter)]:[];s.log=(Array.isArray(raw.log)?raw.log:[]).filter(x=>typeof x==='string').slice(-24);s.cooldownUntil=bounded(raw.cooldownUntil,0,worldClock+4);s.missedEncounters=bounded(raw.missedEncounters,0,4);s.adapted=raw.adapted===true;return s;
  }
  const current=s=>arcs[s.backgroundId]?.chapters[s.personalStory.currentChapter];
  function eligible(e,s,loc){const p=s.personalStory;if(e.requiresBackground!==s.backgroundId)return false;if(e.storyContact)return !p.relationships[e.id.slice(10)]?.dead;if(!e.locations.includes(loc)||p.cooldownUntil>s.worldClock)return false;if(e.storySide)return !p.sideEvents.includes(e.id)&&e.storyChapter<=p.currentChapter;return p.currentChapter===e.storyChapter&&!p.completedSteps.includes(qid(s.backgroundId,e.storyChapter))&&!s.quests.active.some(q=>q.id===p.currentQuest&&q.progress>=1);}
  function context(s){const p=s.personalStory,a=arcs[s.backgroundId],c=current(s);return{title:a.title,theme:a.theme,chapter:p.currentChapter+1,chapterTitle:c?.[0],description:c?.[3],location:c?.[1],action:c?.[2],questId:p.currentQuest,eventId:c?eid(s.backgroundId,p.currentChapter):null,ready:s.quests.active.some(q=>q.id===p.currentQuest&&q.progress>=1),cooldown:Math.max(0,p.cooldownUntil-s.worldClock),complete:p.currentChapter===6,summary:p.endings.length?a.finals[p.importantChoices[qid(s.backgroundId,5)]==='b'?1:0]:null,npcs:a.npcs,perk:p.endings.length?(p.importantChoices[qid(s.backgroundId,5)]==='b'?({rookie:{evasion:.01},soldier:{evasion:.012},technician:{maxWeight:1},hunter:{maxWeight:1},scavenger:{evasion:.01},medic:{radResist:.025}}[s.backgroundId]):a.perk):{}};}
  function remember(p,id,quest,choice,trust=1){const r=p.relationships[id]||(p.relationships[id]={trust:0,hostility:0,ally:false,dead:false,choices:[]});r.trust=Math.max(-5,Math.min(5,r.trust+trust));r.hostility=Math.max(0,Math.min(5,r.hostility+(choice==='b'?1:0)));r.ally=r.trust>=2;r.choices=[...new Set([...r.choices,quest])].slice(-6);}
  function resolve(s,fx){const p=s.personalStory,id=qid(s.backgroundId,fx.chapter),q=s.quests.active.find(q=>q.id===id);if(fx.background!==s.backgroundId||fx.chapter!==p.currentChapter||!q||q.progress>=1)return false;q.progress=1;p.importantChoices[id]=fx.choice;remember(p,fx.npc,id,fx.choice,fx.choice==='b'?-1:1);p.log.push(arcs[s.backgroundId].chapters[fx.chapter][0]+' · '+(fx.choice==='a'?W.events.find(e=>e.id===eid(s.backgroundId,fx.chapter)).stages.find(x=>x.id==='field').choices[0].label:fx.choice==='b'?W.events.find(e=>e.id===eid(s.backgroundId,fx.chapter)).stages.find(x=>x.id==='field').choices[1].label:'проверенное решение'));p.log=p.log.slice(-24);return true;}
  function complete(s,id){const p=s.personalStory;if(id!==p.currentQuest||p.completedSteps.includes(id))return;const n=p.currentChapter;p.completedSteps.push(id);p.currentChapter++;p.currentQuest=p.currentChapter<6?qid(s.backgroundId,p.currentChapter):null;p.cooldownUntil=s.worldClock+3;p.missedEncounters=0;p.unlockedEvents=p.currentQuest?[eid(s.backgroundId,p.currentChapter)]:[];p.log.push('Глава завершена: '+arcs[s.backgroundId].chapters[n][0]);if(n===2)p.pendingRewards.push(`personal_${s.backgroundId}_memo`);if(n===5){p.endings=[arcs[s.backgroundId].endings[p.importantChoices[id]==='b'?1:0]];p.pendingRewards.push(`personal_${s.backgroundId}_reward`);p.log.push('Личная история завершена · '+p.endings[0]);}}
  window.ZoneRPGStories={arcs,fresh,normalize,current,eligible,context,resolve,complete,qid,eid,remember};
})();
