(() => {
  const VERSION=2, KEY='zonerpg-pda-save';
  const clamp=(n,min,max,def=0)=>Number.isFinite(Number(n))?Math.max(min,Math.min(max,Number(n))):def;
  function fresh(){return {version:VERSION,mode:'menu',player:{health:100,maxHealth:100,stamina:100,maxStamina:100,hunger:14,thirst:12,radiation:0,money:620,rank:1,xp:0,kills:0,trips:0,artifacts:0,location:'cordon',time:8},inventory:[{id:'knife',qty:1},{id:'pm',qty:1},{id:'jacket',qty:1},{id:'ammo918',qty:28},{id:'medkit',qty:1},{id:'bandage',qty:2},{id:'canned',qty:2},{id:'water',qty:2}],equipment:{weapon:'pm',armor:'jacket',artifacts:[]},magazines:{pm:8},reputation:{loners:5,bandits:-10,duty:0,freedom:0,military:-5,ecologists:0,mercs:0,mutants:-10,monolith:-25},quests:{active:[{id:'first_road',step:0,progress:0}],completed:[]},known:['cordon','rookie','checkpoint','garbage'],visited:['cordon'],seenEvents:[],takenCaches:[],explores:{},worldFlags:{documentsFound:false,stationOpen:false},travelTo:null,event:null,combat:null,log:['Ты входишь в Зону. На Кордоне ещё можно передумать.'],settings:{scale:1,reduceMotion:false},statistics:{earnings:0,artifacts:0,kills:0,quests:0}};}
  function sanitize(input,items,world){const base=fresh();if(!input||typeof input!=='object'||input.version!==VERSION)return base;const defaults=fresh().player,p=input.player&&typeof input.player==='object'?input.player:{};base.player={...defaults,...p};base.player.maxHealth=clamp(p.maxHealth,60,250,defaults.maxHealth);base.player.maxStamina=clamp(p.maxStamina,50,150,defaults.maxStamina);base.player.health=clamp(p.health,0,base.player.maxHealth+25,defaults.health);base.player.stamina=clamp(p.stamina,0,base.player.maxStamina,defaults.stamina);for(const k of ['hunger','thirst','radiation'])base.player[k]=clamp(p[k],0,100,defaults[k]);base.player.money=clamp(p.money,0,999999,defaults.money);for(const k of ['rank','xp','kills','trips','artifacts','time'])base.player[k]=clamp(p[k],k==='rank'?1:0,k==='time'?23:99999,defaults[k]);if(!world.locations[base.player.location])base.player.location='cordon';
    if(Array.isArray(input.inventory)){const inventory=[];for(const x of input.inventory){if(!x||!items[x.id]||Number(x.qty)<=0)continue;const qty=items[x.id].stackable?clamp(x.qty,1,9999,1):1,existing=inventory.find(y=>y.id===x.id);if(existing&&items[x.id].stackable)existing.qty=Math.min(9999,existing.qty+qty);else inventory.push({id:x.id,qty});}base.inventory=inventory;}
    base.equipment={...base.equipment,...(input.equipment||{})};if(!items[base.equipment.weapon]?.weaponId)base.equipment.weapon='pm';if(!items[base.equipment.armor]||items[base.equipment.armor].type!=='armor')base.equipment.armor='jacket';base.equipment.artifacts=Array.isArray(base.equipment.artifacts)?base.equipment.artifacts.filter(id=>items[id]?.type==='artifact'&&base.inventory.some(x=>x.id===id)).slice(0,2):[];for(const id of [base.equipment.weapon,base.equipment.armor])if(!base.inventory.some(x=>x.id===id))base.inventory.push({id,qty:1});
    base.magazines={...base.magazines,...(input.magazines||{})};for(const id of Object.keys(base.magazines)){const w=window.ZoneRPGItems.weapons[id];if(!w){delete base.magazines[id];continue;}base.magazines[id]=clamp(base.magazines[id],0,w.magazine||0,0);}base.reputation={...base.reputation,...(input.reputation||{})};for(const k of Object.keys(base.reputation))base.reputation[k]=clamp(base.reputation[k],-100,100,0);
    base.quests={active:Array.isArray(input.quests?.active)?input.quests.active.filter(q=>world.quests.some(d=>d.id===q.id)).map(q=>({id:q.id,step:clamp(q.step,0,5),progress:clamp(q.progress,0,99)})):base.quests.active,completed:Array.isArray(input.quests?.completed)?[...new Set(input.quests.completed.filter(id=>world.quests.some(q=>q.id===id)))]:[]};
    base.known=Array.isArray(input.known)?input.known.filter(id=>world.locations[id]):base.known;base.visited=Array.isArray(input.visited)?input.visited.filter(id=>world.locations[id]):base.visited;base.seenEvents=Array.isArray(input.seenEvents)?input.seenEvents.filter(id=>world.events.some(e=>e.id===id)):[];base.takenCaches=Array.isArray(input.takenCaches)?input.takenCaches.filter(x=>typeof x==='string'&&x.length<80):[];
    base.explores={};if(input.explores&&typeof input.explores==='object')for(const [id,n] of Object.entries(input.explores))if(world.locations[id])base.explores[id]=clamp(n,0,3);if(input.worldFlags&&typeof input.worldFlags==='object')for(const k of Object.keys(base.worldFlags))base.worldFlags[k]=Boolean(input.worldFlags[k]);if(input.settings&&typeof input.settings==='object'){base.settings.scale=Number(input.settings.scale);base.settings.reduceMotion=Boolean(input.settings.reduceMotion);}base.settings.scale=[1,1.1].includes(base.settings.scale)?base.settings.scale:1;
    if(input.statistics&&typeof input.statistics==='object')for(const k of Object.keys(base.statistics))base.statistics[k]=clamp(input.statistics[k],0,999999,0);base.log=Array.isArray(input.log)?input.log.filter(x=>typeof x==='string').slice(-10):base.log;base.travelTo=null;base.event=null;base.combat=null;base.mode='play';return base;}
  window.ZoneRPGState={VERSION,KEY,fresh,sanitize};
})();
