(() => {
  const root = document.getElementById('overlay-root');
  let api, current = 'menu';
  const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function show(html, kind='panel') { current=kind; root.innerHTML=`<div class="overlay-backdrop"><section class="overlay-card ${kind}" role="dialog" aria-modal="true">${html}</section></div>`; root.hidden=false; }
  function close(){if(current==='settings'&&api?.getState().mode==='menu'){menu();return;}root.hidden=true;root.innerHTML='';current='play';api?.resume();}
  function button(action,label,cls=''){return `<button type="button" class="${cls}" data-action="${esc(action)}">${label}</button>`;}
  function shell(title,body,foot=''){return `<button class="overlay-close" data-action="close" aria-label="Закрыть">×</button><div class="panel-label">ZONE RPG · ПЕРИМЕТР</div><h2>${esc(title)}</h2>${body}<div class="overlay-footer">${foot||button('close','Закрыть','secondary-button')}<span>ESC — назад</span></div>`;}
  function menu(){api=window.ZoneRPG;const has=api?.hasSave();show(`<div class="menu-logo">ZONE<span>RPG</span></div><div class="panel-label">ОДИНОЧНАЯ ЭКСПЕДИЦИЯ</div><h1>Периметр</h1><p>Серая долина молчит. Дозиметр — нет.</p><div class="menu-actions">${has?button('continue','Продолжить','primary-button'):''}${button('new',has?'Новая игра':'Начать игру','primary-button')}${button('settings','Настройки','secondary-button')}</div><small>Сохранение хранится локально в этом браузере.</small>`,'menu');}
  function inventory(){const s=api.getState(),catalog=api.catalog.items;const rows=s.inventory.map((it,i)=>{const d=catalog[it.id];return `<article class="item-card"><div class="item-icon">${d.type==='weapon'?'⌁':d.type==='artifact'?'◇':d.type==='ammo'?'▪':'+'}</div><div class="item-copy"><strong>${esc(d.name)} <small>×${it.qty}</small></strong><p>${esc(d.description)}</p><small>${d.weight} кг · ${d.value} ₽</small></div><div class="item-actions">${d.type==='weapon'?button(`equip:${i}`,s.equipped===it.id?'В руках':'Взять'):''}${d.type==='consumable'?button(`use:${i}`,'Использовать'):''}${button(`drop:${i}`,'Выбросить','text-button')}</div></article>`}).join('')||'<p class="empty-state">Рюкзак пуст. Обыскивай тайники и противников.</p>';show(shell('Рюкзак',`<div class="panel-meta">${s.weight.toFixed(1)} / 24 кг · ${s.inventory.reduce((a,x)=>a+x.qty,0)} предметов</div><div class="item-list">${rows}</div>`),'inventory');}
  function journal(){const s=api.getState(),rows=s.quests.map(q=>`<article class="quest-card ${q.done?'done':''}"><span class="quest-mark">${q.done?'✓':'⌖'}</span><div><strong>${esc(q.title)}</strong><p>${esc(q.description)}</p><small>${q.done?'ВЫПОЛНЕНО':`ПРОГРЕСС · ${q.progress} / ${q.goal}`} · НАГРАДА ${q.reward} ₽</small></div></article>`).join('');show(shell('Журнал заданий',`<div class="panel-meta">Активные поручения и завершённые дела</div><div class="quest-list">${rows}</div>`),'journal');}
  function settings(){const s=api.getState();show(shell('Настройки',`<div class="settings-row"><div><strong>Размер интерфейса</strong><small>Масштаб HUD</small></div><select data-setting="scale"><option value="1" ${s.settings.scale===1?'selected':''}>Обычный</option><option value="1.1" ${s.settings.scale===1.1?'selected':''}>Крупный</option></select></div><p class="muted">Управление: WASD/стрелки — ходьба, E — действие, ЛКМ — огонь, R — перезарядка, I — рюкзак, J — журнал, 1–3 — оружие.</p><div>${button('reset-save','Удалить сохранение','text-button')}</div>`),'settings');}
  function trade(){const t=api.getTrade(),s=api.getState(),ids=new Set([...t.stock.map(x=>x.id),...s.inventory.map(x=>x.id)]),rows=[...ids].map(id=>{const d=api.catalog.items[id],stock=t.stock.find(x=>x.id===id),owned=s.inventory.find(x=>x.id===id);return `<article class="item-card"><div class="item-copy"><strong>${esc(d.name)} <small>у торговца ×${stock?.qty||0} · у тебя ×${owned?.qty||0}</small></strong><p>${esc(d.description)}</p><small>${stock?`Купить: ${stock.buy} ₽`:'Нет в продаже'} · продать: ${Math.max(1,Math.round(d.value*.55))} ₽</small></div><div class="item-actions">${stock?.qty?button(`buy:${id}`,'Купить'):''}${owned?button(`sell:${id}`,'Продать','text-button'):''}</div></article>`}).join('');show(shell('Торговец · Седой',`<div class="panel-meta">Наличные: ${t.money.toLocaleString('ru-RU')} ₽ · Запасы меняются со временем</div><div class="item-list">${rows}</div>${button('deliver','Сдать 3 электронных блока · 500 ₽','primary-button')}`),'trade');}
  function loot(){const d=api.getLoot();show(shell(d.title,`<p>${esc(d.description)}</p><div class="item-list">${d.items.map(it=>`<article class="item-card"><div class="item-copy"><strong>${esc(api.catalog.items[it.id].name)} <small>×${it.qty}</small></strong></div>${button(`take:${it.id}`,'Забрать')}</article>`).join('')||'<p class="empty-state">Здесь больше ничего нет.</p>'}</div>`),'loot');}
  function camp(){show(shell('Лагерь у дороги',`<p>Торговец Седой разбил стоянку у старой дороги. Можно передохнуть и обменяться снаряжением.</p><div class="menu-actions">${button('rest','Передохнуть','primary-button')}${button('trade','Торговать','secondary-button')}${button('close','Отойти','text-button')}</div>`),'camp');}
  function death(){show(`<div class="panel-label">СВЯЗЬ ПОТЕРЯНА</div><h1>Экспедиция прервана</h1><p>Здоровье закончилось. Можно вернуться к последней точке сохранения.</p><div class="menu-actions">${api.hasSave()?button('load','Загрузить сохранение','primary-button'):''}${button('new','Начать заново','secondary-button')}</div>`,'death');}
  function pause(){show(`<div class="panel-label">ZONE RPG · ПЕРИМЕТР</div><h2>Пауза</h2><div class="menu-actions">${button('resume','Вернуться в игру','primary-button')}${button('save','Сохранить','secondary-button')}${button('settings','Настройки','secondary-button')}${button('main','Главное меню','text-button')}</div>`,'pause');}
  function render(kind){api=window.ZoneRPG;if(!['menu','death'].includes(kind))api.pause();({menu,inventory,journal,settings,trade,loot,camp,death,pause}[kind]||menu)();}
  root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close'||a==='resume'){close();return;}if(a==='main'){api.mainMenu();menu();return;}if(a==='continue'){api.load();close();return;}if(a==='new'){api.newGame();close();return;}if(a==='load'){api.load();close();return;}if(a==='settings'){settings();return;}if(a==='inventory'){inventory();return;}if(a==='journal'){journal();return;}if(a==='trade'){trade();return;}if(a==='loot'){loot();return;}if(a==='camp'){camp();return;}if(a==='death'){death();return;}if(a==='rest'){api.rest();close();return;}if(a==='save'){api.save();close();return;}if(a==='reset-save'){api.resetSave();settings();return;}if(a==='deliver'){api.deliver();trade();return;}if(a.startsWith('buy:')){api.buy(a.slice(4));trade();return;}if(a.startsWith('sell:')){api.sell(a.slice(5));trade();return;}if(a.startsWith('take:')){api.take(a.slice(5));loot();return;}if(a.startsWith('use:')){api.use(Number(a.slice(4)));inventory();return;}if(a.startsWith('equip:')){api.equip(Number(a.slice(6)));inventory();return;}if(a.startsWith('drop:')){api.drop(Number(a.slice(5)));inventory();}});
  root.addEventListener('change',e=>{if(e.target.dataset.setting)api.setSetting(e.target.dataset.setting,e.target.type==='checkbox'?e.target.checked:Number(e.target.value));});
  window.ZoneRPGUI={open:render,close,get current(){return current;},showMessage(text){const el=document.getElementById('game-message');el.textContent=text;el.classList.add('visible');}};
})();
