// World graph and content definitions. Data can grow without changing the UI.
(() => {
  const locations = {
    cordon:{name:'Кордон',description:'Железная дорога, старый КПП и поля, уходящие в туман. Здесь Зона ещё притворяется обычной землёй.',neighbors:['garbage','rookie','checkpoint'],danger:1,rad:4,mutants:7,bandits:9,stalkers:26,npcs:['sidorovich','rookie'],trader:'sidorovich',camp:true,tags:['south'],layout:'Тихие поля и заброшенный блокпост'},
    rookie:{name:'Деревня новичков',description:'Несколько уцелевших хат и костёр, вокруг которого новички делят байки и патроны.',neighbors:['cordon','garbage'],danger:1,rad:2,mutants:5,bandits:3,stalkers:38,npcs:['rookie'],trader:null,camp:true,tags:['south'],layout:'Деревня у старой дороги'},
    checkpoint:{name:'Военный блокпост',description:'Бетонные блоки, прожектор и солдаты, которым не нравится чужое любопытство.',neighbors:['cordon','garbage'],danger:2,rad:5,mutants:3,bandits:6,stalkers:9,npcs:['military'],trader:null,tags:['south','military'],layout:'Пост на южном периметре'},
    garbage:{name:'Свалка',description:'Километры ржавого металла. Под ногами звенит стекло, а из груды кузовов кто-то наблюдает.',neighbors:['cordon','rookie','checkpoint','agro','darkvalley','wild'],danger:2,rad:12,mutants:15,bandits:24,stalkers:22,npcs:['bar','loner'],trader:'bar',camp:true,tags:['center'],layout:'Кладбище техники'},
    agro:{name:'Агропром',description:'Промышленный комплекс и сырые подвалы. Военные давно ушли, но эхо шагов осталось.',neighbors:['garbage','yantar','darkvalley'],danger:3,rad:18,mutants:22,bandits:14,stalkers:21,npcs:['technician','duty'],trader:'technician',tags:['center'],layout:'Промзона и затопленные тоннели'},
    darkvalley:{name:'Тёмная долина',description:'Низина с чёрной водой и силуэтами труб. Ночью здесь лучше не задерживаться.',neighbors:['garbage','agro','swamp','warehouses','wild'],danger:4,rad:24,mutants:32,bandits:34,stalkers:9,npcs:['bandits'],trader:null,tags:['east'],layout:'Трубы и низкие холмы'},
    swamp:{name:'Болота',description:'Топь скрывает старые тропы. В камышах шевелится что-то тяжёлое.',neighbors:['darkvalley','yantar'],danger:4,rad:21,mutants:37,bandits:8,stalkers:12,npcs:['ecologist'],trader:null,tags:['north'],layout:'Топи и редкие сухие островки'},
    yantar:{name:'Янтарь',description:'Озеро под пепельным небом и лаборатория, из которой иногда доносится гул.',neighbors:['agro','swamp','redforest'],danger:4,rad:42,mutants:25,bandits:5,stalkers:16,npcs:['bar','ecologist','technician'],trader:'technician',tags:['north'],layout:'Берег озера и периметр лаборатории'},
    wild:{name:'Дикая территория',description:'Открытая местность между складами и свалкой. Снайперская позиция меняется каждый день.',neighbors:['garbage','darkvalley','warehouses'],danger:5,rad:17,mutants:20,bandits:38,stalkers:8,npcs:['merc'],trader:null,tags:['center','hostile'],layout:'Открытое поле и редкие укрытия'},
    warehouses:{name:'Военные склады',description:'Колонны бронетехники под маскировочной сетью. «Свобода» держит здесь свой рубеж.',neighbors:['darkvalley','wild','redforest','pripyat'],danger:5,rad:26,mutants:22,bandits:10,stalkers:12,npcs:['freedom','merc'],trader:'freedomTrader',tags:['north','military'],layout:'Складские ангары и лесополоса'},
    redforest:{name:'Рыжий лес',description:'Сосны покрыты рыжей пылью. Компас ведёт себя странно, а тропы меняются местами.',neighbors:['yantar','warehouses','pripyat'],danger:6,rad:54,mutants:38,bandits:8,stalkers:12,npcs:['ecologist'],trader:null,tags:['north'],layout:'Рыжие сосны и выжженная просека'},
    pripyat:{name:'Припять',description:'Пустые многоэтажки и площадь, где ветер гоняет обрывки афиш.',neighbors:['warehouses','redforest','chNpp'],danger:7,rad:48,mutants:45,bandits:14,stalkers:7,npcs:['loner','ecologist'],trader:null,tags:['north','endgame'],layout:'Городские кварталы и площадь'},
    chNpp:{name:'ЧАЭС · Саркофаг',description:'Сердце Зоны. За бетонными стенами приборы сходят с ума.',neighbors:['pripyat'],danger:10,rad:92,mutants:60,bandits:14,stalkers:0,npcs:[],trader:null,tags:['endgame','final'],layout:'Периметр станции'},
  };
  const people = {
    sidorovich:{name:'Сидорович',role:'торговец',faction:'loners',greeting:'Не стой у двери. В Зоне даже стены слышат.'},bar:{name:'Бармен',role:'торговец',faction:'loners',greeting:'Сначала расчёт, потом разговоры.'},technician:{name:'Техник Кардан',role:'техник',faction:'loners',greeting:'Инструменты есть? Тогда поговорим.'},rookie:{name:'Новичок Лёха',role:'сталкер',faction:'loners',greeting:'Слыхал, на Свалке нашли целый ящик патронов.'},loner:{name:'Одинокий сталкер',role:'сталкер',faction:'loners',greeting:'Держимся вместе — дольше проживём.'},military:{name:'Сержант КПП',role:'военный',faction:'military',greeting:'Документы и цель визита.'},duty:{name:'Долговец',role:'патруль',faction:'duty',greeting:'Чистим Зону от мутантов. Можешь помочь.'},ecologist:{name:'Учёный',role:'эколог',faction:'ecologists',greeting:'Любые данные о поле будут полезны.'},bandits:{name:'Главарь бандитов',role:'враждебный',faction:'bandits',greeting:'Плата за проход. Быстро.'},merc:{name:'Наёмник',role:'наёмник',faction:'mercs',greeting:'Работа есть? Тогда говори.'},freedom:{name:'Свободовец',role:'патруль',faction:'freedom',greeting:'Зона не должна принадлежать военным.'},freedomTrader:{name:'Торговец Свободы',role:'торговец',faction:'freedom',greeting:'Для своих цены мягче.'}
  };
  const factions={loners:{name:'Одиночки',color:'#adba83'},bandits:{name:'Бандиты',color:'#a68162'},duty:{name:'Долг',color:'#b96853'},freedom:{name:'Свобода',color:'#75a17c'},military:{name:'Военные',color:'#8595a2'},ecologists:{name:'Учёные',color:'#d6c87c'},mercs:{name:'Наёмники',color:'#87949e'},mutants:{name:'Мутанты',color:'#a18467'},monolith:{name:'Монолит',color:'#b19c91'}};
  const enemyTypes={bandit:{name:'Бандит',hp:54,damage:11,accuracy:.58,armor:.04,weapon:'pm',loot:['ammo918','valuables','parts'],faction:'bandits',xp:18},rookie:{name:'Озлобленный новичок',hp:42,damage:8,accuracy:.55,armor:0,weapon:'knife',loot:['bread','ammo918'],faction:'loners',xp:12},merc:{name:'Наёмник',hp:88,damage:16,accuracy:.7,armor:.2,weapon:'aksu',loot:['ammo545','medkit','parts'],faction:'mercs',xp:36},dog:{name:'Слепой пёс',hp:34,damage:10,accuracy:.64,armor:0,weapon:'knife',loot:['meatchunk'],faction:'mutants',xp:10},boar:{name:'Кабан',hp:78,damage:17,accuracy:.62,armor:.08,weapon:'knife',loot:['meatchunk','canned'],faction:'mutants',xp:22},bloodsucker:{name:'Кровосос',hp:105,damage:20,accuracy:.72,armor:.12,weapon:'knife',loot:['flash','meatchunk'],faction:'mutants',xp:44},controller:{name:'Контролёр',hp:125,damage:23,accuracy:.76,armor:.16,weapon:'knife',loot:['jellyfish','electronics'],faction:'mutants',xp:65},monolith:{name:'Монолитовец',hp:118,damage:21,accuracy:.72,armor:.3,weapon:'ak',loot:['ammo762','armySuit','valuables'],faction:'monolith',xp:55}};
  const quests=[
    {id:'first_road',title:'Первый маршрут',text:'Дойди до Свалки, затем вернись на Кордон.',type:'route',target:'garbage',returnTo:'cordon',reward:450,rep:'loners',repGain:8,giver:'sidorovich'},
    {id:'parts_run',title:'Детали для Кардана',text:'Найди 3 набора деталей и доставь их технику.',type:'deliver',item:'parts',count:3,reward:600,rep:'loners',repGain:6,giver:'technician'},
    {id:'field_notes',title:'Полевые заметки',text:'Исследуй Янтарь и принеси учёным документы.',type:'deliver',item:'documents',count:1,reward:900,rep:'ecologists',repGain:12,giver:'ecologist'},
    {id:'mutant_cull',title:'Тихий тракт',text:'Одолей двух мутантов на болотах или в Тёмной долине.',type:'kill',target:'mutants',count:2,reward:800,rep:'duty',repGain:10,giver:'duty'},
    {id:'bandit_problem',title:'Долг за проход',text:'Победи двух бандитов или наёмников.',type:'kill',target:'hostiles',count:2,reward:750,rep:'loners',repGain:7,giver:'sidorovich'},
    {id:'artifact_sample',title:'Образец поля',text:'Найди любой артефакт и доставь учёным.',type:'deliverType',itemType:'artifact',count:1,reward:700,rep:'ecologists',repGain:8,giver:'ecologist'},
    {id:'scout_pripyat',title:'Городская разведка',text:'Доберись до Припяти и вернись на Свалку.',type:'route',target:'pripyat',returnTo:'garbage',reward:1600,rep:'loners',repGain:12,giver:'bar'},
    {id:'station',title:'Последний рубеж',text:'Открой путь к ЧАЭС и достигни Саркофага.',type:'visit',target:'chNpp',reward:3000,rep:'ecologists',repGain:15,giver:'ecologist'}
  ];
  const eventSeeds=[
    {category:'Тайники',kind:'travel',minDanger:1,lines:['У ржавого кузова торчит край матерчатого рюкзака.','Под бетонной плитой видна металлическая защёлка.','В высокой траве мерцает стекло аптечной банки.','Старая путевая будка приоткрыта, внутри что-то блеснуло.','На обочине лежит промокшая сумка с чужой нашивкой.'],choices:[{label:'Осмотреть осторожно',effects:{lootRoll:true,stamina:-4}},{label:'Проверить дозиметром',effects:{radiation:-2,lootRoll:true}},{label:'Не рисковать',effects:{stamina:3}}]},
    {category:'Аномалии',kind:'both',minDanger:2,lines:['Дозиметр зачастил у невидимой границы поля.','Воздух впереди дрожит, а галька медленно поднимается.','На земле мерцают следы недавнего выброса.','Сухие листья вращаются в воронке без ветра.','Между деревьями тихо звенит металл.'],choices:[{label:'Обойти поле',effects:{stamina:-5,time:1}},{label:'Бросить болт и пройти',effects:{radiation:8,lootRoll:true,stamina:-2}},{label:'Поискать артефакт',effects:{radiation:15,artifactRoll:true}}]},
    {category:'Сталкеры',kind:'travel',minDanger:1,lines:['Из придорожной канавы поднимает руку усталый сталкер.','Одинокий путник просит поделиться водой.','У костра незнакомец предлагает обмен.','Раненый разведчик знает короткий путь.','Сталкер с потёртой нашивкой ищет попутчика.'],choices:[{label:'Помочь припасами',effects:{itemCost:{water:1},rep:{loners:4},questRoll:true}},{label:'Поговорить и разойтись',effects:{rep:{loners:2},stamina:3}},{label:'Пройти мимо',effects:{}}]},
    {category:'Бандиты',kind:'travel',minDanger:2,lines:['Трое людей перекрыли дорогу и требуют «плату за воздух».','Из-за остова машины выходят вооружённые бандиты.','На мосту тебя ждёт засада с самодельным шлагбаумом.','Бандитский дозор заметил рюкзак и зовёт старшего.','Кто-то передёрнул затвор в высокой траве.'],choices:[{label:'Отдать 80 ₽',effects:{money:-80,rep:{bandits:3}}},{label:'Попробовать договориться',effects:{talkRoll:true,rep:{bandits:2}}},{label:'Сражаться',combat:'bandit'},{label:'Рвануть в обход',effects:{fleeRoll:true,health:-4,stamina:-12}}]},
    {category:'Мутанты',kind:'both',minDanger:2,lines:['В кустах хрустнула ветка, слишком тяжело для человека.','Стая слепых псов режет путь через просеку.','Низкое рычание доносится из бетонной трубы.','Из камышей несётся кабан с окровавленными боками.','В темноте мелькнул высокий силуэт.'],choices:[{label:'Подготовиться и атаковать',combat:'autoMutant'},{label:'Обойти, потеряв время',effects:{stamina:-10,time:1}},{label:'Отступить',effects:{fleeRoll:true,stamina:-8}}]},
    {category:'Находки',kind:'explore',minDanger:1,lines:['Под обломками найден аккуратно завёрнутый свёрток.','В брошенном вагончике остались банки и патроны.','Среди хлама обнаружилась коробка с инструментами.','Чья-то записная книжка пережила выброс.','В пустой будке сохранились чистая вода и консервы.'],choices:[{label:'Забрать находку',effects:{lootRoll:true,questRoll:true}},{label:'Сначала осмотреть следы',effects:{detectRoll:true,lootRoll:true}},{label:'Оставить на месте',effects:{}}]},
    {category:'Погода и выбросы',kind:'travel',minDanger:2,lines:['Небо темнеет; по радио шипит предупреждение о выбросе.','Гроза гонит тебя к бетонному укрытию.','Пепельный ветер сбивает дыхание на открытом участке.','Вдали вспыхивает горизонт, птицы резко замолкают.','Радиоактивный дождь застал в низине.'],choices:[{label:'Искать укрытие',effects:{time:1,stamina:-4,radiation:-3}},{label:'Переждать под накидкой',effects:{health:-3,radiation:5}},{label:'Продолжить путь',effects:{radiation:12,stamina:-9,time:1}}]},
    {category:'Торговля и услуги',kind:'explore',minDanger:1,lines:['Полевой торговец раскрыл ящик с остатками снаряжения.','Техник готов обменять инструмент на полезные детали.','У костра предлагают выгодную сделку с патронами.','Сталкер продаёт карту местных аномалий.','В полевом лазарете остались лекарства по себестоимости.'],choices:[{label:'Купить припасы · 60 ₽',effects:{money:-60,lootRoll:true}},{label:'Обменять детали',effects:{tradeRoll:true}},{label:'Отказаться',effects:{}}]},
    {category:'Сюжетные сигналы',kind:'both',minDanger:1,lines:['Приёмник поймал обрывок координат: «...старый тоннель...».','На частоте одиночек передают просьбу о помощи.','На стене свежим мелом нарисован знак безопасного пути.','В документах упоминается лабораторный сектор на севере.','Кто-то называет по радио твою фамилию и резко замолкает.'],choices:[{label:'Записать координаты',effects:{discoverRoll:true,questRoll:true,rep:{ecologists:1}}},{label:'Ответить по рации',effects:{rep:{loners:2},lootRoll:true}},{label:'Сменить частоту',effects:{stamina:2}}]},
    {category:'Лагеря и отдых',kind:'explore',minDanger:1,lines:['В небольшой землянке тлеет печь и никого не видно.','У костра можно согреться, но припасы придётся оплатить.','Старый навес защищает от ветра и радиационного дождя.','В палатке оставили чистую ткань и флягу.','Сталкеры поделились слухами о безопасной тропе.'],choices:[{label:'Отдохнуть · 40 ₽',effects:{money:-40,health:8,stamina:30,hunger:6,thirst:5}},{label:'Спросить новости',effects:{rep:{loners:2},discoverRoll:true}},{label:'Идти дальше',effects:{}}]},
    {category:'Риски и выбор',kind:'both',minDanger:1,lines:['На дороге лежит брошенный военный планшет с зашифрованной картой.','В пыльной комнате за дверью тихо капает вода.','Чужой рюкзак привязан к тонкой проволоке.','В разбитой лаборатории мигает аварийный терминал.','За стеной кто-то зовёт на помощь, но голос звучит неестественно.'],choices:[{label:'Рискнуть и проверить',effects:{riskRoll:true,lootRoll:true}},{label:'Сначала оценить опасность',effects:{detectRoll:true,stamina:-3}},{label:'Отойти',effects:{}}]}
  ];
  const variants=['',' Повторный след',' Следы у насыпи',' На старой тропе',' За линией леса'];
  const events=[];
  eventSeeds.forEach((seed,si)=>seed.lines.forEach((text,vi)=>events.push({id:`event_${si+1}_${vi+1}`,category:seed.category,kind:seed.kind,minDanger:seed.minDanger,text:text+variants[vi],choices:seed.choices.map(choice=>({...choice,effects:choice.effects?{...choice.effects}:undefined}))})));
  window.ZoneRPGWorld={locations,people,factions,enemyTypes,quests,events,eventSeeds};
})();
