// World graph and content definitions. Data can grow without changing the UI.
(() => {
  const locations = {
    cordon:{name:'Кордон',description:'Железная дорога, старый КПП и поля, уходящие в туман. Здесь Зона ещё притворяется обычной землёй.',neighbors:['garbage','rookie','checkpoint'],danger:1,rad:4,mutants:7,bandits:9,stalkers:26,npcs:['sidorovich','rookie'],trader:'sidorovich',camp:true,tags:['south'],layout:'Тихие поля и заброшенный блокпост'},
    rookie:{name:'Деревня новичков',description:'Несколько уцелевших хат и костёр, вокруг которого новички делят байки и патроны.',neighbors:['cordon','garbage'],danger:1,rad:2,mutants:5,bandits:3,stalkers:38,npcs:['rookie'],trader:null,camp:true,tags:['south'],layout:'Деревня у старой дороги'},
    checkpoint:{name:'Военный блокпост',description:'Бетонные блоки, прожектор и солдаты, которым не нравится чужое любопытство.',neighbors:['cordon','garbage'],danger:2,rad:5,mutants:3,bandits:6,stalkers:9,npcs:['military'],trader:null,tags:['south','military'],layout:'Пост на южном периметре'},
    garbage:{name:'Свалка',description:'Километры ржавого металла. Под ногами звенит стекло, а из груды кузовов кто-то наблюдает.',neighbors:['cordon','rookie','checkpoint','agro','darkvalley','wild'],danger:2,rad:12,mutants:15,bandits:24,stalkers:22,npcs:['bar','loner'],trader:'bar',camp:true,tags:['center'],layout:'Кладбище техники'},
    agro:{name:'Агропром',description:'Промышленный комплекс и сырые подвалы. Военные давно ушли, но эхо шагов осталось.',neighbors:['garbage','yantar','darkvalley'],danger:3,rad:18,mutants:22,bandits:14,stalkers:21,npcs:['technician','duty'],trader:'technician',tags:['center'],layout:'Промзона и затопленные тоннели'},
    darkvalley:{name:'Тёмная долина',description:'Низина с чёрной водой и силуэтами труб. Ночью здесь лучше не задерживаться.',neighbors:['garbage','agro','swamp','warehouses','wild'],danger:4,rad:24,mutants:32,bandits:34,stalkers:9,npcs:['bandits'],trader:null,tags:['east'],layout:'Трубы и низкие холмы'},
    swamp:{name:'Болота',description:'Топь скрывает старые тропы. В камышах шевелится что-то тяжёлое.',neighbors:['darkvalley','yantar'],danger:4,rad:21,mutants:37,bandits:8,stalkers:12,npcs:['ecologist'],trader:null,tags:['north'],layout:'Топи и редкие сухие островки'},
    yantar:{name:'Янтарь',description:'Озеро под пепельным небом и лаборатория, из которой иногда доносится гул.',neighbors:['agro','swamp','redforest'],danger:4,rad:42,mutants:25,bandits:5,stalkers:16,npcs:['bar','ecologist','technician'],trader:'technician',tags:['north'],layout:'Берег озера и периметр лаборатории'},
    wild:{name:'Дикая территория',description:'Открытая местность между складами и свалкой. Снайперская позиция меняется каждый день.',neighbors:['garbage','darkvalley','warehouses'],danger:5,rad:17,mutants:20,bandits:38,stalkers:8,npcs:['merc'],trader:null,tags:['center','hostile'],layout:'Открытое поле и редкие укрытия'},
    warehouses:{name:'Военные склады',description:'Колонны бронетехники под маскировочной сетью. «Свобода» держит здесь свой рубеж.',neighbors:['darkvalley','wild','redforest','pripyat'],danger:5,rad:26,mutants:22,bandits:10,stalkers:12,npcs:['freedom','merc'],trader:'freedomTrader',tags:['north','military'],layout:'Складские ангары и лесополоса'},
    redforest:{name:'Рыжий лес',description:'Сосны покрыты рыжей пылью. Компас ведёт себя странно, а тропы меняются местами.',neighbors:['yantar','warehouses','pripyat'],danger:6,rad:54,mutants:38,bandits:8,stalkers:12,npcs:['ecologist'],trader:null,tags:['north'],layout:'Рыжие сосны и выжженная просека'},
    pripyat:{name:'Припять',description:'Пустые многоэтажки и площадь, где ветер гоняет обрывки афиш.',neighbors:['warehouses','redforest','chNpp'],danger:7,rad:48,mutants:45,bandits:14,stalkers:7,npcs:['loner','ecologist'],trader:null,tags:['north','endgame'],layout:'Городские кварталы и площадь'},
    chNpp:{name:'ЧАЭС · Саркофаг',description:'Сердце Зоны. За бетонными стенами приборы сходят с ума.',neighbors:['pripyat'],danger:10,rad:92,mutants:60,bandits:14,stalkers:0,npcs:[],trader:null,tags:['endgame','final'],layout:'Периметр станции'},
  };
  const people = {
    sidorovich:{name:'Сидорович',role:'торговец',faction:'loners',greeting:'Не стой у двери. В Зоне даже стены слышат.'},bar:{name:'Бармен',role:'торговец',faction:'loners',greeting:'Сначала расчёт, потом разговоры.'},technician:{name:'Техник Кардан',role:'техник',faction:'loners',greeting:'Инструменты есть? Тогда поговорим.'},rookie:{name:'Новичок Лёха',role:'сталкер',faction:'loners',greeting:'Слыхал, на Свалке нашли целый ящик патронов.'},loner:{name:'Одинокий сталкер',role:'сталкер',faction:'loners',greeting:'Держимся вместе — дольше проживём.'},military:{name:'Сержант КПП',role:'военный',faction:'military',greeting:'Документы и цель визита.'},duty:{name:'Долговец',role:'патруль',faction:'duty',greeting:'Чистим Зону от мутантов. Можешь помочь.'},ecologist:{name:'Учёный',role:'эколог',faction:'ecologists',greeting:'Любые данные о поле будут полезны.'},bandits:{name:'Главарь бандитов',role:'враждебный',faction:'bandits',greeting:'Плата за проход. Быстро.'},merc:{name:'Наёмник',role:'наёмник',faction:'mercs',greeting:'Работа есть? Тогда говори.'},freedom:{name:'Свободовец',role:'патруль',faction:'freedom',greeting:'Зона не должна принадлежать военным.'},freedomTrader:{name:'Торговец Свободы',role:'торговец',faction:'freedom',greeting:'Для своих цены мягче.'}
  };
  const factions={loners:{name:'Одиночки',color:'#adba83'},bandits:{name:'Бандиты',color:'#a68162'},duty:{name:'Долг',color:'#b96853'},freedom:{name:'Свобода',color:'#75a17c'},military:{name:'Военные',color:'#8595a2'},ecologists:{name:'Учёные',color:'#d6c87c'},mercs:{name:'Наёмники',color:'#87949e'},mutants:{name:'Мутанты',color:'#a18467'},monolith:{name:'Монолит',color:'#b19c91'}};
  const enemyTypes={bandit:{name:'Бандит',visual:'bandit',description:'Вооружённый мародёр ищет лёгкую добычу.',hp:54,damage:11,accuracy:.58,armor:.04,weapon:'pm',loot:['ammo918','valuables','parts'],faction:'bandits',xp:18},rookie:{name:'Озлобленный новичок',visual:'stalker',description:'Испуганный сталкер действует резко и неуверенно.',hp:42,damage:8,accuracy:.55,armor:0,weapon:'knife',loot:['bread','ammo918'],faction:'loners',xp:12},merc:{name:'Наёмник',visual:'merc',description:'Подготовленный боец в тяжёлом снаряжении.',hp:88,damage:16,accuracy:.7,armor:.2,weapon:'aksu',loot:['ammo545','medkit','parts'],faction:'mercs',xp:36},dog:{name:'Слепой пёс',visual:'dog',description:'Мутант быстрый, но уязвимый.',hp:34,damage:10,accuracy:.64,armor:0,weapon:'knife',loot:['meatchunk'],faction:'mutants',xp:10},boar:{name:'Кабан',visual:'boar',description:'Тяжёлый мутант несётся напролом.',hp:78,damage:17,accuracy:.62,armor:.08,weapon:'knife',loot:['meatchunk','canned'],faction:'mutants',xp:22},bloodsucker:{name:'Кровосос',visual:'bloodsucker',description:'Невидимый охотник сближается из тумана.',hp:105,damage:20,accuracy:.72,armor:.12,weapon:'knife',loot:['flash','meatchunk'],faction:'mutants',xp:44},controller:{name:'Контролёр',visual:'controller',description:'Пси-излучение сбивает концентрацию.',hp:125,damage:23,accuracy:.76,armor:.16,weapon:'knife',loot:['jellyfish','electronics'],faction:'mutants',xp:65},monolith:{name:'Монолитовец',visual:'monolith',description:'Боец фанатичной группировки держит позицию.',hp:118,damage:21,accuracy:.72,armor:.3,weapon:'ak',loot:['ammo762','armySuit','valuables'],faction:'monolith',xp:55},pseudogiant:{name:'Псевдогигант',visual:'pseudogiant',description:'Огромный мутант медленно готовит сокрушительный удар.',hp:175,damage:29,accuracy:.55,armor:.28,weapon:'knife',loot:['meatchunk','valuables'],faction:'mutants',xp:82},snork:{name:'Снорк',visual:'snork',description:'Прыгает из укрытия, почти не давая прицелиться.',hp:67,damage:15,accuracy:.72,armor:.06,weapon:'knife',loot:['meatchunk','flash'],faction:'mutants',xp:29},duty:{name:'Боец Долга',visual:'duty',description:'Опытный патрульный в бронежилете.',hp:82,damage:15,accuracy:.68,armor:.2,weapon:'ak',loot:['ammo762','bandage'],faction:'duty',xp:32}};
  Object.assign(people,{makar:{name:'Макар «Ржавый»',role:'сталкер',faction:'loners',greeting:'В старом депо я оставил отметку. Проверь, пока бандиты не нашли.'},vera:{name:'Вера Соколова',role:'эколог',faction:'ecologists',greeting:'Нужны полевые образцы, но сначала измерь фон на месте.'},hunter:{name:'Охотник Гром',role:'сталкер',faction:'duty',greeting:'Следы у леса свежие. Не ходи один.'},radio:{name:'Радист Илья',role:'радист',faction:'loners',greeting:'На частоте снова кто-то шепчет координаты.'}});
  locations.garbage.npcs.push('makar');locations.yantar.npcs.push('vera');locations.redforest.npcs.push('hunter');locations.warehouses.npcs.push('radio');
  Object.assign(people,{mara:{name:'Мара Воронова',role:'медик',faction:'loners',greeting:'Повязки кончаются. Сначала покажи, что принёс.'},sergei:{name:'Семён «Седой»',role:'ветеран',faction:'duty',greeting:'Не спеши на север. Сначала проверь запас патронов.'},mira:{name:'Мира Лис',role:'исследователь',faction:'ecologists',greeting:'Я собираю образцы, но не прошу лезть в поле без прибора.'}});
  locations.cordon.npcs.push('mara');locations.garbage.npcs.push('sergei');locations.yantar.npcs.push('mira');
  Object.assign(enemyTypes,{alphaBoar:{...enemyTypes.boar,name:'Матёрый кабан',visual:'alphaBoar',description:'Старый мутант покрыт шрамами и не боится выстрелов.',hp:112,damage:22,accuracy:.67,armor:.16,xp:42,loot:['meatchunk','canned','stoneflower']},damagedBloodsucker:{...enemyTypes.bloodsucker,name:'Искажённый кровосос',visual:'damagedBloodsucker',description:'Повреждённая тварь движется рывками, но бьёт яростно.',hp:91,damage:24,accuracy:.68,armor:.08,xp:49,loot:['flash','meatchunk','electronics']},anomalousDog:{...enemyTypes.dog,name:'Аномальный псевдопёс',visual:'anomalousDog',description:'Шерсть мерцает от статического разряда. Удары быстрые и непредсказуемые.',hp:48,damage:14,accuracy:.72,armor:.04,xp:20,loot:['meatchunk','spark']}});
  const quests=[
    {id:'first_road',title:'Первый маршрут',text:'Дойди до Свалки, затем вернись на Кордон.',type:'route',target:'garbage',returnTo:'cordon',reward:450,rep:'loners',repGain:8,giver:'sidorovich'},
    {id:'parts_run',title:'Детали для Кардана',text:'Найди 3 набора деталей и доставь их технику.',type:'deliver',item:'parts',count:3,reward:600,rep:'loners',repGain:6,giver:'technician'},
    {id:'field_notes',title:'Полевые заметки',text:'Исследуй Янтарь и принеси учёным документы.',type:'deliver',item:'documents',count:1,reward:900,rep:'ecologists',repGain:12,giver:'ecologist'},
    {id:'mutant_cull',title:'Тихий тракт',text:'Одолей двух мутантов на болотах или в Тёмной долине.',type:'kill',target:'mutants',count:2,reward:800,rep:'duty',repGain:10,giver:'duty'},
    {id:'bandit_problem',title:'Долг за проход',text:'Победи двух бандитов или наёмников.',type:'kill',target:'hostiles',count:2,reward:750,rep:'loners',repGain:7,giver:'sidorovich'},
    {id:'artifact_sample',title:'Образец поля',text:'Найди любой артефакт и доставь учёным.',type:'deliverType',itemType:'artifact',count:1,reward:700,rep:'ecologists',repGain:8,giver:'ecologist'},
    {id:'scout_pripyat',title:'Городская разведка',text:'Доберись до Припяти и вернись на Свалку.',type:'route',target:'pripyat',returnTo:'garbage',reward:1600,rep:'loners',repGain:12,giver:'bar'},
    {id:'station',title:'Последний рубеж',text:'Открой путь к ЧАЭС и достигни Саркофага.',type:'visit',target:'chNpp',reward:3000,rep:'ecologists',repGain:15,giver:'ecologist'},
    {id:'depot_marks',title:'Метки у депо',text:'Осмотри Свалку трижды и вернись к Макару.',type:'explore',target:'garbage',count:3,reward:520,rep:'loners',repGain:5,giver:'makar'},
    {id:'field_samples',title:'Полевые образцы',text:'Найди следы аномалии в Янтаре и вернись к Вере.',type:'explore',target:'yantar',count:2,reward:850,rep:'ecologists',repGain:9,giver:'vera'},
    {id:'forest_hunt',title:'След в Рыжем лесу',text:'Одолей двух мутантов и доложи Грому.',type:'kill',target:'mutants',count:2,reward:1100,rep:'duty',repGain:8,giver:'hunter'},
    {id:'radio_parts',title:'Тихая частота',text:'Принеси радисту два набора деталей.',type:'deliver',item:'parts',count:2,reward:680,rep:'loners',repGain:5,giver:'radio'}
  ];
  quests.push({id:'mara_bandages',title:'Перевязочный запас',text:'Принеси Маре аптечку для дозорных.',type:'deliver',item:'medkit',count:1,reward:320,rep:'loners',repGain:4,giver:'mara'},{id:'grey_parts',title:'Детали для укрытия',text:'Семён ждёт две связки деталей со Свалки.',type:'deliver',item:'parts',count:2,reward:560,rep:'duty',repGain:5,giver:'sergei'},{id:'mira_sample',title:'Необычный образец',text:'Передай Мире любой артефакт для анализа.',type:'deliverType',itemType:'artifact',count:1,reward:780,rep:'ecologists',repGain:7,giver:'mira'});
  const eventSeeds=[
    {category:'Тайники',kind:'travel',minDanger:1,lines:['У ржавого кузова торчит край матерчатого рюкзака.','Под бетонной плитой видна металлическая защёлка.','В высокой траве мерцает стекло аптечной банки.','Старая путевая будка приоткрыта, внутри что-то блеснуло.','На обочине лежит промокшая сумка с чужой нашивкой.'],choices:[{label:'Осмотреть осторожно',effects:{lootRoll:true,stamina:-4}},{label:'Проверить дозиметром',effects:{radiation:-2,lootRoll:true}},{label:'Не рисковать',effects:{stamina:3}}]},
    {category:'Аномалии',kind:'both',minDanger:2,lines:['Дозиметр зачастил у невидимой границы поля.','Воздух впереди дрожит, а галька медленно поднимается.','На земле мерцают следы недавнего выброса.','Сухие листья вращаются в воронке без ветра.','Между деревьями тихо звенит металл.'],choices:[{label:'Обойти поле',effects:{stamina:-5,time:1}},{label:'Бросить болт и пройти',effects:{radiation:8,lootRoll:true,stamina:-2}},{label:'Поискать артефакт',effects:{radiation:15,artifactRoll:true}}]},
    {category:'Сталкеры',kind:'travel',minDanger:1,lines:['Из придорожной канавы поднимает руку усталый сталкер.','Одинокий путник просит поделиться водой.','У костра незнакомец предлагает обмен.','Раненый разведчик знает короткий путь.','Сталкер с потёртой нашивкой ищет попутчика.'],choices:[{label:'Помочь припасами',effects:{itemCost:{water:1},rep:{loners:4},questRoll:true}},{label:'Поговорить и разойтись',effects:{rep:{loners:2},stamina:3}},{label:'Пройти мимо',effects:{}}]},
    {category:'Бандиты',kind:'travel',minDanger:2,lines:['Трое людей перекрыли дорогу и требуют «плату за воздух».','Из-за остова машины выходят вооружённые бандиты.','На мосту тебя ждёт засада с самодельным шлагбаумом.','Бандитский дозор заметил рюкзак и зовёт старшего.','Кто-то передёрнул затвор в высокой траве.'],choices:[{label:'Отдать 80 ₽',effects:{money:-80,rep:{bandits:3}}},{label:'Попробовать договориться',effects:{talkRoll:true,rep:{bandits:2}}},{label:'Сражаться',combat:'bandit'},{label:'Рвануть в обход',effects:{fleeRoll:true,health:-4,stamina:-12}}]},
    {category:'Мутанты',kind:'both',minDanger:2,lines:['В кустах хрустнула ветка, слишком тяжело для человека.','Стая слепых псов режет путь через просеку.','Низкое рычание доносится из бетонной трубы.','Из камышей несётся кабан с окровавленными боками.','В темноте мелькнул высокий силуэт.'],choices:[{label:'Подготовиться и атаковать',combat:'autoMutant'},{label:'Обойти, потеряв время',effects:{stamina:-10,time:1}},{label:'Отступить',effects:{fleeRoll:true,stamina:-8}}]},
    {category:'Находки',kind:'explore',minDanger:1,lines:['Под обломками найден аккуратно завёрнутый свёрток.','В брошенном вагончике остались банки и патроны.','Среди хлама обнаружилась коробка с инструментами.','Чья-то записная книжка пережила выброс.','В пустой будке сохранились чистая вода и консервы.'],choices:[{label:'Забрать находку',effects:{lootRoll:true,questRoll:true}},{label:'Сначала осмотреть следы',effects:{detectRoll:true,lootRoll:true}},{label:'Оставить на месте',effects:{}}]},
    {category:'Погода и выбросы',kind:'travel',minDanger:2,lines:['Небо темнеет; по радио шипит предупреждение о выбросе.','Гроза гонит тебя к бетонному укрытию.','Пепельный ветер сбивает дыхание на открытом участке.','Вдали вспыхивает горизонт, птицы резко замолкают.','Радиоактивный дождь застал в низине.'],choices:[{label:'Искать укрытие',effects:{time:1,stamina:-4,radiation:-3}},{label:'Переждать под накидкой',effects:{health:-3,radiation:5}},{label:'Продолжить путь',effects:{radiation:12,stamina:-9,time:1}}]},
    {category:'Торговля и услуги',kind:'explore',minDanger:1,lines:['Полевой торговец раскрыл ящик с остатками снаряжения.','Техник готов обменять инструмент на полезные детали.','У костра предлагают выгодную сделку с патронами.','Сталкер продаёт карту местных аномалий.','В полевом лазарете остались лекарства по себестоимости.'],choices:[{label:'Купить припасы · 60 ₽',effects:{money:-60,lootRoll:true}},{label:'Обменять детали',effects:{tradeRoll:true}},{label:'Отказаться',effects:{}}]},
    {category:'Сюжетные сигналы',kind:'both',minDanger:1,lines:['Приёмник поймал обрывок координат: «...старый тоннель...».','На частоте одиночек передают просьбу о помощи.','На стене свежим мелом нарисован знак безопасного пути.','В документах упоминается лабораторный сектор на севере.','Кто-то называет по радио твою фамилию и резко замолкает.'],choices:[{label:'Записать координаты',effects:{discoverRoll:true,questRoll:true,rep:{ecologists:1}}},{label:'Ответить по рации',effects:{rep:{loners:2},lootRoll:true}},{label:'Сменить частоту',effects:{stamina:2}}]},
    {category:'Лагеря и отдых',kind:'explore',minDanger:1,lines:['В небольшой землянке тлеет печь и никого не видно.','У костра можно согреться, но припасы придётся оплатить.','Старый навес защищает от ветра и радиационного дождя.','В палатке оставили чистую ткань и флягу.','Сталкеры поделились слухами о безопасной тропе.'],choices:[{label:'Отдохнуть · 40 ₽',effects:{money:-40,health:8,stamina:30,hunger:6,thirst:5}},{label:'Спросить новости',effects:{rep:{loners:2},discoverRoll:true,newsRoll:true}},{label:'Идти дальше',effects:{}}]},
    {category:'Риски и выбор',kind:'both',minDanger:1,lines:['На дороге лежит брошенный военный планшет с зашифрованной картой.','В пыльной комнате за дверью тихо капает вода.','Чужой рюкзак привязан к тонкой проволоке.','В разбитой лаборатории мигает аварийный терминал.','За стеной кто-то зовёт на помощь, но голос звучит неестественно.'],choices:[{label:'Рискнуть и проверить',effects:{riskRoll:true,lootRoll:true}},{label:'Сначала оценить опасность',effects:{detectRoll:true,stamina:-3}},{label:'Отойти',effects:{}}]}
  ];
  const events=[];
  eventSeeds.forEach((seed,si)=>seed.lines.forEach((text,vi)=>{
    if(text.includes('зовёт на помощь')){events.push({id:'voice_help_signal',category:'Сюжетный сигнал · голос о помощи',kind:'both',minDanger:1,rarity:'uncommon',text,stages:[
      {id:'listen',text:'Голос повторяет просьбу о помощи. Между словами слышны два коротких щелчка — возможно, это рация или взведённая растяжка.',choices:[{label:'Осмотреть источник из укрытия',nextStage:'source',effects:{detectRoll:true},resultText:'Ты находишь следы у стены и замечаешь, что голос идёт из-за завала.'},{label:'Ответить и назвать своё имя',nextStage:'answer',effects:{rep:{loners:1}},resultText:'На другом конце замолкают, затем называют ориентир у старой вышки.'},{label:'Тихо обойти место',finish:true,resultText:'Ты уходишь, отметив опасный участок на карте.'}]},
      {id:'source',text:'За завалом обнаруживается раненый дозорный. В нескольких шагах натянута тонкая проволока.',choices:[{label:'Помочь бинтом',when:{items:{bandage:1}},effects:{itemCost:{bandage:1},health:5,rep:{loners:3},knowledge:'rescued roadside scout'},nextStage:'thanks',resultText:'Ты останавливаешь кровь и осторожно выводишь дозорного из опасного места.'},{label:'Снять растяжку и забрать рацию',nextStage:'thanks',effects:{riskRoll:true,add:{electronics:1},knowledge:'tower distress frequency'},resultText:'Растяжка оказывается старой сигнальной ловушкой. На рации сохранилась частота дозора.'},{label:'Отступить по безопасному проходу',nextStage:'thanks',effects:{stamina:-3,knowledge:'safe passage near tower'},resultText:'Ты находишь обход за бетонной плитой и запоминаешь безопасный проход.'}]},
      {id:'answer',text:'Из помех доносится: «Старая вышка… западный склон…». Затем связь обрывается.',choices:[{label:'Записать частоту и ориентир',nextStage:'thanks',effects:{knowledge:'tower distress frequency',discoverRoll:true},resultText:'Ориентир сохранён в КПК. Возможно, сигнал ещё повторится.'},{label:'Искать вышку сейчас',nextStage:'source',effects:{stamina:-5},resultText:'Ты двигаешься к вышке, сверяясь с оборванным сигналом.'},{label:'Не рисковать',finish:true,resultText:'Ты прекращаешь передачу и возвращаешься к дороге.'}]},
      {id:'thanks',text:'Источник сигнала остаётся позади, но теперь ты знаешь больше о старой вышке и безопасном проходе.',choices:[{label:'Закончить осмотр',finish:true,resultText:'Запись добавлена в КПК. Ты продолжаешь путь.'}]}
    ]});return;}
    const choices=seed.choices.map(choice=>({...choice,effects:choice.effects?{...choice.effects}:undefined}));
    if(text.includes('кабан'))choices[0]={...choices[0],combat:'boar'};else if(text.includes('Стая слепых псов'))choices[0]={...choices[0],combat:'dog'};else if(text.includes('высокий силуэт'))choices[0]={...choices[0],combat:'bloodsucker'};
    const event={id:`event_${si+1}_${vi+1}`,category:seed.category,kind:seed.kind,minDanger:seed.minDanger,text,rarity:si===9&&vi===4?'uncommon':undefined,choices};events.push(event);
  }));
  const eventChains=[
    {id:'chain_abandoned_camp',category:'Заброшенный лагерь',kind:'explore',minDanger:1,stages:[
      {id:'discover',text:'За осыпавшейся насыпью виден старый лагерь. Костёр давно погас, но следы вокруг свежие.',choices:[{label:'Осмотреть кострище',nextStage:'search',resultText:'В золе нашёлся окурок, ещё не успевший отсыреть.'},{label:'Не задерживаться',finish:true,resultText:'Ты обходишь лагерь и возвращаешься к тропе.'}]},
      {id:'search',text:'У палатки валяется рюкзак с порванным клапаном. Внутри что-то гремит.',choices:[{label:'Открыть рюкзак',nextStage:'stash',resultText:'Замок поддался. Внутри лежат патроны и банка тушёнки.'},{label:'Проверить следы вокруг',effects:{detectRoll:true},nextStage:'stash',resultText:'Следы уходят к дороге. Похоже, хозяин ушёл сам.'}]},
      {id:'stash',text:'В рюкзаке остались припасы. Их хватит кому-нибудь на один переход.',choices:[{label:'Забрать припасы',effects:{add:{ammo918:6,canned:1}},nextStage:'leave',resultText:'Ты перекладываешь патроны и консервы в свой рюкзак.'},{label:'Оставить на месте',nextStage:'leave',resultText:'Ты закрываешь клапан. Пусть находка дождётся хозяина.'}]},
      {id:'leave',text:'Лагерь остаётся позади, впереди снова слышна дорога.',choices:[{label:'Далее',finish:true,resultText:'Ты продолжаешь путь.'}]}
    ]},
    {id:'chain_wounded_stalker',category:'Раненый сталкер',kind:'travel',minDanger:1,stages:[
      {id:'meet',text:'У обочины сидит раненый сталкер. Он держит ладонь на боку и молча следит за твоими руками.',choices:[{label:'Помочь бинтом',nextStage:'thanks',effects:{itemCost:{bandage:1},rep:{loners:2},health:4},resultText:'Кровотечение удалось остановить. Сталкер медленно поднимается на ноги.'},{label:'Оставить припасы и уйти',nextStage:'thanks',effects:{add:{water:1},rep:{loners:1}},resultText:'Ты ставишь флягу рядом. Незнакомец кивает и не задаёт вопросов.'},{label:'Пройти мимо',finish:true,resultText:'Ты не останавливаешься. Позади слышен только шум ветра.'}]},
      {id:'thanks',text:'Раненый проверяет повязку и смотрит в сторону ближайшей стоянки.',choices:[{label:'Спросить о дороге',nextStage:'gift',effects:{discoverRoll:true},resultText:'Он показывает короткую тропу в обход открытого участка.'},{label:'Попрощаться',finish:true,resultText:'Сталкер остаётся у обочины. Ты продолжаешь путь.'}]},
      {id:'gift',text:'Перед уходом сталкер достаёт из внутреннего кармана аптечку.',choices:[{label:'Принять аптечку',nextStage:'leave',effects:{add:{medkit:1}},resultText:'«Мне пока нужнее бинты», — говорит он и протягивает тебе аптечку.'}]},
      {id:'leave',text:'Раненый укрылся за бетонной плитой. Тропа впереди свободна.',choices:[{label:'Далее',finish:true,resultText:'Ты снова в пути.'}]}
    ]},
    {id:'chain_suspicious_cache',category:'Подозрительный тайник',kind:'both',minDanger:2,stages:[
      {id:'discover',text:'Под ржавой плитой заметна крышка тайника. К ней тянется тонкая проволока.',choices:[{label:'Осмотреть крепление',nextStage:'risk',effects:{detectRoll:true},resultText:'Проволока уходит под плиту и теряется в грязи.'},{label:'Отойти',finish:true,resultText:'Ты оставляешь тайник в покое.'}]},
      {id:'risk',text:'Замок проржавел, но крышка поддаётся. Внутри может быть что угодно.',choices:[{label:'Открыть тайник',nextStage:'result',effects:{riskRoll:true,lootRoll:true},resultText:'Крышка с глухим скрипом отходит. Ты проверяешь содержимое и быстро закрываешь тайник.'},{label:'Не рисковать',nextStage:'result',resultText:'Ты решаешь не трогать чужую схронку.'}]},
      {id:'result',text:'Проволока осталась неподвижной. Кажется, на этот раз обошлось.',choices:[{label:'Далее',finish:true,resultText:'Ты возвращаешься на тропу.'}]}
    ]},
    {id:'chain_road_tracks',category:'Следы на дороге',kind:'travel',minDanger:2,stages:[
      {id:'tracks',text:'На грязи отпечатались свежие следы тяжёлых ботинок. Они сворачивают к разрушенному зданию.',choices:[{label:'Проследить их',nextStage:'building',resultText:'Следы ведут к пролому в стене. Внутри мерцает слабый свет.'},{label:'Обойти здание',finish:true,resultText:'Ты держишься подальше от чужого укрытия.'}]},
      {id:'building',text:'За стеной кто-то передвигает ящики. Выход перекрыт кучей кирпича.',choices:[{label:'Позвать из укрытия',nextStage:'contact',resultText:'Шорох внутри стихает. Через щель отвечает усталый голос.'},{label:'Войти с оружием',combat:'bandit',nextStage:'contact',winText:'За проломом никого не осталось. В углу мигает радиоприёмник.',fleeText:'Ты отступаешь от пролома, сохранив дистанцию.'}]},
      {id:'contact',text:'Приёмник ловит короткий сигнал с координатами старой метеостанции.',choices:[{label:'Записать частоту',nextEvent:'chain_strange_signal',effects:{rep:{loners:1}},resultText:'Частота сохранена в КПК. Сигнал снова повторяется — уже ближе.'},{label:'Продолжить дорогу',finish:true,resultText:'Ты оставляешь чужую частоту в покое.'}]}
    ]},
    {id:'chain_strange_signal',category:'Странный сигнал',kind:'both',minDanger:2,stages:[
      {id:'source',text:'Приёмник шипит на одной частоте. Между помехами слышны координаты и три коротких удара.',choices:[{label:'Найти источник',nextStage:'approach',effects:{discoverRoll:true},resultText:'Сигнал идёт из старой будки у насыпи.'},{label:'Сменить частоту',finish:true,resultText:'Помехи затихают, и дорога снова становится слышна.'}]},
      {id:'approach',text:'У будки лежит разобранная рация. Рядом — свежий след от сапога.',choices:[{label:'Осмотреть аппаратуру',nextStage:'choice',effects:{lootRoll:true},resultText:'Под корпусом нашёлся запечатанный конверт с пометкой «Янтарь».'},{label:'Ответить в эфир',nextStage:'choice',effects:{rep:{ecologists:2},questRoll:true},resultText:'В эфире отвечает неизвестный голос и передаёт краткие координаты.'}]},
      {id:'choice',text:'Частота больше не повторяется. Координаты остались в журнале КПК.',choices:[{label:'Далее',finish:true,resultText:'Ты продолжаешь путь, прислушиваясь к рации.'}]}
    ]}
  ];
  const addedEvents=[
    {id:'garbage_depot_ambush',category:'Свалка · засада',kind:'explore',locations:['garbage'],minDepth:2,minDanger:2,rarity:'uncommon',text:'За стеной старого депо слышны короткие очереди. На входе лежит брошенный рюкзак, а внутри кто-то перезаряжает оружие.',choices:[{label:'Войти через пролом',combat:'bandit',effects:{stamina:-3}},{label:'Окликнуть людей',when:{rep:{bandits:5}},effects:{rep:{bandits:2},money:35},resultText:'Бандиты узнают знак на нашивке и отпускают тебя с небольшой платой.'},{label:'Обойти депо',effects:{time:1,stamina:-6}}]},
    {id:'cordon_watchman',category:'Кордон · старый дозор',kind:'travel',locations:['cordon','checkpoint'],minDanger:1,rarity:'uncommon',text:'На вышке скрипит дверь. Старый дозорный оставил в журнале координаты безопасного брода и запись: «не ходить к трубе после заката».',choices:[{label:'Сверить координаты',effects:{discoverRoll:true,knowledge:'safe ford'},resultText:'Ты переносишь отметку в КПК и запоминаешь безопасный путь.'},{label:'Забрать журнал',effects:{add:{valuables:1},rep:{military:-1}}}]},
    {id:'swamp_fisher',category:'Болота · чужая сеть',kind:'explore',locations:['swamp'],minDanger:3,minDepth:1,rarity:'common',text:'В камышах запуталась рыбацкая сеть. Под ней дрожит вода, хотя ветра нет.',choices:[{label:'Освободить сеть',effects:{health:-4,rep:{loners:2},add:{canned:1}}},{label:'Осмотреть дно',effects:{radiation:7,artifactRoll:true}},{label:'Отступить на сухой островок',effects:{stamina:3}}]},
    {id:'yantar_signal',category:'Янтарь · измерение',kind:'explore',locations:['yantar'],minDepth:2,rarity:'rare',requiredRep:{ecologists:5},text:'Датчик у бетонной стены поймал ровный импульс. Вера отмечала похожий сигнал перед исчезновением группы наблюдателей.',choices:[{label:'Снять показания',effects:{radiation:5,rep:{ecologists:3},add:{electronics:1}},resultText:'Показания совпали с архивной кривой Веры. Учёные смогут уточнить карту поля.'},{label:'Проверить источник',combat:'snork',effects:{radiation:8}}]},
    {id:'redforest_footsteps',category:'Рыжий лес · следы',kind:'both',locations:['redforest'],minDanger:5,minDepth:1,rarity:'uncommon',text:'На рыжей хвое отпечатались следы босых ног. Они обрываются у поваленной сосны, будто человек шагнул вверх.',choices:[{label:'Идти по следу',combat:'snork',effects:{stamina:-4}},{label:'Оставить метку и вернуться',effects:{knowledge:'forest footprints',rep:{duty:1}}}]},
    {id:'night_warehouse_patrol',category:'Склады · ночной патруль',kind:'travel',locations:['warehouses'],time:'night',rarity:'rare',text:'В темноте патруль «Свободы» принимает тебя за разведчика. Фонарь режет глаза, но командир узнаёт старый пароль.',choices:[{label:'Назвать пароль',when:{rep:{freedom:8}},effects:{rep:{freedom:3},add:{bandage:1}},resultText:'Патруль опускает оружие и делится перевязочным пакетом.'},{label:'Отойти к укрытию',effects:{stamina:-5,time:1}},{label:'Сорваться с места',combat:'duty',effects:{fleeRoll:true}}]},
    {id:'darkvalley_bloodtrail',category:'Тёмная долина · кровавый след',kind:'explore',locations:['darkvalley'],minDepth:3,rarity:'uncommon',text:'Свежая кровь тянется от трубы к бетонному коллектору. Из глубины доносится тяжёлое дыхание.',choices:[{label:'Заманить зверя наружу',combat:'boar',effects:{stamina:-3}},{label:'Спуститься тихо',combat:'bloodsucker'},{label:'Запомнить путь и уйти',effects:{knowledge:'dark valley trail',time:1}}]},
    {id:'pripyat_last_broadcast',category:'Припять · последний эфир',kind:'explore',locations:['pripyat'],minDepth:2,rarity:'very_rare',text:'Из пустого громкоговорителя звучит объявление о закрытии школы. В конце записи слышен голос, называющий твоё имя.',choices:[{label:'Ответить по радио',when:{items:{electronics:1}},effects:{itemCost:{electronics:1},rep:{loners:2},knowledge:'school broadcast'},resultText:'В ответ приходит только набор координат и три коротких сигнала.'},{label:'Записать частоту',effects:{radiation:4,knowledge:'pripyat frequency'}},{label:'Выключить приёмник',effects:{stamina:2}}]},
    {id:'deep_cache_echo',category:'Тайник · гул из-под земли',kind:'explore',minDepth:8,minDanger:4,rarity:'rare',text:'Под бетонным кольцом глухо отзывается пустота. Кто-то спрятал там герметичный контейнер, но крышку удерживает ржавая цепь.',choices:[{label:'Срезать цепь',when:{items:{tools:1}},effects:{itemCost:{tools:1},artifactRoll:true}},{label:'Поднять крышку силой',effects:{health:-8,lootRoll:true,stamina:-6}},{label:'Поставить отметку',effects:{knowledge:'deep cache echo'}}]},
    {id:'secret_stalker',category:'Секретная встреча',kind:'both',minDepth:12,minDanger:5,rarity:'special',requiredRep:{loners:20},text:'За линией старых столбов сидит сталкер без нашивок. Он знает дорогу, которой нет на карте, и называет твой позывной.',choices:[{label:'Выслушать маршрут',effects:{rep:{loners:4},discoverRoll:true,knowledge:'unmarked route'},resultText:'Незнакомец рисует на клочке бумаги новый обход и тут же сжигает оригинал.'},{label:'Потребовать объяснений',combat:'merc'},{label:'Уйти молча',effects:{}}]},
    {id:'military_checkpoint_order',category:'Блокпост · приказ',kind:'travel',locations:['checkpoint'],rarity:'uncommon',text:'Сержант сверяет список пропавших патрулей и просит подтвердить слух о мутантах возле Свалки.',choices:[{label:'Передать сведения',when:{questActive:'mutant_cull'},effects:{rep:{military:3},money:90},resultText:'Сержант ставит отметку в журнале и выплачивает небольшую премию.'},{label:'Предложить помощь',effects:{rep:{military:1},knowledge:'checkpoint roster'}},{label:'Не вмешиваться',effects:{}}]},
    {id:'agroprom_locked_lab',category:'Агропром · лабораторный вход',kind:'explore',locations:['agro'],minDepth:3,rarity:'rare',text:'За сорванной дверью видны свежие следы учёных. На панели питания ещё горит один индикатор.',choices:[{label:'Подключить найденные провода',when:{items:{wires:2}},effects:{itemCost:{wires:2},add:{electronics:1},knowledge:'agroprom lab'},resultText:'Панель оживает на несколько секунд, открывая схему подземного этажа.'},{label:'Вскрыть дверь',combat:'bandit',effects:{stamina:-6}},{label:'Отметить лабораторию',effects:{discoverRoll:true}}]},
    {id:'wild_sniper_glint',category:'Дикая территория · блик',kind:'both',locations:['wild'],minDanger:4,rarity:'uncommon',text:'С насыпи блеснул прицел. Выстрела нет, но стрелок явно ждёт, когда ты выйдешь на открытое место.',choices:[{label:'Рвануть к бетонной плите',effects:{stamina:-8,health:-3}},{label:'Зайти с фланга',combat:'merc'},{label:'Показать пустые руки',when:{rep:{mercs:10}},effects:{rep:{mercs:2},time:1},resultText:'Наёмник принимает знак и отходит, не опуская винтовку.'}]},
    {id:'rare_field_calm',category:'Аномалия · тихий карман',kind:'explore',minDepth:5,minDanger:3,rarity:'very_rare',text:'Дозиметр замолкает посреди опасного поля. Пыль оседает, и в центре круга проступает тёплый свет.',choices:[{label:'Проверить центр',effects:{radiation:12,artifactRoll:true}},{label:'Снять показания издали',effects:{rep:{ecologists:2},knowledge:'quiet anomaly'}},{label:'Запомнить ориентир',effects:{}}]},
    {id:'pripyat_roof_mutant',category:'Припять · крыша',kind:'explore',locations:['pripyat'],minDepth:4,rarity:'rare',text:'С крыши торгового центра срывается кусок бетона. Следом на карниз выползает огромная тень.',choices:[{label:'Удержать позицию',combat:'pseudogiant'},{label:'Спуститься в переход',effects:{stamina:-10,time:1}},{label:'Бросить приманку',when:{items:{canned:1}},effects:{itemCost:{canned:1},stamina:4}}]},
    {id:'tower_keeper',category:'Секретная история · смотритель',kind:'explore',locations:['garbage','redforest'],minDepth:6,rarity:'special',requiredFlag:'documentsFound',text:'На вершине старой вышки загорается фонарь. Смотритель оставил на перилах конверт со схемой северных тоннелей.',choices:[{label:'Забрать схему',effects:{knowledge:'north tunnels',rep:{ecologists:2},add:{valuables:1}},resultText:'На схеме отмечен короткий, но опасный путь к северным секторам.'},{label:'Оставить конверт',effects:{}}]}
  ];
  addedEvents.push(
    {id:'rookie_missing_radio',category:'Деревня · пропавшая рация',kind:'travel',locations:['rookie'],rarity:'common',text:'Новичок Лёха услышал рацию у колодца, но боится идти туда один. На дне мерцает тусклый зелёный огонёк.',choices:[{label:'Спуститься за рацией',effects:{stamina:-5,add:{electronics:1},rep:{loners:2}}},{label:'Проверить дозиметром',effects:{radiation:2,knowledge:'rookie well'}},{label:'Посоветовать не рисковать',effects:{}}]},
    {id:'checkpoint_wounded',category:'Блокпост · раненый связной',kind:'travel',locations:['checkpoint'],minDanger:2,rarity:'uncommon',text:'Солдат в грязной шинели просит довести его до бетонного укрытия. Он сжимает карту северной дороги.',choices:[{label:'Перевязать',when:{items:{bandage:1}},effects:{itemCost:{bandage:1},rep:{military:3},knowledge:'north checkpoint route'}},{label:'Отвести под огонь',combat:'duty'},{label:'Оставить воду',when:{items:{water:1}},effects:{itemCost:{water:1},rep:{military:1}}}]},
    {id:'garbage_tagged_crate',category:'Свалка · чужой груз',kind:'explore',locations:['garbage'],minDepth:4,rarity:'uncommon',text:'На ящике свежая метка Макара. Внутри слышно тихое тиканье, а вокруг разбросаны гильзы.',choices:[{label:'Открыть с расстояния',effects:{lootRoll:true,stamina:-3}},{label:'Осмотреть метку',effects:{knowledge:'Makar crate',rep:{loners:2}}},{label:'Забрать целиком',combat:'bandit'}]},
    {id:'agro_generator',category:'Агропром · генератор',kind:'explore',locations:['agro'],minDepth:2,rarity:'common',text:'Старый генератор запускается сам по себе. Гул разносится по пустому цеху и будит что-то под полом.',choices:[{label:'Выдернуть кабель',effects:{stamina:-2,knowledge:'agroprom generator'}},{label:'Дождаться остановки',effects:{time:1,radiation:-2}},{label:'Проверить подвал',combat:'snork'}]},
    {id:'valley_captive',category:'Тёмная долина · пленник',kind:'explore',locations:['darkvalley'],minDepth:2,rarity:'rare',text:'За железной дверью кто-то стучит три раза, затем дважды. На засове вырезан знак бандитской группировки.',choices:[{label:'Договориться за 80 ₽',when:{money:80},effects:{money:-80,rep:{loners:3},add:{valuables:1}}},{label:'Взломать засов',combat:'bandit',effects:{health:-3}},{label:'Проверить соседний ход',when:{items:{tools:1}},effects:{knowledge:'valley captive route',radiation:2}}]},
    {id:'swamp_will_o_wisp',category:'Болота · огонёк',kind:'explore',locations:['swamp'],time:'night',rarity:'rare',text:'Над топью плывёт тёплый огонёк. Болты, брошенные в его сторону, меняют направление в воздухе.',choices:[{label:'Идти за светом',effects:{radiation:9,artifactRoll:true}},{label:'Обойти по сухим корням',effects:{stamina:-5,knowledge:'swamp night path'}},{label:'Погасить фонарь',effects:{}}]},
    {id:'yantar_rain',category:'Янтарь · пепельный дождь',kind:'travel',locations:['yantar'],rarity:'uncommon',text:'На озеро падает серый дождь, оставляя на поверхности круги. Станция измерений совсем рядом.',choices:[{label:'Спрятаться на станции',when:{rep:{ecologists:0}},effects:{time:1,rep:{ecologists:1},radiation:-3}},{label:'Собрать осадок',effects:{radiation:6,add:{electronics:1}}},{label:'Ускорить шаг',effects:{stamina:-7}}]},
    {id:'wild_broken_convoy',category:'Дикая территория · конвой',kind:'explore',locations:['wild'],minDepth:2,rarity:'uncommon',text:'Две машины стоят нос к носу. На стекле остались следы изнутри, а в рации повторяется сигнал бедствия.',choices:[{label:'Проверить кабину',effects:{lootRoll:true,health:-4}},{label:'Засечь сигнал',effects:{knowledge:'wild convoy frequency',electronicsRoll:true}},{label:'Уйти в овраг',combat:'merc'}]},
    {id:'warehouse_old_friend',category:'Склады · знакомый позывной',kind:'travel',locations:['warehouses'],rarity:'uncommon',requiredRep:{freedom:4},text:'В эфире отвечает старый позывной. Человек просит оставить у третьего ангара упаковку патронов.',choices:[{label:'Оставить патроны',when:{items:{ammo545:6}},effects:{itemCost:{ammo545:6},rep:{freedom:4},money:120}},{label:'Попросить координаты',effects:{knowledge:'third warehouse',discoverRoll:true}},{label:'Отключить рацию',effects:{}}]},
    {id:'redforest_tree_mark',category:'Рыжий лес · насечка',kind:'explore',locations:['redforest'],minDepth:3,rarity:'common',text:'На сосне свежая насечка, направленная против ветра. Следующий знак виден только через оптику.',choices:[{label:'Продолжить по знакам',effects:{stamina:-4,knowledge:'red forest marks'}},{label:'Забраться на склон',effects:{radiation:4,discoverRoll:true}},{label:'Снять насечку на фото',effects:{rep:{loners:1}}}]},
    {id:'pripyat_classroom',category:'Припять · класс',kind:'explore',locations:['pripyat'],minDepth:1,rarity:'uncommon',text:'На доске в школьном классе мелом написан сегодняшний час. Под партой лежит целая коробка довоенных батареек.',choices:[{label:'Забрать батарейки',effects:{add:{electronics:1},knowledge:'school classroom'}},{label:'Проверить запись',effects:{radiation:3,rep:{ecologists:1}}},{label:'Не задерживаться',effects:{}}]},
    {id:'chNpp_monolith_signal',category:'Саркофаг · ответ сигнала',kind:'explore',locations:['chNpp'],minDepth:1,rarity:'special',requiredFlag:'stationOpen',text:'Под гулом станции приборы ловят знакомую частоту. Кто-то передаёт точные показания твоего дозиметра.',choices:[{label:'Открыть канал',combat:'monolith',effects:{radiation:7}},{label:'Записать импульс',effects:{knowledge:'sarcophagus signal',rep:{ecologists:3}}},{label:'Выключить прибор',effects:{stamina:-4}}]},
    {id:'cordon_trader_debt',category:'Кордон · старый долг',kind:'travel',locations:['cordon'],rarity:'uncommon',text:'У КПП тебя догоняет посыльный Сидоровича: один из новичков взял припасы в долг и пропал у железной дороги.',choices:[{label:'Внести 60 ₽',when:{money:60},effects:{money:-60,rep:{loners:3},knowledge:'rookie debt'}},{label:'Поискать должника',effects:{discoverRoll:true,stamina:-3}},{label:'Оставить разбираться торговцу',effects:{}}]},
    {id:'mutant_den',category:'Мутанты · логово',kind:'explore',minDepth:5,minDanger:4,rarity:'rare',text:'У входа в бетонный водосток лежат кости и обрывки снаряжения. Изнутри доносится скрежет когтей.',choices:[{label:'Заманить зверя наружу',combat:'pseudogiant'},{label:'Бросить мясо и отступить',when:{items:{meatchunk:1}},effects:{itemCost:{meatchunk:1},stamina:4}},{label:'Отметить опасный тоннель',effects:{knowledge:'mutant den'}}]},
    {id:'loner_scout',category:'Сталкер · разведчик',kind:'both',minDanger:3,rarity:'uncommon',text:'Разведчик показывает пустую карту и утверждает, что вышел из сектора, которого здесь нет. Он просит не записывать его настоящее имя.',choices:[{label:'Обменяться маршрутами',effects:{discoverRoll:true,rep:{loners:2},knowledge:'unmapped sector'}},{label:'Проверить его рассказ',when:{rep:{loners:12}},effects:{add:{valuables:1},knowledge:'scout account'}},{label:'Попрощаться',effects:{}}]}
  );
  addedEvents.push(
    {id:'rare_alpha_boar',category:'Редкая угроза · матёрый кабан',kind:'explore',locations:['garbage','wild'],minDanger:2,minDepth:5,rarity:'very_rare',text:'Тяжёлые шаги сотрясают груду металла. Из тумана выходит кабан, чья шкура покрыта старыми осколками.',choices:[{label:'Удержать позицию',combat:'alphaBoar'},{label:'Уйти по насыпи',effects:{stamina:-9,knowledge:'alpha boar track'}},{label:'Отвлечь тушёнкой',when:{items:{canned:1}},effects:{itemCost:{canned:1},stamina:3}}]},
    {id:'rare_damaged_bloodsucker',category:'Редкая угроза · искажённый кровосос',kind:'both',minDanger:5,minDepth:7,rarity:'special',text:'На секунду гаснет КПК. В красном шуме проступает силуэт, двигающийся рывками.',choices:[{label:'Включить фонарь и стрелять',combat:'damagedBloodsucker'},{label:'Затаиться за бетонной плитой',effects:{stamina:-8,health:-3}},{label:'Бросить болт в сторону',effects:{time:1,radiation:2}}]},
    {id:'rare_anomalous_dog',category:'Редкая угроза · псевдопёс',kind:'explore',locations:['swamp','redforest'],minDanger:3,minDepth:4,rarity:'rare',text:'Собачий вой отражается сразу с трёх сторон. Между деревьями вспыхивают голубые искры.',choices:[{label:'Выстрелить по силуэту',combat:'anomalousDog'},{label:'Переждать в укрытии',effects:{stamina:-4,time:1}},{label:'Отметить место на карте',effects:{knowledge:'anomalous dog territory'}}]},
    {id:'radio_silent_call',category:'Уникальный сигнал · тихий канал',kind:'both',minDanger:2,minDepth:10,rarity:'special',text:'Радиоприёмник сам переключается на частоту без помех. Незнакомка называет тебя по позывному и просит оставить ответ у старой вышки.',stages:[{id:'call',text:'Передача повторяется: «Если ты слышишь, не отвечай вслух. Оставь знак на вышке».',choices:[{label:'Записать частоту',nextStage:'mark',effects:{knowledge:'silent radio caller',startQuest:'radio_parts'},resultText:'КПК запоминает частоту и примерное направление сигнала.'},{label:'Ответить коротким импульсом',nextStage:'mark',effects:{radiation:3,rep:{loners:2}},resultText:'В динамике слышится короткий щелчок — собеседник принял ответ.'},{label:'Сбросить вызов',finish:true,resultText:'Канал замолкает. Ты сохраняешь батарею и идёшь дальше.'}]},{id:'mark',text:'На опоре старой вышки кто-то оставил свежую отметку: три черты и круг.',choices:[{label:'Оставить ответный знак',nextStage:'end',effects:{knowledge:'tower answer mark',add:{valuables:1}},resultText:'В щели под табличкой спрятаны довоенные жетоны.'},{label:'Осмотреть основание',nextStage:'end',effects:{detectRoll:true,artifactRoll:true},resultText:'У основания обнаруживается слабый сигнал детектора.'},{label:'Уйти, не оставляя следов',nextStage:'end',resultText:'Ты запоминаешь знак, но не отвечаешь.'}]},{id:'end',text:'Частота снова молчит. В журнале осталась запись о неизвестном собеседнике.',choices:[{label:'Закрыть заметку',finish:true,resultText:'Ты возвращаешься к исследованию.'}]}]}
  );
  events.push(...addedEvents,...eventChains);
  window.ZoneRPGWorld={locations,people,factions,enemyTypes,quests,events,eventSeeds,eventChains};
})();
