
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {runtime,eventSave,select,qty}=require('./runtime.cjs');let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
const terminal=s=>s.event?.flow.phase==='result'&&!s.event.flow.pending?.nextStage&&!s.event.flow.pending?.nextEvent;
function settle(r){for(let i=0;i<60;i++){const s=r.E.getState();assert.notEqual(s.mode,'dead');if(terminal(s))return s;if(s.combat){const old=r.ctx.Math.random;r.ctx.Math.random=()=>0;r.E.action('flee');r.ctx.Math.random=old;continue;}assert.ok(s.event);const safe=s.event.choices.find(c=>c.action==='advance')||s.event.choices.find(c=>c.finish&&!c.combat&&!c.effects?.itemCost&&(c.effects?.money??0)>=0)||s.event.choices.find(c=>!c.combat&&!c.effects?.itemCost)||s.event.choices[0];select(r,safe.label);}throw Error('Unfinished encounter');}
function use(r,id){const i=r.E.getState().inventory.findIndex(x=>x.id===id);assert.ok(i>=0,id);r.E.action('use',i);}
test('Counts, references, item icons, faction symbols and new enemy sprites',()=>{const r=runtime();assert.equal(Object.keys(r.W.locations).length,29);assert.ok(r.W.events.length>=250);assert.equal(Object.values(r.W.people).filter(p=>!p.personalStory).length,44);assert.equal(r.W.quests.filter(q=>!q.personalStory).length,55);assert.equal(Object.keys(r.W.enemyTypes).filter(id=>id!=='storyScarBoar').length,30);assert.equal(Object.values(r.I.items).filter(x=>x.type==='artifact').length,24);assert.equal(new Set(r.W.events.map(x=>x.id)).size,r.W.events.length);for(const e of r.W.events){for(const l of e.locations||[])assert.ok(r.W.locations[l],e.id);for(const stage of e.stages)for(const c of stage.choices){if(c.nextStage)assert.ok(e.stages.some(x=>x.id===c.nextStage),e.id);if(c.nextEvent)assert.ok(r.W.events.some(x=>x.id===c.nextEvent));if(c.combat&&c.combat!=='autoMutant')assert.ok(r.W.enemyTypes[c.enemyId||c.combat]);for(const id of Object.keys({...c.effects?.add,...c.effects?.itemCost,...c.when?.items}))assert.ok(r.I.items[id],id);}}
 for(const [id,it]of Object.entries(r.I.items)){assert.ok(it.type&&Number.isFinite(it.weight)&&Number.isFinite(it.price),id);assert.ok(fs.existsSync(path.join(__dirname,'../assets/sprites/item-icons/'+it.icon+'.svg')),id+': '+it.icon);}
 for(const [id,f]of Object.entries(r.W.factions)){assert.ok(fs.existsSync(path.join(__dirname,'../assets/sprites/faction-'+id+'.svg')));if(f.base)assert.ok(r.W.locations[f.base]);for(const enemy of f.enemies||[])assert.ok(r.W.factions[enemy]);}
 for(const [id,e]of Object.entries(r.W.enemyTypes)){assert.ok(fs.existsSync(path.join(__dirname,'../assets/sprites/enemy-'+e.visual+'.svg')),id);for(const item of e.loot)assert.ok(r.I.items[item]);}
 for(const q of r.W.quests){if(q.requiredCompletedQuest)assert.ok(r.W.quests.some(x=>x.id===q.requiredCompletedQuest));if(q.requiredFaction)assert.ok(r.W.factions[q.requiredFaction].joinable);if(q.type==='research')assert.ok(r.W.events.find(x=>x.id==='v7_research_'+q.giver));}
});
test('50 successive encounters, prepared resources, no idle emission, bounded depth and save/load',()=>{const r=runtime(),s=r.S.fresh();s.player.location='garbage';s.inventory.push({id:'energy',qty:35},{id:'water',qty:6},{id:'ration7',qty:6},{id:'antirad',qty:8});r.load(s);let seed=92731;r.ctx.Math.random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};r.E.action('explore');const ids=[],renders=[];r.E.onChange(()=>renders.push(r.E.getState()));
 for(let n=1;n<=50;n++){const a=settle(r);ids.push(a.event.id);assert.equal(a.expedition.active,true);assert.equal(a.expedition.originLocationId,'garbage');assert.equal(a.expedition.depth,n);if(n===25){r.E.action('save');r.E.action('load');assert.equal(r.E.getState().expedition.depth,25);}
 if(n<50){if(r.E.getState().player.stamina<40)use(r,'energy');if(r.E.getState().player.thirst>70)use(r,'water');if(r.E.getState().player.hunger>70)use(r,'ration7');if(r.E.getState().player.radiation>55)use(r,'antirad');r.E.action('event',r.E.getState().event.choices.findIndex(x=>x.action==='advance'));assert.ok(r.E.getState().event);}
 }
 assert.ok(new Set(ids).size>=20,'encounter variety');assert.ok(renders.every(x=>x.event&&x.mode!=='play'));assert.equal(r.E.getState().expeditionCost,15);assert.equal(r.ctx.window.ZoneRPGExpedition.tier(50000),3);assert.ok(r.E.getState().expedition.summary.hours>=50);r.E.action('save');const raw=JSON.parse(r.store.get(r.S.KEY));assert.equal(raw.version,r.S.VERSION);assert.equal(raw.event.text,undefined);assert.equal(raw.event.choices,undefined);const inventory=JSON.stringify(r.E.getState().inventory);r.E.action('load');assert.equal(JSON.stringify(r.E.getState().inventory),inventory);r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'garbage');assert.equal(r.E.getState().expedition.active,false);assert.equal(r.E.getState().event,null);console.log('  '+new Set(ids).size+' distinct encounters in 50');
});
test('Every sector returns to its own origin, including v8 migration and temporary encounter coordinates',()=>{const r=runtime();for(const id of Object.keys(r.W.locations)){const s=eventSave(r,'event_6_3');s.version=8;delete s.expedition;s.player.location=id;s.explorationOriginLocationId=id;s.explorationSessionDepth=2;r.load(s);select(r,'Забрать находку');r.E.action('save');r.E.action('load');assert.equal(r.E.getState().expedition.originLocationId,id);r.E.action('eventReturn');assert.equal(r.E.getState().player.location,id);assert.equal(r.E.getState().expedition.active,false);}const s=eventSave(r,'event_6_3');s.player.location='quarry';s.explorationOriginLocationId='darkvalley';r.load(s);select(r,'Забрать находку');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'darkvalley');});
test('Low stamina leaves Continue disabled but Return free; stages use a distinct advance label',()=>{const r=runtime(),s=eventSave(r,'v7_quarry_survey','approach');s.player.location='quarry';s.explorationOriginLocationId='quarry';r.load(s);select(r,'Найти пост');assert.equal(r.E.getState().event.choices[0].label,'Следующий этап');assert.ok(!r.root.innerHTML.includes('event-return'));select(r,'Следующий этап');select(r,'Снять показания');const a=r.E.getState();a.player.stamina=0;r.load(a);assert.match(r.root.innerHTML,/Нет сил/);r.E.action('event',0);assert.equal(r.E.getState().event.flow.phase,'result');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'quarry');assert.equal(r.E.getState().player.stamina,0);});
test('Seven joinable factions validate membership, enemies, discount, refusal and persistence',()=>{const r=runtime();for(const [id,f]of Object.entries(r.W.factions).filter(([id,f])=>f.joinable)){const s=r.S.fresh();s.player.location=f.base;s.player.rank=f.minRank;s.reputation[id]=f.minRep;r.load(s);const before=r.E.getState().shop?.stock[0].price;r.E.action('joinFaction',id);assert.equal(r.E.getState().factionMembership,id);for(const enemy of f.enemies)assert.equal(r.E.getState().reputation[enemy],s.reputation[enemy]-15);const after=r.E.getState().shop?.stock[0].price;if(before)assert.ok(after<before);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().factionMembership,id);r.E.action('leaveFaction');assert.equal(r.E.getState().factionMembership,null);}
 const s=r.S.fresh();s.reputation.loners=-50;r.load(s);assert.equal(r.E.getState().shop,null);r.E.action('joinFaction','loners');assert.equal(r.E.getState().factionMembership,null);
});
test('Directed research is deterministic, persistent and rewarded exactly once',()=>{const r=runtime(),s=r.S.fresh();s.player.location='researchCamp';r.load(s);r.E.action('acceptQuest','v7_job_prof7');r.E.action('researchQuest','v7_job_prof7');select(r,'Разметить участок');select(r,'Следующий этап');select(r,'Снять показания');r.E.action('save');r.E.action('load');select(r,'Следующий этап');select(r,'Составить отчёт');select(r,'Продолжить');assert.ok(r.E.getState().quests.active.find(x=>x.id==='v7_job_prof7').ready);const money=r.E.getState().player.money;r.E.action('turnIn','v7_job_prof7');assert.ok(r.E.getState().player.money>money);const earned=r.E.getState().player.money;r.E.action('turnIn','v7_job_prof7');assert.equal(r.E.getState().player.money,earned);});
test('Faction chains gate previous completion and offer the next real contract',()=>{const r=runtime(),s=r.S.fresh();s.player.location='dutyFort';s.player.rank=2;s.reputation.duty=20;r.load(s);assert.ok(!r.E.getState().quests.available.some(x=>x.requiredFaction));r.E.action('joinFaction','duty');assert.ok(r.E.getState().quests.available.some(x=>x.id==='v7_duty_line_1'));assert.ok(!r.E.getState().quests.available.some(x=>x.id==='v7_duty_line_2'));r.E.action('acceptQuest','v7_duty_line_1');r.ctx.Math.random=()=>.99;for(let n=0;n<2;n++){r.E.action('explore');settle(r);r.E.action('eventReturn');}r.E.action('turnIn','v7_duty_line_1');assert.ok(r.E.getState().quests.available.some(x=>x.id==='v7_duty_line_2'));r.E.action('acceptQuest','v7_duty_line_2');assert.ok(r.E.getState().quests.active.some(x=>x.id==='v7_duty_line_2'));});
test('Unique mirror reward stays single across save and repeated clicks; chain retains origin',()=>{const r=runtime(),s=eventSave(r,'v7_mirror_chain','signal');s.player.location='mirrorLake';s.explorationOriginLocationId='mirrorLake';s.inventory.push({id:'probe7',qty:1});r.load(s);for(const label of ['Проследить за фигурой','Следующий этап','Сверить журнал','Следующий этап','Проверить болтами','Следующий этап','Забрать Зеркальное семя'])select(r,label);assert.equal(qty(r.E.getState(),'mirrorSeed'),1);r.E.action('save');r.E.action('load');assert.equal(qty(r.E.getState(),'mirrorSeed'),1);r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'mirrorLake');});
test('Human, mutant and elite scaled combat maintain IDs/stats across compact save, defeat grants loot once',()=>{const r=runtime();for(const type of ['banditScout','quarryDog','mirrorStalker']){const event=r.W.events.find(x=>x.id==='v7_enemy_'+type),s=eventSave(r,event.id,'fight');s.player.location=event.locations[0];s.explorationOriginLocationId=s.player.location;s.explorationSessionDepth=10;s.baseStats.maxHealth=300;s.player.health=300;s.inventory.push({id:'ammo918',qty:200});r.load(s);select(r,'Вступить в бой');const c=r.E.getState().combat;assert.equal(c.type,type);assert.equal(c.enemy.visual,type);assert.ok(c.enemy.maxHp>r.W.enemyTypes[type].hp);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().combat.enemy.damage,c.enemy.damage);assert.equal(r.E.getState().combat.enemy.maxHp,c.enemy.maxHp);r.ctx.Math.random=()=>0;for(let n=0;n<100&&r.E.getState().combat;n++){if(!r.E.getState().activeWeapon.magazine)r.E.action('reload');else r.E.action('attack');}assert.equal(r.E.getState().combat,null);assert.notEqual(r.E.getState().mode,'dead');const inventory=JSON.stringify(r.E.getState().inventory),money=r.E.getState().player.money;r.E.action('attack');assert.equal(r.E.getState().player.money,money);assert.equal(JSON.stringify(r.E.getState().inventory),inventory);}});
test('World event clocks, expiration and save/load remain bounded',()=>{const r=runtime(),s=r.S.fresh();r.load(s);for(let n=0;n<24;n++)r.E.action('breath');assert.equal(r.E.getState().worldClock,24);assert.ok(r.E.getState().worldEvents.length);const a=r.E.getState().worldEvents;r.E.action('save');r.E.action('load');assert.deepEqual(r.E.getState().worldEvents,a);assert.ok(r.E.getState().worldEvents.every(x=>x.endsAt>24));});
test('Local pools differ in at least ten sectors and new content remains reachable',()=>{const r=runtime(),pools=new Set();for(const id of ['cordon','garbage','darkvalley','swamp','yantar','railway','quarry','greenhouse','floodplain','mirrorLake'])pools.add(r.W.events.filter(x=>x.locations?.includes(id)).map(x=>x.id).join(','));assert.equal(pools.size,10);for(const loc of Object.values(r.W.locations))for(const next of loc.neighbors)assert.ok(r.W.locations[next]);});
test('Medusa clamping and new equipment effects never grant free health',()=>{const r=runtime(),s=r.S.fresh();s.inventory.push({id:'jellyfish',qty:1,instanceId:'medusa'},{id:'surveyPack',qty:1,instanceId:'pack7'},{id:'echoHeart',qty:1,instanceId:'heart7'});r.load(s);r.E.action('artifact','medusa');assert.equal(r.E.getState().player.health,95);r.E.action('artifact','medusa');assert.equal(r.E.getState().player.health,95);assert.equal(r.E.getState().stats.maxHealth,100);r.E.action('use',r.E.getState().inventory.findIndex(x=>x.id==='medkit'));assert.equal(r.E.getState().player.health,100);r.E.action('artifact','heart7');assert.equal(r.E.getState().player.health,100);assert.equal(r.E.getState().stats.maxHealth,114);r.E.action('equipGear','pack7');assert.equal(r.E.getState().capacity,37);r.E.action('unequipSlot','backpack');assert.equal(r.E.getState().capacity,25);});

test('Every v7 choice executes with valid prerequisites and survives state sanitization',()=>{const r=runtime();let count=0;for(const e of r.W.events.filter(x=>x.id.startsWith('v7_')||x.id.startsWith('npc_story_')&&r.W.people[x.id.slice(10)]?.home))for(const stage of e.stages)for(const c of stage.choices){
 const s=eventSave(r,e.id,stage.id,c.action==='joinFaction'||c.action==='questPanel'?'event':'explore');s.player.location=e.locations[0];s.explorationOriginLocationId=s.player.location;s.player.money=100000;s.player.rank=10;s.baseStats.maxHealth=200;s.player.health=200;s.baseStats.maxCarryWeight=100;s.reputation=Object.fromEntries(Object.keys(r.W.factions).map(id=>[id,50]));s.attributes={strength:10,agility:10,endurance:10,perception:10,intelligence:10};
 if(c.when?.background)s.backgroundId=c.when.background;if(c.when?.faction)s.factionMembership=c.when.faction;
 for(const [id,n]of Object.entries({...c.when?.items,...c.effects?.itemCost}))s.inventory.push({id,qty:Math.max(n,2),...(!r.I.items[id].stackable?{instanceId:'test-'+id}:{})});
 if(c.effects?.researchQuest)s.quests.active.push({id:c.effects.researchQuest,progress:0,step:0});
 r.load(s);if(!r.E.getState().event.choices.some(x=>x.label===c.label))continue;select(r,c.label);assert.equal(r.errors.length,0,e.id+':'+c.label);r.E.action('save');r.E.action('load');assert.ok(r.E.getState().player.location);count++;
 }assert.ok(count>150);console.log('  '+count+' new choices exercised');});
test('Temporary closure blocks only its road and expires without mutating world topology',()=>{const r=runtime(),s=r.S.fresh();s.player.location='southTunnel';assert.ok(r.W.locations.southTunnel.neighbors.includes('rookie'));s.worldEvents=[{id:'roadClosure',endsAt:4}];r.load(s);assert.equal(r.E.getState().routes.find(x=>x.id==='rookie').open,false);r.E.action('travel','rookie');assert.equal(r.E.getState().player.location,'southTunnel');for(let n=0;n<4;n++)r.E.action('breath');assert.equal(r.E.getState().routes.find(x=>x.id==='rookie').open,true);});
test('Expedition report persists after Return; ordinary travel cannot become an expedition',()=>{const r=runtime(),s=r.S.fresh();s.player.location='quarry';r.load(s);r.ctx.Math.random=()=>.99;r.E.action('explore');settle(r);r.E.action('eventReturn');assert.equal(r.E.getState().lastExpedition.originLocationId,'quarry');r.E.action('save');r.E.action('load');assert.equal(r.E.getState().lastExpedition.depth,1);r.E.action('openPanel','expeditionReport');assert.match(r.root.innerHTML,/Каменоломня/);r.E.action('closePanel');r.E.action('travel','garbage');assert.equal(r.E.getState().expedition.active,false);assert.equal(r.E.getState().player.location,'garbage');});
test('Dead saves never resume exploration or revive the player',()=>{const r=runtime(),s=eventSave(r,'event_6_3');s.player.health=0;r.load(s);assert.equal(r.E.getState().mode,'dead');assert.equal(r.E.getState().expedition.active,false);assert.equal(r.E.getState().event,null);});
test('All weapon slots empty remain renderable in location and inventory',()=>{const r=runtime(),s=r.S.fresh();s.inventory=s.inventory.filter(x=>r.I.items[x.id].type!=='weapon');s.equipment.primary=null;s.equipment.sidearm=null;s.equipment.melee=null;r.load(s);assert.equal(r.E.getState().activeWeapon,null);r.E.action('openPanel','inventory');assert.match(r.root.innerHTML,/Рюкзак/);});

test('Scavenger start immediately recognises the already reached Garbage route target',()=>{const r=runtime();r.E.action('startGame','scavenger');const q=r.E.getState().quests.active.find(x=>x.id==='first_road');assert.equal(q.step,1);assert.equal(r.E.getState().player.location,'garbage');r.E.action('save');r.E.action('load');assert.equal(r.E.getState().quests.active.find(x=>x.id==='first_road').step,1);});
test('NPC memory and field discoveries persist after notes age out',()=>{const r=runtime(),s=r.S.fresh();s.player.location='radioHill';r.load(s);r.E.action('npcAction','guide7:talk');assert.equal(r.E.getState().npcMemory.guide7.visits,1);select(r,'Спросить о секторе');select(r,'Продолжить');const save=r.E.getState();save.knowledge=Array.from({length:100},(_,i)=>'record '+i);r.load(save);r.E.action('npcAction','guide7:talk');assert.match(r.E.getState().event.text,/узнаёт тебя/);assert.equal(r.E.getState().npcMemory.guide7.visits,2);});
test('Faction symbols, journal, report and field guide screens render without missing state fields',()=>{const r=runtime(),s=r.S.fresh();s.discoveredEnemies=['boar','mirrorStalker'];s.discoveredArtifacts=['jellyfish','mirrorSeed'];r.load(s);for(const mode of ['factions','encyclopedia','expeditionReport','map','quests','character','inventory']){r.E.action('openPanel',mode);assert.ok(r.root.innerHTML.length>100);assert.ok(!r.root.innerHTML.includes('undefined'));}});
console.log(passed+' v7 checks passed.');


