const assert=require('node:assert/strict');
const {runtime,eventSave,select}=require('./runtime.cjs');let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
const snapshot=s=>JSON.stringify({event:s.event,expedition:s.expedition,location:s.player.location,inventory:s.inventory});
test('Global dock and panel return preserve choices and result across all PDA sections',()=>{const r=runtime();r.load(eventSave(r,'event_6_3'));for(const phase of ['choices','result']){if(phase==='result')select(r,'Забрать находку');const before=snapshot(r.E.getState());for(const panel of ['inventory','character','quests','map','more','factions','encyclopedia','notebook','settings','pause']){r.E.action('openPanel',panel);assert.match(r.root.innerHTML,/aria-label="Основная навигация"/);r.E.action('openPanel','more');r.E.action('closePanel');assert.equal(r.E.getState().mode,'event');assert.equal(snapshot(r.E.getState()),before);}assert.doesNotMatch(r.root.innerHTML,/Запасы и снаряжение|Сохранить вылазку/);assert.match(r.root.innerHTML,/<button class="dock-button" disabled/);}});
test('Map is viewable, every travel control disabled and engine travel blocked',()=>{const r=runtime();r.load(eventSave(r,'event_6_3'));const before=snapshot(r.E.getState());r.E.action('openPanel','map');assert.match(r.root.innerHTML,/Нельзя перейти в другую локацию во время вылазки/);const controls=r.root.innerHTML.match(/<button[^>]*data-action="travel"[^>]*>/g)||[];assert.ok(controls.length>=29);assert.ok(controls.every(x=>x.includes('disabled')));r.E.action('travel','garbage');assert.equal(snapshot(r.E.getState()),before);r.E.action('closePanel');assert.equal(r.E.getState().mode,'event');});
test('Global Explore cannot advance or restart active expedition; encounter Continue still advances',()=>{const r=runtime();r.load(eventSave(r,'event_6_3'));select(r,'Забрать находку');const before=snapshot(r.E.getState());r.E.action('explore');assert.equal(snapshot(r.E.getState()),before);const depth=r.E.getState().expedition.depth;select(r,'Продолжить');assert.equal(r.E.getState().expedition.depth,depth+1);});
test('Single save under More preserves result, origin, depth and inventory after load',()=>{const r=runtime();r.load(eventSave(r,'event_6_3'));select(r,'Забрать находку');const before=snapshot(r.E.getState());r.E.action('openPanel','more');assert.equal((r.root.innerHTML.match(/data-action="save"/g)||[]).length,1);assert.match(r.root.innerHTML,/Сохранить игру/);r.E.action('save');r.E.action('load');assert.equal(snapshot(r.E.getState()),before);assert.equal(r.E.getState().mode,'event');r.E.action('openPanel','pause');assert.doesNotMatch(r.root.innerHTML,/data-action="save"/);});
test('All location screens omit raw preparation JS and duplicate inventory/save CTAs',()=>{const r=runtime();for(const id of Object.keys(r.W.locations)){const s=r.S.fresh();s.player.location=id;r.load(s);const text=r.root.innerHTML.replace(/<[^>]*>/g,'');assert.doesNotMatch(text,/\?\.|\|\||\$\{|s\.activeWeapon|s\.player/);assert.doesNotMatch(r.root.innerHTML,/preparation-note|Проверить инвентарь|data-action="save"/);assert.match(r.root.innerHTML,/Основная навигация/);}});
test('Combat navigation uses existing combat item system and returns to same enemy',()=>{const r=runtime(),s=r.S.fresh();s.combat={type:'dog',enemy:{...r.W.enemyTypes.dog,hp:34,maxHp:34},aimed:false,turn:1,log:[]};r.load(s);const before=snapshot(r.E.getState());assert.match(r.root.innerHTML,/data-value="combatItems"/);for(const panel of ['combatItems','character','quests','map','more']){r.E.action('openPanel',panel);assert.match(r.root.innerHTML,/Основная навигация/);r.E.action('closePanel');assert.equal(r.E.getState().mode,'combat');assert.equal(snapshot(r.E.getState()),before);}});
console.log(passed+' navigation checks passed');
