const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {runtime,eventSave,select,qty}=require('./runtime.cjs');let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
function finish(r){for(let i=0;i<20&&r.E.getState().event;i++){const s=r.E.getState();if(s.combat){r.ctx.Math.random=()=>0;r.E.action('flee');continue;}if(s.event.flow.phase==='result'&&!s.event.flow.pending?.nextStage&&!s.event.flow.pending?.nextEvent&&s.expedition.active){r.E.action('eventReturn');continue;}const c=s.event.choices.find(c=>c.action==='advance')||s.event.choices.find(c=>c.finish&&!c.combat&&!c.effects?.itemCost)||s.event.choices[0];select(r,c.label);}assert.equal(r.E.getState().event,null);}
function progressSnapshot(s){return JSON.stringify([s.player,s.worldClock,s.inventory,s.quests,s.statistics,s.expedition]);}
function combatSeed(r,type){const s=r.S.fresh();s.baseStats.maxHealth=400;s.player.health=400;s.combat={type,enemy:{...r.W.enemyTypes[type],hp:r.W.enemyTypes[type].hp,maxHp:r.W.enemyTypes[type].hp},turn:1,aimed:false,log:[]};s.inventory.push({id:'ammo918',qty:80});return s;}
function win(r){r.ctx.Math.random=()=>0;for(let i=0;i<150&&r.E.getState().combat;i++){const w=r.E.getState().activeWeapon;if(w?.weapon.ammoType&&!w.magazine)r.E.action('reload');else r.E.action('attack');}assert.equal(r.E.getState().combat,null);assert.notEqual(r.E.getState().mode,'dead');}

test('Pig NPC has separate identity, three-legged local art, interactions, no combat fallback',()=>{
  const r=runtime(),id='npc_threeLeggedPigBandit',s=r.S.fresh('soldier');assert.equal(r.W.people[id].species,'трёхногая свинья');assert.equal(r.W.enemyTypes.bandit.visual,'bandit');
  assert.ok(fs.existsSync(path.join(__dirname,'../assets/sprites/npc-pig-bandit.svg')));r.load(s);r.E.action('openPanel','people');assert.match(r.root.innerHTML,/npc-pig-bandit.svg/);assert.ok(!r.root.innerHTML.includes('data-value="'+id+':fight"'));
  r.E.action('npcAction',id+':fight');assert.equal(r.E.getState().combat,null);r.E.action('npcAction',id+':talk');assert.match(r.root.innerHTML,/npc-pig-bandit.svg/);select(r,'Спросить караульного о Бандите');assert.ok(r.E.getState().knowledge.some(x=>x.includes('трёхногая свинья')));finish(r);
});
test('Pig care is bounded by world time; food consumed, gift once, memory survives save',()=>{
  const r=runtime(),id='npc_threeLeggedPigBandit',s=r.S.fresh('soldier');r.load(s);const initial=qty(r.E.getState(),'bandage');
  for(let n=0;n<3;n++){r.E.action('npcAction',id+':talk');select(r,n===0?'Угостить консервами':'Погладить Бандита');finish(r);r.E.action('save');r.E.action('load');if(n<2)r.E.action('breath');}
  assert.equal(qty(r.E.getState(),'canned'),1);assert.equal(qty(r.E.getState(),'bandage'),initial+1);assert.equal(r.E.getState().npcMemory[id].care,3);
  r.E.action('npcAction',id+':talk');select(r,'Погладить Бандита');assert.equal(r.E.getState().event.flow.phase,'choices');assert.equal(r.E.getState().npcMemory[id].care,3);select(r,'Уйти');finish(r);r.E.action('breath');r.E.action('npcAction',id+':talk');select(r,'Погладить Бандита');assert.equal(qty(r.E.getState(),'bandage'),initial+1);
});
test('Six starts differ in stats/items/reputation/intro, Rookie has two flexible points',()=>{
  const r=runtime(),signatures=new Set(),intros=new Set();for(const id of Object.keys(r.S.BACKGROUNDS)){r.E.action('startGame',id);const s=r.E.getState();signatures.add(JSON.stringify([s.player.location,s.inventory,s.reputation,s.stats]));assert.equal(s.event.id,'v72_intro_'+id);intros.add(s.event.text);const before=progressSnapshot(s);r.E.action('save');r.E.action('load');assert.equal(progressSnapshot(r.E.getState()),before);finish(r);r.E.action('openPanel','character');assert.match(r.root.innerHTML,new RegExp(r.S.BACKGROUNDS[id].name));}
  assert.equal(signatures.size,6);assert.equal(intros.size,6);const rookie=r.S.fresh();assert.equal(rookie.attributePoints,2);assert.equal(qty(rookie,'antirad'),1);assert.equal(rookie.reputation.military,0);
});
test('Medic passive healing works once; background modifiers never stack after load',()=>{const r=runtime(),s=r.S.fresh('medic');s.player.health=40;r.load(s);r.E.action('use',r.E.getState().inventory.findIndex(x=>x.id==='medkit'));assert.equal(r.E.getState().player.health,40+r.I.items.medkit.effect.health*1.05);const stats=JSON.stringify(r.E.getState().stats);for(let i=0;i<3;i++){r.E.action('save');r.E.action('load');assert.equal(JSON.stringify(r.E.getState().stats),stats);}});
test('Paid rest with 0 or 34 money changes no gameplay state; explicit free breath remains',()=>{const r=runtime();for(const money of [0,34]){const s=r.S.fresh();s.player.money=money;s.player.stamina=10;s.player.health=40;r.load(s);const before=progressSnapshot(r.E.getState());r.E.action('rest');assert.equal(progressSnapshot(r.E.getState()),before);assert.match(r.E.getState().log.at(-1),/Недостаточно денег/);r.E.action('breath');assert.equal(r.E.getState().player.stamina,35);}const s=r.S.fresh();s.player.stamina=20;s.player.health=40;r.load(s);r.E.action('rest');assert.equal(r.E.getState().player.money,585);assert.equal(r.E.getState().worldClock,2);assert.equal(r.E.getState().player.health,65);});
test('Toolkit hatch grants APS and ammo once, retains toolkit and flag after reload',()=>{const r=runtime(),s=eventSave(r,'v61_yard_mechanic','follow');s.player.location='machineYard';s.inventory.push({id:'tools',qty:1,instanceId:'tool72'});r.load(s);const ammo=qty(r.E.getState(),'ammo918');select(r,'[Набор инструментов] Поднять застрявший люк');assert.equal(qty(r.E.getState(),'aps'),1);assert.equal(qty(r.E.getState(),'ammo918'),ammo+24);assert.equal(qty(r.E.getState(),'tools'),1);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().worldFlags.hatchOpened,true);const again=eventSave(r,'v61_yard_mechanic','follow');again.player.location='machineYard';again.worldFlags.hatchOpened=true;again.inventory=r.E.getState().inventory;r.load(again);assert.ok(!r.E.getState().event.choices.some(c=>/люк/i.test(c.label)));});
test('Full backpack leaves hatch reward unclaimed until space exists',()=>{const r=runtime(),s=eventSave(r,'v61_yard_mechanic','follow');s.player.location='machineYard';s.inventory.push({id:'tools',qty:1},{id:'parts',qty:100});r.load(s);select(r,'[Набор инструментов] Поднять застрявший люк');assert.equal(r.E.getState().worldFlags.hatchOpened,false);assert.equal(qty(r.E.getState(),'aps'),0);assert.equal(r.E.getState().event.flow.phase,'choices');});
test('Knife has no ammunition UI/reload; attacks, accuracy, mastery, miss and save work',()=>{const r=runtime();r.load(combatSeed(r,'boar'));r.E.action('switchWeapon','melee');assert.match(r.root.innerHTML,/АТАКОВАТЬ НОЖОМ/);const arena=r.root.innerHTML.match(/<section class="combat-card[\s\S]*?<\/section>/)[0];assert.doesNotMatch(arena,/ПЕРЕЗАРЯДКА|запас|0\/—/);const ammo=qty(r.E.getState(),'ammo918'),mag=r.E.getState().magazines.pm,hp=r.E.getState().combat.enemy.hp;r.ctx.Math.random=()=>0;r.E.action('attack');assert.ok(r.E.getState().combat.enemy.hp<hp);assert.ok(r.E.getState().weaponMastery.melee>0);assert.equal(qty(r.E.getState(),'ammo918'),ammo);assert.equal(r.E.getState().magazines.pm,mag);r.ctx.Math.random=()=>.999;r.E.action('attack');assert.match(r.E.getState().combat.log.join(' '),/отскакивает от лезвия/);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().activeWeapon.id,'knife');r.E.action('openPanel','inventory');const knifeRow=r.root.innerHTML.match(/<article class="item-row-card">[\s\S]*?Охотничий нож[\s\S]*?<\/article>/)[0];assert.doesNotMatch(knifeRow,/магазин|запас|Перезаряд/);});
test('All boar intro text is in-world, no pause/developer instructions',()=>{const r=runtime();assert.doesNotMatch(JSON.stringify(r.W.enemyTypes.ironBoar)+JSON.stringify(r.W.events.find(e=>e.id==='v63_ironBoar')),/используй паузу/i);});
test('Every post-combat choice has useful outcome and once-only flag across compact save',()=>{
  for(const type of ['bandit','boar','bloodsucker'])for(const label of ['Осмотреть тела','Осмотреть поле боя','Изучить противника','Проверить оружие врага']){const r=runtime();r.load(combatSeed(r,type));win(r);assert.equal(r.E.getState().event.id,'v72_post_combat');r.E.action('save');r.E.action('load');select(r,label);const a=r.E.getState();assert.ok(a.knowledge.some(x=>x.startsWith('После боя: ')));assert.ok(Object.keys(a.event.flow.flags).some(k=>k.startsWith('postCombat:')));const inventory=JSON.stringify(a.inventory),xp=a.player.xp,money=a.player.money;r.E.action('save');r.E.action('load');assert.equal(JSON.stringify(r.E.getState().inventory),inventory);assert.equal(r.E.getState().player.xp,xp);assert.equal(r.E.getState().player.money,money);
    const replay=r.E.getState();replay.event.flow.phase='choices';r.load(replay);select(r,label);assert.equal(JSON.stringify(r.E.getState().inventory),inventory);assert.equal(r.E.getState().player.xp,xp);select(r,'Продолжить путь');finish(r);
  }
});
test('Flee does not grant post-combat victory loot/knowledge XP',()=>{const r=runtime(),s=eventSave(r,'v7_enemy_quarryDog','fight');s.player.location='quarry';r.load(s);select(r,'Вступить в бой');r.ctx.Math.random=()=>0;r.E.action('flee');select(r,'Следующий этап');const before=JSON.stringify(r.E.getState().inventory);select(r,'Осмотреть тела');assert.equal(JSON.stringify(r.E.getState().inventory),before);assert.ok(!r.E.getState().event.flow.flags['postCombat:body']);});
test('Twenty successful event draws avoid last three IDs, history survives save/load',()=>{const r=runtime(),s=r.S.fresh();s.player.location='garbage';s.inventory.push({id:'energy',qty:20});s.baseStats.maxHealth=500;s.player.health=500;r.load(s);r.ctx.Math.random=()=>0;const ids=[];for(let i=0;i<20;i++){r.E.action('explore');const id=r.E.getState().event.id;assert.ok(!ids.slice(-3).includes(id),id);ids.push(id);finish(r);if(r.E.getState().player.stamina<40)r.E.action('use',r.E.getState().inventory.findIndex(x=>x.id==='energy'));if(i===8){const recent=JSON.stringify(r.E.getState().recentEvents);r.E.action('save');r.E.action('load');assert.equal(JSON.stringify(r.E.getState().recentEvents),recent);}assert.ok(r.E.getState().recentEvents.length<=3);}assert.ok(new Set(ids).size>=4);});
test('Small event pool falls back to a repeat only when no alternative exists',()=>{const r=runtime();for(const e of r.W.events)e.kind='quest';const e=r.W.events.find(e=>e.id==='event_6_3');e.kind='explore';e.locations=['cordon'];e.minDanger=0;const s=r.S.fresh();s.recentEvents=[e.id];r.load(s);r.ctx.Math.random=()=>0;r.E.action('explore');assert.equal(r.E.getState().event.id,e.id);});
test('Ordinary Yantar exploration never counts anomaly traces; directed action does',()=>{const r=runtime(),s=r.S.fresh();s.player.location='yantar';r.load(s);r.E.action('acceptQuest','field_samples');r.ctx.Math.random=()=>.99;r.E.action('explore');assert.equal(r.E.getState().quests.active.find(q=>q.id==='field_samples').progress,0);finish(r);for(let n=0;n<2;n++){r.E.action('questSearch','field_samples');select(r,'Искать следы аномалий');r.E.action('save');r.E.action('load');finish(r);}const q=r.E.getState().quests.active.find(q=>q.id==='field_samples');assert.equal(q.progress,2);assert.equal(q.status,'Готово к сдаче');assert.ok(!r.E.getState().quests.completed.some(q=>q.id==='field_samples'));});
test('Field Notes directed search succeeds by third attempt and progress persists',()=>{const r=runtime(),s=r.S.fresh();s.player.location='yantar';r.load(s);assert.doesNotMatch(r.root.innerHTML,/data-action="questSearch"[^>]*field_notes/);r.E.action('acceptQuest','field_notes');assert.match(r.root.innerHTML,/Искать документы/);r.ctx.Math.random=()=>.99;for(let n=1;n<=3;n++){r.E.action('questSearch','field_notes');select(r,'Провести поиск документов');assert.equal(qty(r.E.getState(),'documents'),n===3?1:0);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().quests.active.find(q=>q.id==='field_notes').searchAttempts,n);finish(r);}assert.equal(r.E.getState().quests.active.find(q=>q.id==='field_notes').status,'Готово к сдаче');assert.doesNotMatch(r.root.innerHTML,/data-action="questSearch"[^>]*field_notes/);const money=r.E.getState().player.money;r.E.action('turnIn','field_notes');assert.equal(r.E.getState().player.money,money+900);assert.equal(qty(r.E.getState(),'documents'),0);});
test('All 55 quests have valid NPC/location/reward metadata and manual reward exactly once',()=>{const r=runtime();assert.equal(r.W.quests.length,55);for(const d of r.W.quests){assert.ok(r.W.people[d.giver],d.id);assert.ok(d.turnInLocations.length,d.id);assert.ok(d.turnInLocations.every(id=>r.W.locations[id].npcs.includes(d.giver)),d.id);assert.equal(d.rewardTrigger,'turnIn');const s=r.S.fresh();s.player.location=d.turnInLocations[0];s.quests.active=[{id:d.id,progress:d.count||1,step:1}];if(d.type==='visit')s.visited.push(d.target);if(d.type==='deliver')s.inventory.push({id:d.item,qty:d.count||1});if(d.type==='deliverType')s.inventory.push({id:'jellyfish',qty:1,instanceId:'quest-art'});r.load(s);const q=r.E.getState().quests.active[0];assert.equal(q.ready,true,d.id);assert.equal(q.canTurnIn,true,d.id);assert.equal(q.status,'Готово к сдаче',d.id);assert.equal(r.E.getState().player.money,s.player.money,d.id);r.E.action('turnIn',d.id);assert.equal(r.E.getState().player.money,s.player.money+d.reward,d.id);const paid=progressSnapshot(r.E.getState());r.E.action('turnIn',d.id);assert.equal(progressSnapshot(r.E.getState()),paid,d.id);}});
test('Route arrival records objective but manual turn-in pays only at giver',()=>{const r=runtime(),s=r.S.fresh();s.player.location='rookie';s.quests.active=[{id:'first_road',progress:0,step:0}];r.load(s);r.ctx.Math.random=()=>.99;r.E.action('travel','garbage');assert.equal(r.E.getState().player.money,620);assert.equal(r.E.getState().quests.active[0].status,'Готово к сдаче');r.E.action('travel','cordon');assert.equal(r.E.getState().player.money,620);assert.equal(r.E.getState().quests.active[0].canTurnIn,true);r.E.action('turnIn','first_road');assert.equal(r.E.getState().player.money,1070);});
test('Auto turn-in defaults OFF, persists, pays eligible local routes only and never story choices',()=>{const r=runtime(),s=r.S.fresh();s.quests.active=[{id:'first_road',step:1,progress:0}];r.load(s);assert.equal(r.E.getState().settings.autoTurnInQuests,false);r.E.action('openPanel','settings');assert.match(r.root.innerHTML,/Автоматически сдавать задания/);r.E.action('setSetting',{key:'autoTurnInQuests',value:true});assert.equal(r.E.getState().player.money,620);r.E.action('closePanel');assert.equal(r.E.getState().player.money,1070);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().settings.autoTurnInQuests,true);const x=r.S.fresh();x.player.location='garbage';x.quests.active=[{id:'first_road',step:1,progress:0}];x.settings.autoTurnInQuests=true;r.load(x);assert.equal(r.E.getState().player.money,620);const d=r.W.quests.find(q=>q.id==='first_road');d.requiresDialogue=true;x.player.location='cordon';r.load(x);assert.equal(r.E.getState().player.money,620);assert.equal(r.E.getState().quests.active.length,1);});
test('v9 migration preserves old progression/gear, resets false anomaly count and defaults auto OFF',()=>{const r=runtime(),s=r.S.fresh();s.version=9;s.player.money=6789;s.quests.active=[{id:'field_samples',progress:2,step:0},{id:'railway_cache',progress:2,step:0}];delete s.settings.autoTurnInQuests;r.load(s);assert.equal(r.E.getState().version,10);assert.equal(r.E.getState().player.money,6789);assert.equal(r.E.getState().quests.active.find(q=>q.id==='field_samples').progress,0);assert.equal(r.E.getState().quests.active.find(q=>q.id==='railway_cache').progress,2);assert.equal(r.E.getState().settings.autoTurnInQuests,false);assert.equal(r.E.getState().activeWeapon.id,'pm');});
test('Faction UI distinguishes player reputation and faction-to-faction relations',()=>{const r=runtime();r.load(r.S.fresh());r.E.action('openPanel','factions');assert.match(r.root.innerHTML,/Как эта группировка относится лично к вам/);assert.match(r.root.innerHTML,/Как эта группировка относится к другим фракциям/);assert.match(r.root.innerHTML,/Свобода: Враждебное/);});
test('Compact CSS affects dock only; More keeps 48px targets and navigation regression',()=>{const css=fs.readFileSync(path.join(__dirname,'../style.css'),'utf8');assert.match(css,/\.action-dock \.dock-button\{min-height:36px/);assert.match(css,/min-height:44px/);assert.match(css,/\.menu-actions>button\{[^}]*min-height:48px/);const r=runtime();r.load(eventSave(r,'event_6_3'));r.E.action('openPanel','more');assert.match(r.root.innerHTML,/Сохранить игру/);r.E.action('closePanel');assert.equal(r.E.getState().event.id,'event_6_3');});
test('Browser harness loads local scripts and all five v7.2 fixtures sanitize correctly',()=>{const vm=require('node:vm'),html=fs.readFileSync(path.join(__dirname,'browser.html'),'utf8');for(const [,src]of html.matchAll(/<script[^>]*src="([^"]+)"/g))assert.ok(fs.existsSync(path.resolve(__dirname,'..',src)),src);for(const scenario of ['v72-pig','v72-quests','v72-turnin','v72-knife','v72-hatch']){const r=runtime(),store=new Map();r.ctx.URLSearchParams=URLSearchParams;r.ctx.location={search:'?scenario='+scenario};r.ctx.addEventListener=()=>{};r.ctx.sessionStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};r.ctx.ZoneRPGState=r.S;r.ctx.ZoneRPGWorld=r.W;Object.defineProperty(r.ctx,'ZoneRPGSave',{get:()=>r.ctx.window.ZoneRPGSave});r.ctx.console.warn=()=>{};vm.runInContext(fs.readFileSync(path.join(__dirname,'browser-fixture.js'),'utf8'),r.ctx);const seeded=r.ctx.window.ZoneRPGSave.read();assert.equal(seeded.ok,true,scenario);const s=r.load(seeded.data);if(scenario==='v72-knife')assert.equal(s.activeWeapon.id,'knife');if(scenario==='v72-quests')assert.equal(s.quests.active.length,2);if(scenario==='v72-pig')assert.equal(s.player.location,'checkpoint');if(scenario==='v72-hatch')assert.equal(s.event.flow.stageId,'follow');}});
console.log(passed+' quality v7.2 checks passed.');
