const assert=require('node:assert/strict');
const {runtime,eventSave,select}=require('./runtime.cjs');
let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
const xp=s=>s.player.xp+Array.from({length:s.player.rank-1},(_,i)=>120+i*75).reduce((a,b)=>a+b,0);
function listen(r){r.E.action('news');select(r,'Послушать слухи');const s=r.E.getState();select(r,'Продолжить');return s;}
function travel(r,id){r.ctx.Math.random=()=>.999;r.E.action('travel',id);assert.equal(r.E.getState().player.location,id);assert.equal(r.E.getState().event,null);}
function raw(r){r.E.action('save');return JSON.parse(r.store.get(r.S.KEY));}

test('Every background starts with an empty history and the correct world visit',()=>{const r=runtime();for(const bg of Object.keys(r.S.BACKGROUNDS)){r.E.action('startGame',bg);const s=r.E.getState();assert.equal(s.rumorVisit.location,s.player.location);assert.equal(s.rumorVisit.heard,false);assert.equal(s.heardRumors.length,0);assert.equal(s.rumors.length,0);}});
test('First rumor gives 8 XP and real title/text in both PDA sections',()=>{const r=runtime();r.load(r.S.fresh());const s=listen(r);assert.equal(xp(s),8);assert.equal(s.rumors.length,1);assert.equal(s.heardRumors.length,1);assert.equal(s.rumorVisit.heard,true);assert.ok(s.event.text.includes(s.rumors[0].title));assert.ok(s.event.text.includes(s.rumors[0].text));for(const panel of ['notebook','encyclopedia']){r.E.action('openPanel',panel);assert.ok(r.root.innerHTML.includes(s.rumors[0].title));assert.ok(r.root.innerHTML.includes(s.rumors[0].text));assert.ok(!r.root.innerHTML.includes(s.rumors[0].id));}assert.equal(r.warnings.length,0);});
test('Repeated clicks, panels, rest and save/load do not open another visit',()=>{const r=runtime();r.load(r.S.fresh());listen(r);r.E.action('breath');r.E.action('rest');r.E.action('openPanel','inventory');r.E.action('closePanel');r.E.action('save');r.E.action('load');for(let n=0;n<12;n++){const s=listen(r);assert.equal(xp(s),8);assert.equal(s.rumors.length,1);assert.match(s.event.text,/Вы уже услышали последние слухи\. Новостей пока нет/);}r.E.action('openPanel','encyclopedia');assert.equal(r.warnings.length,0);});
test('Cordon -> Garbage -> Cordon resets only the visit and prefers unseen rumors',()=>{const r=runtime();r.load(r.S.fresh());const first=listen(r).rumors[0].id;travel(r,'garbage');assert.equal(r.E.getState().rumorVisit.heard,false);listen(r);travel(r,'cordon');const out=listen(r);assert.equal(out.rumors.length,3);assert.equal(xp(out),24);assert.notEqual(out.rumors[2].id,first);assert.equal(new Set(out.heardRumors).size,3);});
test('Travel request leaves visit intact until arrival, including pending travel save/load',()=>{const r=runtime();r.load(r.S.fresh());listen(r);r.ctx.Math.random=()=>0;r.E.action('travel','garbage');assert.ok(r.E.getState().event);assert.equal(r.E.getState().rumorVisit.location,'cordon');assert.equal(r.E.getState().rumorVisit.heard,true);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().rumorVisit.heard,true);const s=raw(r);s.event=null;s.travelTo='garbage';r.load(s);assert.equal(r.E.getState().rumorVisit.location,'garbage');assert.equal(r.E.getState().rumorVisit.heard,false);assert.equal(r.E.getState().heardRumors.length,1);});
test('Expedition and return to its origin preserve the world visit',()=>{const r=runtime();r.load(r.S.fresh());listen(r);r.E.action('explore');assert.ok(r.E.getState().expedition.active);for(let n=0;n<12;n++){const e=r.E.getState().event;if(e.flow.phase==='result'&&!e.flow.pending?.nextStage&&!e.flow.pending?.nextEvent)break;const c=e.choices.find(c=>c.action==='advance')||e.choices.find(c=>c.finish&&!c.combat)||e.choices.find(c=>!c.combat);assert.ok(c);select(r,c.label);}r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'cordon');assert.equal(r.E.getState().rumorVisit.heard,true);const s=listen(r);assert.equal(s.rumors.length,1);assert.match(s.event.text,/Новостей пока нет/);});
test('Save/load with temporary encounter coordinates preserves the expedition origin visit',()=>{const r=runtime();r.load(r.S.fresh());listen(r);r.E.action('explore');const s=raw(r);s.player.location='garbage';r.load(s);assert.equal(r.E.getState().rumorVisit.location,'cordon');assert.equal(r.E.getState().rumorVisit.heard,true);});
test('NPC camp news shares the visit guard and never repeats rumor XP',()=>{const r=runtime();r.load(r.S.fresh());listen(r);const saved=raw(r),event=eventSave(r,'npc_story_sidorovich','contact','event').event;saved.event=event;saved.mode='event';r.load(saved);select(r,'Обсудить новости');const s=r.E.getState();assert.equal(xp(s),8);assert.equal(s.rumors.length,1);assert.match(s.event.text,/Новостей пока нет/);});
test('Exhausted local pool returns explanation without duplicate notes or XP',()=>{const r=runtime(),s=r.S.fresh();s.heardRumors=r.ctx.window.ZoneRPGKnowledge.pool('cordon').map(d=>d.id);r.load(s);for(let n=0;n<5;n++){const out=listen(r);assert.equal(xp(out),0);assert.equal(out.rumors.length,0);assert.match(out.event.text,/ничего нового здесь уже не рассказывают/);}assert.equal(r.warnings.length,0);});
test('All available rumors across repeated real visits pay exactly once',()=>{const r=runtime();r.load(r.S.fresh());const count=r.ctx.window.ZoneRPGKnowledge.pool('cordon').length;for(let n=0;n<count+2;n++){listen(r);const s=raw(r);Object.assign(s.player,{health:100,stamina:100,hunger:0,thirst:0,radiation:0});r.load(s);travel(r,'garbage');travel(r,'cordon');}const out=r.E.getState();assert.equal(out.rumors.length,count);assert.equal(xp(out),count*8);assert.equal(new Set(out.rumors.map(d=>d.id)).size,count);});
test('v11 migration preserves text records, resolves ID-only records and prevents known rumor XP',()=>{const r=runtime(),s=r.S.fresh(),K=r.ctx.window.ZoneRPGKnowledge,def=K.pool('cordon')[0];s.version=11;delete s.heardRumors;delete s.rumorVisit;s.rumors=[{text:def.text,location:'Кордон',time:8},'rumor_darkValley_03'];s.knowledge=['rumor:cordon','camp news cordon','npc-met:sidorovich','v63 ironBoar observed'];r.load(s);let out=r.E.getState();assert.equal(out.version,r.S.VERSION);assert.equal(out.rumors.length,2);assert.ok(out.heardRumors.includes(def.id));assert.equal(out.rumors[0].title,def.title);assert.equal(out.rumors[1].text,K.rumor('rumor_darkValley_03').text);assert.equal(xp(out),0);out=listen(r);assert.notEqual(out.rumors.at(-1).id,def.id);assert.equal(xp(out),8);r.E.action('openPanel','encyclopedia');for(const id of s.knowledge)assert.ok(!r.root.innerHTML.includes(id));assert.equal(r.warnings.length,0);});
test('Legacy rumor IDs stored as text resolve through the same registry',()=>{const r=runtime(),s=r.S.fresh();s.version=11;s.rumors=[{text:'rumor_darkValley_03',location:'darkvalley'}];r.load(s);assert.equal(r.E.getState().rumors[0].id,'rumor_zone_03');r.E.action('openPanel','notebook');assert.match(r.root.innerHTML,/Сигнал старой вышки/);assert.doesNotMatch(r.root.innerHTML,/rumor_darkValley|darkvalley/);assert.equal(r.warnings.length,0);});
test('Every current knowledge key resolves centrally; enemy/item/location/faction/quest IDs are localized',()=>{const r=runtime(),K=r.ctx.window.ZoneRPGKnowledge;let count=0;for(const event of r.W.events)for(const stage of event.stages||[{choices:event.choices}])for(const choice of stage.choices||[])for(const key of [].concat(choice.effects?.knowledge||[])){const d=K.display(key);assert.notEqual(d.title,'Неизвестная запись',key);assert.match(d.title,/[А-Яа-яЁё]/,key);assert.ok(!d.text.includes(key)||/[А-Яа-яЁё]/.test(key),key);count++;}for(const id of ['darkvalley','garbage','bloodsucker','pm','loners','first_road']){const d=K.display(id==='bloodsucker'?'enemy '+id:id);assert.notEqual(d.title,'Неизвестная запись');assert.ok(!d.title.includes(id));}assert.equal(r.warnings.length,0);console.log('  '+count+' knowledge definitions checked');});
test('Unknown IDs never leak and warn only once across repeated render',()=>{const r=runtime(),s=r.S.fresh();s.knowledge=['rumor_missing_99'];s.rumors=[{id:'event_missing_99'}];r.load(s);for(let n=0;n<4;n++)r.E.action('openPanel','encyclopedia');assert.match(r.root.innerHTML,/Неизвестная запись/);assert.doesNotMatch(r.root.innerHTML,/rumor_missing_99|event_missing_99/);assert.equal(r.warnings.length,2);assert.equal(r.errors.length,0);});
test('Rumor button remains enabled and uses the other location actions CSS class',()=>{const r=runtime();r.load(r.S.fresh());for(let n=0;n<2;n++){assert.match(r.root.innerHTML,/<button class="secondary-button"[^>]*data-action="news"[^>]*>Послушать слухи<\/button>/);listen(r);}assert.doesNotMatch(r.root.innerHTML,/<button[^>]*data-action="news"[^>]*disabled/);});
console.log(passed+' v8.1 checks passed.');
