const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {runtime,eventSave,select,qty}=require('./runtime.cjs');let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
const final=s=>s.event?.flow.phase==='result'&&!s.event.flow.pending?.nextStage&&!s.event.flow.pending?.nextEvent;
function resolve(r){for(let i=0;i<60;i++){const s=r.E.getState();if(final(s))return s;if(s.combat){r.ctx.Math.random=()=>0;if(s.activeWeapon.magazine===0)r.E.action('reload');else r.E.action('attack');continue;}assert.ok(s.event,'Missing event');const c=s.event.choices.find(c=>c.action==='advance')||s.event.choices.find(c=>c.finish&&!c.combat&&!c.effects?.money&&!c.effects?.itemCost)||s.event.choices.find(c=>!c.combat&&!c.effects?.money&&!c.effects?.itemCost)||s.event.choices[0];select(r,c.label);}throw Error('Unfinished chain');}
function seed(r,location,id='event_6_3'){const s=eventSave(r,id);s.player.location=location;s.explorationOriginLocationId=location;s.explorationSessionDepth=1;s.seenEvents=[id];s.recentEvents=[id];s.known=[location];s.visited=[location];r.load(s);return s;}
const totalXP=s=>s.player.xp+Array.from({length:s.player.rank-1},(_,i)=>120+i*75).reduce((a,b)=>a+b,0);
function finishAndReturn(r){resolve(r);r.E.action('eventReturn');assert.equal(r.E.getState().event,null);}

test('Continue immediately selects next encounter with no emitted idle state',()=>{const r=runtime();seed(r,'garbage');select(r,'Забрать находку');assert.ok(final(r.E.getState()));const before=r.E.getState(),renders=[];r.E.onChange(()=>renders.push(r.E.getState()));select(r,'Продолжить');const s=r.E.getState();assert.ok(s.event);assert.notEqual(s.event.id,before.event.id);assert.equal(s.player.location,'garbage');assert.equal(s.explorationOriginLocationId,'garbage');assert.equal(s.explorationSessionDepth,2);assert.equal(s.explores.garbage,(before.explores.garbage||0)+1);assert.ok(renders.length);assert.ok(renders.every(x=>x.event&&x.mode!=='play'));});
test('Three encounters retain warehouse origin; Return keeps earned rewards',()=>{const r=runtime();seed(r,'warehouses');select(r,'Забрать находку');for(let n=0;n<2;n++){select(r,'Продолжить');resolve(r);assert.equal(r.E.getState().explorationOriginLocationId,'warehouses');}const before=r.E.getState();r.E.action('eventReturn');const after=r.E.getState();assert.equal(after.player.location,'warehouses');assert.equal(after.explorationActive,false);assert.equal(after.explorationOriginLocationId,null);assert.equal(after.explorationSessionDepth,0);assert.equal(totalXP(after),totalXP(before));assert.equal(after.player.money,before.player.money);assert.equal(JSON.stringify(after.inventory),JSON.stringify(before.inventory));assert.equal(JSON.stringify(after.quests),JSON.stringify(before.quests));});
test('Return works in five sectors and never defaults to cordon',()=>{const r=runtime();for(const loc of ['cordon','garbage','darkvalley','warehouses','pripyat']){seed(r,loc);select(r,'Забрать находку');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,loc);assert.equal(r.E.getState().mode,'play');}});
test('Dark valley session survives multiple Continue, save/load and Return',()=>{const r=runtime();seed(r,'darkvalley');select(r,'Забрать находку');select(r,'Продолжить');resolve(r);select(r,'Продолжить');resolve(r);const depth=r.E.getState().explorationSessionDepth;r.E.action('save');r.E.action('load');assert.equal(r.E.getState().explorationOriginLocationId,'darkvalley');assert.equal(r.E.getState().explorationSessionDepth,depth);r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'darkvalley');});
test('Return uses session origin rather than temporary encounter sector',()=>{const r=runtime(),s=seed(r,'darkvalley');s.player.location='machineYard';r.load(s);select(r,'Забрать находку');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'darkvalley');});
test('Scripted continuation precedes the next ordinary encounter',()=>{const r=runtime();const s=eventSave(r,'site_railway_2');s.player.location='railway';s.explorationOriginLocationId='railway';s.explorationSessionDepth=4;r.load(s);select(r,'Осмотреться и проверить следы');const pending=r.E.getState().event.flow.pending.nextStage;select(r,'Продолжить');assert.equal(r.E.getState().event.id,'site_railway_2');assert.equal(r.E.getState().event.flow.stageId,pending);assert.equal(r.E.getState().explorationSessionDepth,4);r.E.action('eventReturn');assert.ok(r.E.getState().event);});
test('Exhausted Continue keeps result/origin; Return unlocks free recovery',()=>{const r=runtime(),s=seed(r,'wild');s.player.stamina=0;r.load(s);select(r,'Забрать находку');select(r,'Продолжить');assert.ok(final(r.E.getState()));assert.equal(r.E.getState().explorationOriginLocationId,'wild');assert.match(r.root.innerHTML,/Нет сил/);r.E.action('eventReturn');r.E.action('breath');assert.equal(r.E.getState().player.stamina,25);r.E.action('explore');assert.ok(r.E.getState().event);assert.equal(r.E.getState().explorationSessionDepth,1);});
test('Empty search has distinct Continue/Return with no completion XP',()=>{const r=runtime(),s=r.S.fresh();s.player.location='garbage';r.load(s);r.ctx.Math.random=()=>.99;r.E.action('explore');assert.ok(final(r.E.getState()));assert.match(r.root.innerHTML,/ВЕРНУТЬСЯ/);select(r,'Продолжить');assert.equal(r.E.getState().explorationSessionDepth,2);assert.equal(totalXP(r.E.getState()),0);r.E.action('save');r.E.action('load');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'garbage');});
test('Legacy versions 6/7 recover current sector as missing exploration origin',()=>{const r=runtime();for(const version of [6,7]){const s=eventSave(r,'event_6_3');s.version=version;s.player.location='darkvalley';delete s.explorationOriginLocationId;delete s.explorationSessionDepth;delete s.eventXPClaims;delete s.initialReputationModifiers;delete s.startingLocation;s.known=[];s.visited=['southTunnel'];r.load(s);const v=r.E.getState();assert.equal(v.version,8);assert.equal(v.explorationOriginLocationId,'darkvalley');assert.ok(v.known.includes('darkvalley'));assert.ok(v.known.includes('southTunnel'));select(r,'Забрать находку');r.E.action('eventReturn');assert.equal(r.E.getState().player.location,'darkvalley');}});
test('Every visited/current location remains discovered across all save versions',()=>{const r=runtime();for(const version of [6,7,8])for(const id of Object.keys(r.W.locations)){const s=r.S.fresh();s.version=version;s.player.location=id;s.known=[];s.visited=['southTunnel'];r.load(s);const v=r.E.getState();assert.ok(v.known.includes(id),id);assert.ok(v.visited.includes(id));assert.ok(v.known.includes('southTunnel'));const n=v.map.find(n=>n.id===id);assert.ok(n.current&&n.known&&n.open,id);r.E.action('save');r.E.action('load');assert.ok(r.E.getState().known.includes(id));}});
test('Southern tunnel: visit, actions, save/load, leave and revisit stays known',()=>{const r=runtime();r.load(r.S.fresh());r.ctx.Math.random=()=>.99;r.E.action('travel','southTunnel');assert.equal(r.E.getState().player.location,'southTunnel');r.E.action('explore');finishAndReturn(r);r.E.action('breath');r.E.action('save');r.E.action('load');r.ctx.Math.random=()=>.99;r.E.action('travel','cordon');r.E.action('travel','southTunnel');const s=r.E.getState();assert.equal(s.player.location,'southTunnel');assert.ok(s.known.includes('southTunnel'));assert.ok(s.map.find(n=>n.id==='southTunnel').known);});
test('Graph: all 21 reachable, valid IDs, reverse roads, unique render edges',()=>{const r=runtime(),seen=new Set(['cordon']),queue=['cordon'];while(queue.length)for(const id of r.W.locations[queue.shift()].neighbors)if(!seen.has(id)){seen.add(id);queue.push(id);}assert.equal(seen.size,21);let directed=0;for(const [id,l]of Object.entries(r.W.locations)){assert.equal(new Set(l.neighbors).size,l.neighbors.length);for(const next of l.neighbors){assert.ok(r.W.locations[next]);assert.ok((l.oneWayNeighbors||[]).includes(next)||r.W.locations[next].neighbors.includes(id));directed++;}}const edges=r.W.mapEdges();assert.equal(edges.length,directed/2);assert.ok(edges.every(e=>e.twoWay));assert.equal(new Set(edges.map(e=>[e.from,e.to].sort().join(':'))).size,edges.length);});
test('Deduplication preserves explicit one-way edge and renderer uses its arrow only',()=>{const r=runtime();let edges=r.W.mapEdges({a:{neighbors:['b','b']},b:{neighbors:[]}});assert.equal(edges.length,1);assert.equal(edges[0].twoWay,false);edges=r.W.mapEdges({a:{neighbors:['b']},b:{neighbors:['a']}});assert.equal(edges.length,1);assert.equal(edges[0].twoWay,true);r.W.locations.cordon.neighbors.push('pripyat');const s=r.S.fresh();s.known=Object.keys(r.W.locations);r.load(s);r.E.action('openPanel','map');assert.equal((r.root.innerHTML.match(/marker-end=/g)||[]).length,1);});
test('Every ordinary directed road is traversable in both directions',()=>{const r=runtime();let n=0;for(const [id,l]of Object.entries(r.W.locations))for(const next of l.neighbors){const s=r.S.fresh();s.player.location=id;s.player.health=200;s.baseStats.maxHealth=200;s.worldFlags.stationOpen=true;s.known=Object.keys(r.W.locations);r.load(s);r.ctx.Math.random=()=>.99;r.E.action('travel',next);assert.equal(r.E.getState().player.location,next,id+' -> '+next);n++;}console.log('  '+n+' directed routes traversed');});
test('Cordon/dead village return and Pripyat/warehouses/valley/dump history',()=>{const r=runtime();r.load(r.S.fresh());r.ctx.Math.random=()=>.99;r.E.action('travel','deadVillage');assert.equal(r.E.getState().player.location,'deadVillage');r.E.action('travel','cordon');assert.equal(r.E.getState().player.location,'cordon');const s=r.S.fresh();s.player.location='pripyat';r.load(s);for(const next of ['warehouses','darkvalley','garbage']){r.E.action('travel',next);assert.equal(r.E.getState().player.location,next);}r.E.action('save');r.E.action('load');assert.ok(r.E.getState().routes.find(x=>x.id==='darkvalley').open);});
test('Warehouse news cannot farm XP; claims survive save and trip counter changes',()=>{const r=runtime(),s=r.S.fresh();s.player.location='warehouses';r.load(s);for(let n=0;n<12;n++){r.E.action('news');select(r,'Послушать новости');assert.ok(r.E.getState().event.text.includes('Слух:'));select(r,'Продолжить');if(n===4){r.E.action('save');r.E.action('load');}}assert.equal(totalXP(r.E.getState()),8);assert.equal(r.E.getState().rumors.length,12);const newer=r.E.getState();newer.player.trips+=3;r.load(newer);r.E.action('news');select(r,'Послушать новости');assert.equal(totalXP(r.E.getState()),8);});
test('Repeated inspection, conversation and reading definitions never repeat completion XP',()=>{const r=runtime();for(const id of ['event_6_3','npc_story_sidorovich','site_railway_2']){let claims=[],expected;for(let n=0;n<3;n++){const s=eventSave(r,id,undefined,'event');s.eventXPClaims=claims;r.load(s);resolve(r);const gained=totalXP(r.E.getState());if(n===0){expected=gained;assert.ok(expected>0,id);}else assert.equal(gained,0,id);claims=r.E.getState().eventXPClaims;r.E.action('eventReturn');assert.equal(totalXP(r.E.getState()),gained);}}});
test('Every active quest has a status; station and city route use generic target names',()=>{const r=runtime(),s=r.S.fresh();s.quests.active=r.W.quests.map(q=>({id:q.id,step:0,progress:0}));r.load(s);r.E.action('openPanel','quests');assert.equal(r.E.getState().quests.active.length,23);assert.ok(r.E.getState().quests.active.every(q=>['Не выполнено','Выполняется','Готово к сдаче'].includes(q.status)));assert.equal(r.E.getState().quests.active.find(q=>q.id==='mara_bandages').status,'Готово к сдаче');assert.match(r.root.innerHTML,/Последний рубеж/);assert.match(r.root.innerHTML,/Городская разведка/);assert.match(r.root.innerHTML,/ДОЙДИ: Припять/);assert.match(r.root.innerHTML,/ДОЙДИ: ЧАЭС/);const p=r.S.fresh();p.quests.active=[{id:'scout_pripyat',step:1,progress:0}];r.load(p);r.E.action('openPanel','quests');assert.match(r.root.innerHTML,/ВЕРНИСЬ: Свалка/);assert.equal(r.E.getState().quests.active[0].status,'Выполняется');});
test('All six starts have safe varied locations, intro, reputation and persistent metadata',()=>{const r=runtime(),starts=new Set(),base=r.S.fresh();for(const [id,b]of Object.entries(r.S.BACKGROUNDS)){r.E.action('startGame',id);let s=r.E.getState();starts.add(s.player.location);assert.equal(s.player.location,b.startLocation);assert.ok(r.W.locations[s.player.location].danger<=2);assert.ok(s.event.text.includes(b.intro));assert.ok(s.visited.includes(b.startLocation)&&s.known.includes(b.startLocation));for(const [f,n]of Object.entries(b.reputation||{}))assert.equal(s.reputation[f],base.reputation[f]+n);const before=JSON.stringify([s.inventory,s.reputation,s.attributes,s.initialReputationModifiers]);r.E.action('save');r.E.action('load');s=r.E.getState();assert.equal(s.backgroundId,id);assert.equal(s.startingLocation,b.startLocation);assert.equal(JSON.stringify([s.inventory,s.reputation,s.attributes,s.initialReputationModifiers]),before);}assert.ok(starts.size>=4);});
test('Background-specific actions are gated, functional and saved for all six histories',()=>{const r=runtime();let n=0;for(const e of r.W.events)for(const stage of e.stages)for(const c of stage.choices.filter(c=>c.when?.background)){const id=c.when.background,s=eventSave(r,e.id,stage.id,'event');s.backgroundId=id==='rookie'?'soldier':'rookie';r.load(s);assert.ok(!r.E.getState().event.choices.some(x=>x.label===c.label));s.backgroundId=id;r.load(s);const before=r.E.getState();select(r,c.label);assert.ok(final(r.E.getState()));assert.ok(r.E.getState().backgroundInteractions.some(x=>x.endsWith(c.label)));if(c.effects.rep)for(const [f,v]of Object.entries(c.effects.rep))assert.equal(r.E.getState().reputation[f],before.reputation[f]+v);if(c.effects.add)for(const [id,v]of Object.entries(c.effects.add))assert.equal(qty(r.E.getState(),id),qty(before,id)+v);r.E.action('save');r.E.action('load');assert.ok(r.E.getState().backgroundInteractions.some(x=>x.endsWith(c.label)));n++;}assert.equal(n,6);});
function pathTo(e,label){const queue=[{id:e.stages[0].id,path:[]}],seen=new Set();while(queue.length){const node=queue.shift();if(seen.has(node.id))continue;seen.add(node.id);const s=e.stages.find(x=>x.id===node.id);if(s.choices.some(c=>c.label.startsWith(label)))return node.path;for(const c of s.choices)if(c.nextStage&&!c.combat)queue.push({id:c.nextStage,path:[...node.path,c.label]});}return null;}
test('Toolkit reaches three useful choices through real entry stages, without consumption',()=>{const r=runtime();let n=0;for(const e of r.W.events){const p=pathTo(e,'[Набор инструментов]');if(!p)continue;const s=eventSave(r,e.id,undefined,'event');s.inventory.push({id:'tools',qty:1,instanceId:'tool-test'});s.attributes={strength:10,agility:10,endurance:10,perception:10,intelligence:10};r.load(s);for(const label of p){select(r,label);select(r,'Продолжить');}const c=r.E.getState().event.choices.find(c=>c.label.startsWith('[Набор инструментов]'));assert.ok(c,e.id);const before=JSON.stringify([r.E.getState().inventory,r.E.getState().reputation,r.E.getState().knowledge]);select(r,c.label);assert.equal(qty(r.E.getState(),'tools'),1);assert.notEqual(JSON.stringify([r.E.getState().inventory,r.E.getState().reputation,r.E.getState().knowledge]),before);r.E.action('eventReturn');n++;if(n===3)break;}assert.equal(n,3);});
test('Five new enemies have distinct stats, scenes, intros and valid canonical sprites',()=>{const r=runtime();for(const id of ['ratSwarm','marshLeech','ironBoar','nightLurker','ashWalker']){const e=r.W.enemyTypes[id];assert.ok(e.intro&&e.description);assert.equal(e.kind,'mutant');assert.ok(fs.existsSync(path.join(__dirname,'../assets/sprites/enemy-'+e.visual+'.svg')));const s=eventSave(r,'v63_'+id);r.load(s);select(r,'Подготовиться и атаковать');const c=r.E.getState().combat;assert.equal(c.type,id);assert.equal(c.enemy.name,e.name);assert.equal(c.enemy.hp,e.hp);assert.equal(c.enemy.visual,e.visual);r.E.action('save');r.E.action('load');assert.equal(r.E.getState().combat.enemy.visual,e.visual);}for(const e of Object.values(r.W.enemyTypes))assert.equal(e.kind,e.faction==='mutants'?'mutant':'human');});
test('Mutant pool respects early/late sectors, night and depth',()=>{const r=runtime();const early=r.W.mutantOptions('cordon',12,0).map(x=>x.id);assert.ok(!early.includes('bloodsucker')&&!early.includes('ashWalker'));assert.ok(early.includes('ratSwarm'));assert.ok(!r.W.mutantOptions('redforest',12,20).some(x=>x.id==='nightLurker'));assert.ok(r.W.mutantOptions('redforest',23,20).some(x=>x.id==='nightLurker'));assert.ok(!r.W.mutantOptions('pripyat',12,0).some(x=>x.id==='ashWalker'));assert.ok(r.W.mutantOptions('pripyat',12,10).some(x=>x.id==='ashWalker'));});
test('New enemy mechanics: telegraphed heavy hit and radioactive wound',()=>{const r=runtime();r.load(eventSave(r,'v63_ironBoar'));select(r,'Подготовиться и атаковать');r.ctx.Math.random=()=>0;const hp=r.E.getState().player.health;r.E.action('aim');assert.equal(r.E.getState().player.health,hp);assert.match(r.E.getState().combat.status,/ГОТОВИТ/);r.E.action('aim');assert.ok(r.E.getState().player.health<hp);r.load(eventSave(r,'v63_marshLeech'));select(r,'Подготовиться и атаковать');r.E.action('aim');assert.ok(r.E.getState().player.radiation>0);});
test('Local favicon is declared; all consumers preserve only declared stamina changes',()=>{const r=runtime(),html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.match(html,/rel="icon" href="assets\/favicon.svg"/);assert.ok(fs.existsSync(path.join(__dirname,'../assets/favicon.svg')));for(const [id,it]of Object.entries(r.I.items)){if(!['food','medicine','drink'].includes(it.type))continue;const s=r.S.fresh();s.player.stamina=10;s.player.hunger=80;s.inventory.push({id,qty:1});r.load(s);r.E.action('use',r.E.getState().inventory.findIndex(x=>x.id===id));assert.equal(r.E.getState().player.stamina,10+(it.effect?.stamina||0),id);}assert.equal(r.I.items.canned.effect.stamina,undefined);});
test('Every delivery quest checks readiness before consuming goods and pays once',()=>{const r=runtime();for(const d of r.W.quests.filter(q=>['deliver','deliverType'].includes(q.type))){const s=r.S.fresh();s.player.location=d.giverLocations[0];s.quests.active=[{id:d.id,step:0,progress:0}];s.inventory=s.inventory.filter(x=>x.id!==(d.item||'jellyfish'));s.inventory.push({id:d.item||'jellyfish',qty:d.count||1});r.load(s);const money=r.E.getState().player.money;r.E.action('turnIn',d.id);assert.ok(r.E.getState().quests.completed.some(q=>q.id===d.id),d.id);assert.equal(r.E.getState().player.money,money+d.reward);const after=JSON.stringify(r.E.getState().inventory);r.E.action('turnIn',d.id);assert.equal(r.E.getState().player.money,money+d.reward);assert.equal(JSON.stringify(r.E.getState().inventory),after);}});
test('New mutant artifacts are not routine drops; quest delivery UI uses actual stock',()=>{const r=runtime();for(const id of ['ratSwarm','marshLeech','ironBoar','nightLurker','ashWalker']){const e=r.W.enemyTypes[id];for(const item of e.loot.filter(id=>r.I.items[id].type==='artifact'))assert.ok(e.lootChances[item]<=.12);}const s=r.S.fresh();s.quests.active=[{id:'mara_bandages',step:0,progress:0}];r.load(s);const q=r.E.getState().quests.active[0];assert.equal(q.progress,1);assert.equal(q.status,'Готово к сдаче');});
console.log(passed+' v6.3 checks passed.');
